import type { ExpansionDeck } from './lexiconExpansion'

const A1_A2_PCIC = 'https://cvc.cervantes.es/ensenanza/biblioteca_ele/plan_curricular/niveles/09_nociones_especificas_inventario_a1-a2.htm'
const B1_B2_PCIC = 'https://cvc.cervantes.es/ensenanza/biblioteca_ele/plan_curricular/niveles/09_nociones_especificas_inventario_b1-b2.htm'

// Production batch 010: 96 canonical targets selected from remaining frequency gaps.
export const expansionBatch010: ExpansionDeck[] = [
  {
    id: 'expansion-a2-information-materials-010', level: 'A2', scene: '日常', title: '信息、材料与常见概念',
    description: '理解媒体信息、物体材料和日常说明中的常用词', frameworkReference: A1_A2_PCIC,
    words: [
      { spanish: 'artículo', chinese: '文章；物品；条款', example: 'He leído un artículo sobre salud.', exampleChinese: '我读了一篇关于健康的文章。', lemma: 'artículo', partOfSpeech: 'noun', frequencyRank: 350 },
      { spanish: 'tierra', chinese: '土地；地球；泥土', example: 'La planta necesita tierra húmeda.', exampleChinese: '这株植物需要湿润的土壤。', lemma: 'tierra', partOfSpeech: 'noun', frequencyRank: 366 },
      { spanish: 'atención', chinese: '注意；照顾；服务', example: 'Gracias por su atención.', exampleChinese: '感谢您的关注。', lemma: 'atención', partOfSpeech: 'noun', frequencyRank: 454 },
      { spanish: 'provincia', chinese: '省；省份', example: 'La ciudad está en otra provincia.', exampleChinese: '这座城市在另一个省。', lemma: 'provincia', partOfSpeech: 'noun', frequencyRank: 695 },
      { spanish: 'canal', chinese: '频道；渠道；运河', example: 'El canal ofrece noticias locales.', exampleChinese: '这个频道提供本地新闻。', lemma: 'canal', partOfSpeech: 'noun', frequencyRank: 982 },
      { spanish: 'prensa', chinese: '新闻界；报刊；压力机', example: 'La prensa publicó la noticia.', exampleChinese: '媒体发布了这条新闻。', lemma: 'prensa', partOfSpeech: 'noun', frequencyRank: 1000 },
      { spanish: 'técnica', chinese: '技术；技巧；方法', example: 'Esta técnica facilita el aprendizaje.', exampleChinese: '这种技巧让学习更容易。', lemma: 'técnica', partOfSpeech: 'noun', frequencyRank: 1535 },
      { spanish: 'plataforma', chinese: '平台；站台', example: 'La plataforma permite reservar citas.', exampleChinese: '这个平台可以预约。', lemma: 'plataforma', partOfSpeech: 'noun', frequencyRank: 1876 },
      { spanish: 'superficie', chinese: '表面；面积', example: 'Limpia la superficie de la mesa.', exampleChinese: '请清洁桌面。', lemma: 'superficie', partOfSpeech: 'noun', frequencyRank: 1921 },
      { spanish: 'software', chinese: '软件', example: 'El software necesita una actualización.', exampleChinese: '这个软件需要更新。', lemma: 'software', partOfSpeech: 'noun', frequencyRank: 1960 },
      { spanish: 'detalle', chinese: '细节；小礼物', example: 'Falta un detalle en el formulario.', exampleChinese: '表格里缺少一个细节。', lemma: 'detalle', partOfSpeech: 'noun', frequencyRank: 2493 },
      { spanish: 'ciclo', chinese: '周期；循环；阶段', example: 'El curso completa un ciclo anual.', exampleChinese: '这门课程完成一个年度周期。', lemma: 'ciclo', partOfSpeech: 'noun', frequencyRank: 2763 },
    ],
  },
  {
    id: 'expansion-a2-health-services-010', level: 'A2', scene: '健康', title: '健康、服务与日常用品',
    description: '谈论健康状况、家庭用品、购买与出行服务', frameworkReference: A1_A2_PCIC,
    words: [
      { spanish: 'cáncer', chinese: '癌症', example: 'La prevención ayuda a detectar el cáncer.', exampleChinese: '预防有助于发现癌症。', lemma: 'cáncer', partOfSpeech: 'noun', frequencyRank: 1844 },
      { spanish: 'mejora', chinese: '改善；好转', example: 'El paciente muestra una mejora clara.', exampleChinese: '患者有明显好转。', lemma: 'mejora', partOfSpeech: 'noun', frequencyRank: 3062 },
      { spanish: 'limpieza', chinese: '清洁；清扫', example: 'La limpieza se realiza cada mañana.', exampleChinese: '每天早上进行清洁。', lemma: 'limpieza', partOfSpeech: 'noun', frequencyRank: 3335 },
      { spanish: 'envío', chinese: '寄送；货件', example: 'El envío llegará mañana.', exampleChinese: '货件明天到达。', lemma: 'envío', partOfSpeech: 'noun', frequencyRank: 4331 },
      { spanish: 'casco', chinese: '头盔；外壳；老城区', example: 'Ponte el casco antes de salir.', exampleChinese: '出发前戴上头盔。', lemma: 'casco', partOfSpeech: 'noun', frequencyRank: 4771 },
      { spanish: 'alimento', chinese: '食物；食品', example: 'Cada alimento lleva una etiqueta.', exampleChinese: '每种食品都有标签。', lemma: 'alimento', partOfSpeech: 'noun', frequencyRank: 5066 },
      { spanish: 'bebida', chinese: '饮料', example: 'La bebida está demasiado fría.', exampleChinese: '饮料太凉了。', lemma: 'bebida', partOfSpeech: 'noun', frequencyRank: 5284 },
      { spanish: 'autopista', chinese: '高速公路', example: 'La autopista tiene mucho tráfico.', exampleChinese: '高速公路交通拥堵。', lemma: 'autopista', partOfSpeech: 'noun', frequencyRank: 5372 },
      { spanish: 'vendedor', chinese: '销售员；卖家', example: 'El vendedor explicó la garantía.', exampleChinese: '销售员解释了保修条款。', lemma: 'vendedor', partOfSpeech: 'noun', frequencyRank: 5574 },
      { spanish: 'harina', chinese: '面粉', example: 'La receta lleva harina y agua.', exampleChinese: '这个食谱需要面粉和水。', lemma: 'harina', partOfSpeech: 'noun', frequencyRank: 5624 },
      { spanish: 'ducha', chinese: '淋浴；淋浴间', example: 'La ducha no tiene agua caliente.', exampleChinese: '淋浴没有热水。', lemma: 'ducha', partOfSpeech: 'noun', frequencyRank: 5953 },
      { spanish: 'oficio', chinese: '职业；手艺；公文', example: 'Aprendió el oficio con su familia.', exampleChinese: '他跟家人学会了这门手艺。', lemma: 'oficio', partOfSpeech: 'noun', frequencyRank: 4930 },
    ],
  },
  {
    id: 'expansion-b1-public-scale-010', level: 'B1', scene: '社会', title: '公共范围与基本判断',
    description: '说明公共与私人范围、需求和社会经济尺度', frameworkReference: B1_B2_PCIC,
    words: [
      { spanish: 'nacional', chinese: '国家的；全国的', example: 'El programa tiene alcance nacional.', exampleChinese: '该计划覆盖全国。', lemma: 'nacional', partOfSpeech: 'adjective', frequencyRank: 165 },
      { spanish: 'internacional', chinese: '国际的', example: 'Es una organización internacional.', exampleChinese: '这是一个国际组织。', lemma: 'internacional', partOfSpeech: 'adjective', frequencyRank: 378 },
      { spanish: 'público', chinese: '公共的；公众', example: 'El transporte público funciona bien.', exampleChinese: '公共交通运行良好。', lemma: 'público', partOfSpeech: 'adjective', frequencyRank: 382 },
      { spanish: 'base', chinese: '基础；基地；底座', example: 'La confianza es la base del acuerdo.', exampleChinese: '信任是协议的基础。', lemma: 'base', partOfSpeech: 'noun', frequencyRank: 428 },
      { spanish: 'capital', chinese: '首都；资本；大写的', example: 'La empresa necesita más capital.', exampleChinese: '公司需要更多资本。', lemma: 'capital', partOfSpeech: 'noun', frequencyRank: 465 },
      { spanish: 'medida', chinese: '措施；尺寸；测量', example: 'La medida reduce el consumo de energía.', exampleChinese: '这项措施降低能源消耗。', lemma: 'medida', partOfSpeech: 'noun', frequencyRank: 725 },
      { spanish: 'sector', chinese: '行业；部门；区域', example: 'El sector turístico crea empleo.', exampleChinese: '旅游业创造就业。', lemma: 'sector', partOfSpeech: 'noun', frequencyRank: 813 },
      { spanish: 'necesidad', chinese: '需要；必要性', example: 'Existe una necesidad urgente de vivienda.', exampleChinese: '住房需求十分迫切。', lemma: 'necesidad', partOfSpeech: 'noun', frequencyRank: 830 },
      { spanish: 'materia', chinese: '科目；材料；物质', example: 'Esta materia requiere mucha lectura.', exampleChinese: '这门科目需要大量阅读。', lemma: 'materia', partOfSpeech: 'noun', frequencyRank: 1298 },
      { spanish: 'sección', chinese: '部分；栏目；部门', example: 'Consulta la sección de ayuda.', exampleChinese: '请查看帮助部分。', lemma: 'sección', partOfSpeech: 'noun', frequencyRank: 1330 },
      { spanish: 'privado', chinese: '私人的；私营的', example: 'El sector privado también participa.', exampleChinese: '私营部门也参与其中。', lemma: 'privado', partOfSpeech: 'adjective', frequencyRank: 1526 },
      { spanish: 'conciencia', chinese: '意识；良知', example: 'La campaña crea conciencia ambiental.', exampleChinese: '这项活动提升环保意识。', lemma: 'conciencia', partOfSpeech: 'noun', frequencyRank: 1502 },
    ],
  },
  {
    id: 'expansion-b1-space-experience-010', level: 'B1', scene: '环境', title: '空间、环境与个人体验',
    description: '描述自然环境、空间特征和复杂感受', frameworkReference: B1_B2_PCIC,
    words: [
      { spanish: 'símbolo', chinese: '符号；象征', example: 'La paloma es un símbolo de paz.', exampleChinese: '鸽子是和平的象征。', lemma: 'símbolo', partOfSpeech: 'noun', frequencyRank: 3217 },
      { spanish: 'testigo', chinese: '证人；见证者', example: 'El testigo describió el accidente.', exampleChinese: '证人描述了事故。', lemma: 'testigo', partOfSpeech: 'noun', frequencyRank: 3218 },
      { spanish: 'profundidad', chinese: '深度；深刻程度', example: 'El lago tiene mucha profundidad.', exampleChinese: '这个湖很深。', lemma: 'profundidad', partOfSpeech: 'noun', frequencyRank: 3352 },
      { spanish: 'virtual', chinese: '虚拟的；在线的', example: 'La reunión será virtual.', exampleChinese: '会议将在线举行。', lemma: 'virtual', partOfSpeech: 'adjective', frequencyRank: 3527 },
      { spanish: 'ancho', chinese: '宽的；宽度', example: 'El pasillo tiene dos metros de ancho.', exampleChinese: '走廊有两米宽。', lemma: 'ancho', partOfSpeech: 'adjective', frequencyRank: 3533 },
      { spanish: 'desierto', chinese: '沙漠；荒芜的', example: 'El desierto recibe poca lluvia.', exampleChinese: '沙漠降雨很少。', lemma: 'desierto', partOfSpeech: 'noun', frequencyRank: 3545 },
      { spanish: 'imaginación', chinese: '想象力；想象', example: 'La lectura desarrolla la imaginación.', exampleChinese: '阅读培养想象力。', lemma: 'imaginación', partOfSpeech: 'noun', frequencyRank: 4017 },
      { spanish: 'oscuridad', chinese: '黑暗；昏暗', example: 'La carretera queda en oscuridad.', exampleChinese: '这条道路陷入黑暗。', lemma: 'oscuridad', partOfSpeech: 'noun', frequencyRank: 4028 },
      { spanish: 'paisaje', chinese: '风景；景观', example: 'El tren cruza un paisaje verde.', exampleChinese: '火车穿过绿色景观。', lemma: 'paisaje', partOfSpeech: 'noun', frequencyRank: 4029 },
      { spanish: 'caos', chinese: '混乱；无序', example: 'El retraso causó caos en la estación.', exampleChinese: '延误造成车站混乱。', lemma: 'caos', partOfSpeech: 'noun', frequencyRank: 4059 },
      { spanish: 'fortaleza', chinese: '优势；力量；堡垒', example: 'La paciencia es su mayor fortaleza.', exampleChinese: '耐心是他最大的优势。', lemma: 'fortaleza', partOfSpeech: 'noun', frequencyRank: 4080 },
      { spanish: 'dificultad', chinese: '困难；难度', example: 'La tarea presenta cierta dificultad.', exampleChinese: '这项任务有一定难度。', lemma: 'dificultad', partOfSpeech: 'noun', frequencyRank: 4238 },
    ],
  },
  {
    id: 'expansion-b1-production-environment-010', level: 'B1', scene: '工作', title: '生产、规划与环境资源',
    description: '讨论生产流程、资金安排、技能培训和资源使用', frameworkReference: B1_B2_PCIC,
    words: [
      { spanish: 'descubrimiento', chinese: '发现', example: 'El descubrimiento cambió la investigación.', exampleChinese: '这项发现改变了研究。', lemma: 'descubrimiento', partOfSpeech: 'noun', frequencyRank: 4410 },
      { spanish: 'fabricación', chinese: '制造；生产', example: 'La fabricación utiliza materiales reciclados.', exampleChinese: '制造过程使用再生材料。', lemma: 'fabricación', partOfSpeech: 'noun', frequencyRank: 4425 },
      { spanish: 'importe', chinese: '金额；总额', example: 'Compruebe el importe antes de pagar.', exampleChinese: '付款前请核对金额。', lemma: 'importe', partOfSpeech: 'noun', frequencyRank: 4433 },
      { spanish: 'planificación', chinese: '规划；计划工作', example: 'La planificación evita retrasos.', exampleChinese: '规划可以避免延误。', lemma: 'planificación', partOfSpeech: 'noun', frequencyRank: 4449 },
      { spanish: 'psicología', chinese: '心理学；心理', example: 'Estudia psicología en la universidad.', exampleChinese: '她在大学学习心理学。', lemma: 'psicología', partOfSpeech: 'noun', frequencyRank: 4453 },
      { spanish: 'selva', chinese: '丛林；热带雨林', example: 'La selva alberga muchas especies.', exampleChinese: '雨林中生活着许多物种。', lemma: 'selva', partOfSpeech: 'noun', frequencyRank: 4462 },
      { spanish: 'depósito', chinese: '押金；存款；容器', example: 'El alquiler exige un depósito.', exampleChinese: '租房需要押金。', lemma: 'depósito', partOfSpeech: 'noun', frequencyRank: 4501 },
      { spanish: 'herencia', chinese: '遗产；继承', example: 'Recibió la casa como herencia.', exampleChinese: '他继承了这套房子。', lemma: 'herencia', partOfSpeech: 'noun', frequencyRank: 4515 },
      { spanish: 'observación', chinese: '观察；意见', example: 'La observación confirma el patrón.', exampleChinese: '观察证实了这一模式。', lemma: 'observación', partOfSpeech: 'noun', frequencyRank: 4532 },
      { spanish: 'aporte', chinese: '贡献；投入', example: 'Cada miembro hizo un aporte útil.', exampleChinese: '每位成员都作出了有用贡献。', lemma: 'aporte', partOfSpeech: 'noun', frequencyRank: 4577 },
      { spanish: 'capacitación', chinese: '培训；能力培养', example: 'La empresa ofrece capacitación digital.', exampleChinese: '公司提供数字技能培训。', lemma: 'capacitación', partOfSpeech: 'noun', frequencyRank: 4581 },
      { spanish: 'carbón', chinese: '煤；木炭', example: 'La región reduce el uso de carbón.', exampleChinese: '该地区正在减少煤炭使用。', lemma: 'carbón', partOfSpeech: 'noun', frequencyRank: 4582 },
    ],
  },
  {
    id: 'expansion-b2-governance-quality-010', level: 'B2', scene: '社会', title: '治理、规范与实施质量',
    description: '评价制度行动、正式规范和执行效果', frameworkReference: B1_B2_PCIC,
    words: [
      { spanish: 'eliminación', chinese: '消除；删除；淘汰', example: 'La eliminación de residuos exige control.', exampleChinese: '废弃物处理需要监管。', lemma: 'eliminación', partOfSpeech: 'noun', frequencyRank: 4416 },
      { spanish: 'excelencia', chinese: '卓越；优秀', example: 'El centro busca la excelencia educativa.', exampleChinese: '该中心追求教育卓越。', lemma: 'excelencia', partOfSpeech: 'noun', frequencyRank: 4423 },
      { spanish: 'legislativo', chinese: '立法的；立法机构', example: 'El proceso legislativo será largo.', exampleChinese: '立法过程会很漫长。', lemma: 'legislativo', partOfSpeech: 'adjective', frequencyRank: 4439 },
      { spanish: 'polémica', chinese: '争议；争论', example: 'La decisión generó una gran polémica.', exampleChinese: '这项决定引发巨大争议。', lemma: 'polémica', partOfSpeech: 'noun', frequencyRank: 4451 },
      { spanish: 'visual', chinese: '视觉的；可视的', example: 'El informe incluye un resumen visual.', exampleChinese: '报告包含视觉摘要。', lemma: 'visual', partOfSpeech: 'adjective', frequencyRank: 4470 },
      { spanish: 'magnitud', chinese: '规模；量级；大小', example: 'No se conoce la magnitud del daño.', exampleChinese: '损失规模尚不清楚。', lemma: 'magnitud', partOfSpeech: 'noun', frequencyRank: 4523 },
      { spanish: 'protocolo', chinese: '协议；规程；礼仪', example: 'El hospital actualizó el protocolo.', exampleChinese: '医院更新了规程。', lemma: 'protocolo', partOfSpeech: 'noun', frequencyRank: 4542 },
      { spanish: 'sello', chinese: '印章；邮票；标志', example: 'El documento necesita un sello oficial.', exampleChinese: '文件需要官方印章。', lemma: 'sello', partOfSpeech: 'noun', frequencyRank: 4550 },
      { spanish: 'utilización', chinese: '使用；利用', example: 'La utilización de datos requiere permiso.', exampleChinese: '使用数据需要许可。', lemma: 'utilización', partOfSpeech: 'noun', frequencyRank: 4563 },
      { spanish: 'bloqueo', chinese: '封锁；阻塞；冻结', example: 'El bloqueo de la cuenta fue temporal.', exampleChinese: '账户冻结是暂时的。', lemma: 'bloqueo', partOfSpeech: 'noun', frequencyRank: 4579 },
      { spanish: 'cuota', chinese: '费用；份额；配额', example: 'La cuota mensual incluye el servicio.', exampleChinese: '月费包含这项服务。', lemma: 'cuota', partOfSpeech: 'noun', frequencyRank: 4590 },
      { spanish: 'eficaz', chinese: '有效的；高效的', example: 'La medida resultó eficaz.', exampleChinese: '这项措施被证明有效。', lemma: 'eficaz', partOfSpeech: 'adjective', frequencyRank: 4597 },
    ],
  },
  {
    id: 'expansion-b2-institutions-standards-010', level: 'B2', scene: '行政', title: '机构、标准与社会流动',
    description: '理解机构数据、正式转移、社会流动和技术标准', frameworkReference: B1_B2_PCIC,
    words: [
      { spanish: 'estadística', chinese: '统计；统计数据', example: 'La estadística muestra una tendencia clara.', exampleChinese: '统计数据显示出明确趋势。', lemma: 'estadística', partOfSpeech: 'noun', frequencyRank: 4599 },
      { spanish: 'fiscalía', chinese: '检察机关', example: 'La fiscalía abrió una investigación.', exampleChinese: '检察机关展开了调查。', lemma: 'fiscalía', partOfSpeech: 'noun', frequencyRank: 4603 },
      { spanish: 'razonable', chinese: '合理的；适度的', example: 'El plazo parece razonable.', exampleChinese: '这个期限看起来合理。', lemma: 'razonable', partOfSpeech: 'adjective', frequencyRank: 4644 },
      { spanish: 'referente', chinese: '参照；标杆；代表人物', example: 'La ciudad es un referente cultural.', exampleChinese: '这座城市是文化标杆。', lemma: 'referente', partOfSpeech: 'noun', frequencyRank: 4645 },
      { spanish: 'terapia', chinese: '治疗；疗法', example: 'La terapia requiere varias sesiones.', exampleChinese: '治疗需要多个疗程。', lemma: 'terapia', partOfSpeech: 'noun', frequencyRank: 4657 },
      { spanish: 'transferencia', chinese: '转账；转移', example: 'La transferencia llegará mañana.', exampleChinese: '转账明天到账。', lemma: 'transferencia', partOfSpeech: 'noun', frequencyRank: 4661 },
      { spanish: 'virtud', chinese: '优点；美德', example: 'La claridad es la principal virtud del texto.', exampleChinese: '清晰是这篇文章的主要优点。', lemma: 'virtud', partOfSpeech: 'noun', frequencyRank: 4671 },
      { spanish: 'atmósfera', chinese: '大气；氛围', example: 'La atmósfera contiene varios gases.', exampleChinese: '大气含有多种气体。', lemma: 'atmósfera', partOfSpeech: 'noun', frequencyRank: 4678 },
      { spanish: 'estándar', chinese: '标准；标准的', example: 'El producto cumple el estándar europeo.', exampleChinese: '该产品符合欧洲标准。', lemma: 'estándar', partOfSpeech: 'noun', frequencyRank: 4706 },
      { spanish: 'inmigración', chinese: '移民；移民事务', example: 'El informe analiza la inmigración reciente.', exampleChinese: '报告分析近期移民情况。', lemma: 'inmigración', partOfSpeech: 'noun', frequencyRank: 4717 },
      { spanish: 'núcleo', chinese: '核心；中心；细胞核', example: 'La confianza forma el núcleo del acuerdo.', exampleChinese: '信任构成协议的核心。', lemma: 'núcleo', partOfSpeech: 'noun', frequencyRank: 4732 },
      { spanish: 'precisión', chinese: '精确；准确度', example: 'El informe describe los datos con precisión.', exampleChinese: '报告准确描述了数据。', lemma: 'precisión', partOfSpeech: 'noun', frequencyRank: 5424 },
    ],
  },
  {
    id: 'expansion-b2-evidence-change-010', level: 'B2', scene: '学习', title: '证据、变化与表达质量',
    description: '比较证据强度、变化趋势和表达效果', frameworkReference: B1_B2_PCIC,
    words: [
      { spanish: 'contraste', chinese: '对比；反差', example: 'El contraste entre los resultados es notable.', exampleChinese: '结果之间的反差很明显。', lemma: 'contraste', partOfSpeech: 'noun', frequencyRank: 5480 },
      { spanish: 'creencia', chinese: '信念；看法', example: 'La evidencia cuestiona esa creencia.', exampleChinese: '证据对这种看法提出质疑。', lemma: 'creencia', partOfSpeech: 'noun', frequencyRank: 5485 },
      { spanish: 'dimensión', chinese: '维度；规模；尺寸', example: 'El problema tiene una dimensión social.', exampleChinese: '这个问题具有社会层面。', lemma: 'dimensión', partOfSpeech: 'noun', frequencyRank: 5495 },
      { spanish: 'disminución', chinese: '减少；下降', example: 'Se observa una disminución del consumo.', exampleChinese: '可以观察到消费下降。', lemma: 'disminución', partOfSpeech: 'noun', frequencyRank: 5497 },
      { spanish: 'eficacia', chinese: '有效性；功效', example: 'El estudio evalúa la eficacia del tratamiento.', exampleChinese: '研究评估治疗的有效性。', lemma: 'eficacia', partOfSpeech: 'noun', frequencyRank: 5610 },
      { spanish: 'claridad', chinese: '清晰；明确', example: 'Explique la propuesta con claridad.', exampleChinese: '请清楚地解释这项提议。', lemma: 'claridad', partOfSpeech: 'noun', frequencyRank: 5701 },
      { spanish: 'creatividad', chinese: '创造力', example: 'El proyecto fomenta la creatividad.', exampleChinese: '该项目鼓励创造力。', lemma: 'creatividad', partOfSpeech: 'noun', frequencyRank: 5707 },
      { spanish: 'minoría', chinese: '少数；少数群体', example: 'La medida afecta a una minoría.', exampleChinese: '这项措施影响少数人。', lemma: 'minoría', partOfSpeech: 'noun', frequencyRank: 5755 },
      { spanish: 'motivación', chinese: '动机；积极性', example: 'La motivación mejora con objetivos claros.', exampleChinese: '明确目标能提升积极性。', lemma: 'motivación', partOfSpeech: 'noun', frequencyRank: 5757 },
      { spanish: 'probabilidad', chinese: '可能性；概率', example: 'La probabilidad de error es baja.', exampleChinese: '出错概率很低。', lemma: 'probabilidad', partOfSpeech: 'noun', frequencyRank: 5772 },
      { spanish: 'proporción', chinese: '比例；比重', example: 'La proporción de jóvenes ha aumentado.', exampleChinese: '年轻人的比例上升了。', lemma: 'proporción', partOfSpeech: 'noun', frequencyRank: 5878 },
      { spanish: 'récord', chinese: '纪录；记录', example: 'La cifra alcanzó un récord histórico.', exampleChinese: '这一数字创下历史纪录。', lemma: 'récord', partOfSpeech: 'noun', frequencyRank: 4460 },
    ],
  },
]
