import type { ExpansionDeck } from './lexiconExpansion'

const A1_A2_PCIC = 'https://cvc.cervantes.es/ensenanza/biblioteca_ele/plan_curricular/niveles/09_nociones_especificas_inventario_a1-a2.htm'
const B1_B2_PCIC = 'https://cvc.cervantes.es/ensenanza/biblioteca_ele/plan_curricular/niveles/09_nociones_especificas_inventario_b1-b2.htm'
type ExpansionWord = ExpansionDeck['words'][number]
const w = (spanish: string, chinese: string, example: string, exampleChinese: string, partOfSpeech: ExpansionWord['partOfSpeech'], frequencyRank: number): ExpansionWord => ({ spanish, chinese, example, exampleChinese, lemma: spanish, partOfSpeech, frequencyRank })

// Production batch 014: 96 canonical description, institutions, culture and science targets.
export const expansionBatch014: ExpansionDeck[] = [
  {
    id: 'expansion-a2-people-directions-014', level: 'A2', scene: '日常', title: '人物、方向与常见判断',
    description: '描述人物身份、方向和常见判断结果', frameworkReference: A1_A2_PCIC,
    words: [
      w('representante', '代表；销售代表', 'El representante explicó la propuesta.', '代表解释了这项提议。', 'noun', 2268),
      w('ideal', '理想的；理想', 'La habitación es ideal para una familia.', '这个房间很适合一家人。', 'adjective', 2295),
      w('ilegal', '非法的', 'Es ilegal aparcar aquí.', '在这里停车是违法的。', 'adjective', 2296),
      w('oriente', '东方；东部', 'La ventana mira hacia oriente.', '窗户朝东。', 'noun', 2407),
      w('pasión', '热情；激情', 'Estudia música con pasión.', '他满怀热情地学习音乐。', 'noun', 2410),
      w('regular', '一般的；规律的；固定的', 'El servicio tiene una calidad regular.', '这项服务质量一般。', 'adjective', 2633),
      w('horrible', '糟糕的；可怕的', 'El tráfico fue horrible.', '交通状况非常糟糕。', 'adjective', 2666),
      w('intelectual', '知识分子；智力的', 'La lectura exige un esfuerzo intelectual.', '阅读需要脑力投入。', 'adjective', 2670),
      w('liberal', '自由派的；宽松的', 'El partido tiene una posición liberal.', '该政党持自由派立场。', 'adjective', 2730),
      w('escolar', '学校的；学生', 'El transporte escolar llega temprano.', '校车很早到达。', 'adjective', 2982),
      w('teniente', '中尉；副职', 'El teniente dirigió el operativo.', '中尉指挥了行动。', 'noun', 3023),
      w('instante', '瞬间；片刻', 'Espere un instante, por favor.', '请稍等片刻。', 'noun', 3490),
    ],
  },
  {
    id: 'expansion-a2-science-events-014', level: 'A2', scene: '社会', title: '科学、活动与公共场所',
    description: '理解基础科学、公共活动和常见评价词', frameworkReference: A1_A2_PCIC,
    words: [
      w('nuclear', '核能的；核心的', 'La energía nuclear genera debate.', '核能引发讨论。', 'adjective', 3498),
      w('pacífico', '和平的；太平洋', 'El proceso fue pacífico.', '这一过程是和平的。', 'adjective', 3503),
      w('básico', '基本的；基础的', 'El curso enseña vocabulario básico.', '课程教授基础词汇。', 'adjective', 3676),
      w('negativo', '消极的；阴性的', 'El resultado fue negativo.', '结果为阴性。', 'adjective', 3724),
      w('dólar', '美元', 'Un dólar no es suficiente.', '一美元不够。', 'noun', 4240),
      w('noble', '高尚的；贵族', 'Ayudar a otros es un objetivo noble.', '帮助他人是一个高尚目标。', 'adjective', 4358),
      w('carnaval', '狂欢节', 'El carnaval llena las calles de música.', '狂欢节让街道充满音乐。', 'noun', 4401),
      w('monumento', '纪念碑；古迹', 'El monumento está abierto al público.', '古迹对公众开放。', 'noun', 4529),
      w('rival', '对手；竞争的', 'La empresa rival bajó sus precios.', '竞争公司降低了价格。', 'noun', 4549),
      w('semejante', '相似的；同类', 'Nunca había visto un caso semejante.', '我从未见过类似情况。', 'adjective', 4551),
      w('operativo', '行动；运行中的', 'El sistema vuelve a estar operativo.', '系统恢复运行。', 'adjective', 4812),
      w('sorprendente', '令人惊讶的', 'La mejora fue sorprendente.', '改善程度令人惊讶。', 'adjective', 4949),
    ],
  },
  {
    id: 'expansion-b1-political-systems-014', level: 'B1', scene: '社会', title: '政治体系与社会变化',
    description: '理解政治组织、制度变化和公共立场', frameworkReference: B1_B2_PCIC,
    words: [
      w('socialista', '社会主义者；社会主义的', 'El partido socialista presentó su programa.', '社会主义政党提出了纲领。', 'adjective', 2476),
      w('comunista', '共产主义者；共产主义的', 'El movimiento comunista tuvo influencia regional.', '共产主义运动曾在该地区产生影响。', 'adjective', 2596),
      w('correspondiente', '相应的；对应的', 'Adjunte el documento correspondiente.', '请附上相应文件。', 'adjective', 2871),
      w('democrático', '民主的', 'El proceso debe ser democrático.', '这一过程应当是民主的。', 'adjective', 3242),
      w('presidencial', '总统的；主席的', 'La elección presidencial será en mayo.', '总统选举将在五月举行。', 'adjective', 3282),
      w('aparición', '出现；露面', 'La aparición del problema fue repentina.', '问题突然出现。', 'noun', 3300),
      w('transición', '过渡；转型', 'La transición energética necesita inversión.', '能源转型需要投资。', 'noun', 3370),
      w('radical', '彻底的；激进的', 'La reforma supone un cambio radical.', '改革意味着彻底改变。', 'adjective', 3438),
      w('coalición', '联盟；联合政府', 'Los partidos formaron una coalición.', '各政党组成了联盟。', 'noun', 3765),
      w('manifestación', '示威；表现；显现', 'La manifestación terminó sin incidentes.', '示威活动平静结束。', 'noun', 3861),
      w('posesión', '拥有；就职；财产', 'El documento prueba la posesión de la vivienda.', '文件证明了房屋所有权。', 'noun', 3873),
      w('soberanía', '主权', 'La constitución protege la soberanía nacional.', '宪法保护国家主权。', 'noun', 3962),
    ],
  },
  {
    id: 'expansion-b1-authority-conflict-014', level: 'B1', scene: '行政', title: '公共权力与冲突处理',
    description: '理解公共候选、冲突事件和司法处理', frameworkReference: B1_B2_PCIC,
    words: [
      w('amante', '爱好者；情人', 'Es amante de la música clásica.', '他是古典音乐爱好者。', 'noun', 3977),
      w('occidente', '西方；西部', 'La región queda al occidente del país.', '该地区位于国家西部。', 'noun', 4026),
      w('administrativo', '行政的；办事人员', 'El trámite administrativo tarda una semana.', '行政手续需要一周。', 'adjective', 4135),
      w('candidatura', '候选资格；参选', 'Presentó su candidatura a la presidencia.', '他提交了总统候选申请。', 'noun', 4222),
      w('conquista', '征服；获得', 'La conquista cambió la historia de la región.', '征服改变了该地区历史。', 'noun', 4229),
      w('desaparición', '消失；失踪', 'La policía investiga la desaparición.', '警方调查失踪事件。', 'noun', 4235),
      w('ignorancia', '无知；不了解', 'La ignorancia de la norma no evita la multa.', '不了解规定并不能免除罚款。', 'noun', 4253),
      w('terrorismo', '恐怖主义', 'La cooperación busca prevenir el terrorismo.', '合作旨在预防恐怖主义。', 'noun', 4288),
      w('policial', '警察的；警方的', 'La investigación policial continúa.', '警方调查仍在继续。', 'adjective', 4369),
      w('captura', '抓捕；捕获；截图', 'La captura del sospechoso fue confirmada.', '嫌疑人被捕得到确认。', 'noun', 4400),
      w('socialismo', '社会主义', 'El libro analiza la historia del socialismo.', '这本书分析社会主义历史。', 'noun', 4464),
      w('invasión', '入侵；侵占', 'La invasión provocó una crisis humanitaria.', '入侵引发人道危机。', 'noun', 4518),
    ],
  },
  {
    id: 'expansion-b1-law-society-014', level: 'B1', scene: '社会', title: '法律、制度与社会责任',
    description: '讨论法律责任、制度结构和社会伤害', frameworkReference: B1_B2_PCIC,
    words: [
      w('terrorista', '恐怖分子；恐怖主义的', 'La policía detuvo al terrorista.', '警方逮捕了恐怖分子。', 'noun', 4658),
      w('persecución', '追捕；迫害', 'La persecución política obligó a muchas personas a salir.', '政治迫害迫使许多人离开。', 'noun', 4735),
      w('colonial', '殖民的', 'El museo conserva edificios de época colonial.', '博物馆保存殖民时期建筑。', 'adjective', 4865),
      w('capitalismo', '资本主义', 'El curso compara capitalismo y socialismo.', '课程比较资本主义和社会主义。', 'noun', 4977),
      w('detención', '拘留；停止', 'La detención fue revisada por un juez.', '拘留由法官审查。', 'noun', 5095),
      w('jurídico', '法律的；法务人员', 'Necesitamos asesoramiento jurídico.', '我们需要法律咨询。', 'adjective', 5125),
      w('monarquía', '君主制；王室', 'El país mantiene una monarquía parlamentaria.', '该国保留议会君主制。', 'noun', 5335),
      w('hermandad', '兄弟情谊；团体', 'La comunidad celebró su hermandad.', '社区庆祝彼此情谊。', 'noun', 5398),
      w('dirigente', '领导人；负责人', 'La dirigente anunció nuevas medidas.', '领导人宣布了新措施。', 'noun', 5496),
      w('impunidad', '有罪不罚；逍遥法外', 'La reforma busca acabar con la impunidad.', '改革旨在终结有罪不罚。', 'noun', 5520),
      w('piedad', '怜悯；虔诚', 'Pidió piedad al tribunal.', '他请求法庭宽恕。', 'noun', 5545),
      w('tortura', '酷刑；折磨', 'La ley prohíbe toda forma de tortura.', '法律禁止任何形式的酷刑。', 'noun', 5678),
    ],
  },
  {
    id: 'expansion-b2-travel-infrastructure-014', level: 'B2', scene: '旅行', title: '交通、公共空间与社会结构',
    description: '分析交通网络、公共空间和社会结构变化', frameworkReference: B1_B2_PCIC,
    words: [
      w('navegación', '导航；航行；浏览', 'La aplicación ofrece navegación sin conexión.', '应用提供离线导航。', 'noun', 5760),
      w('ampliación', '扩大；扩建', 'La ampliación del metro reducirá el tráfico.', '地铁扩建将缓解交通。', 'noun', 5793),
      w('aéreo', '航空的；空中的', 'El transporte aéreo aumentó este año.', '航空运输今年有所增长。', 'adjective', 5798),
      w('barrera', '障碍；屏障', 'El precio es una barrera para muchas familias.', '价格对许多家庭构成障碍。', 'noun', 5801),
      w('bronce', '青铜；铜牌', 'La estatua está hecha de bronce.', '雕像由青铜制成。', 'noun', 5802),
      w('cadáver', '遗体；尸体', 'El cadáver fue identificado por la policía.', '遗体由警方确认身份。', 'noun', 5803),
      w('católico', '天主教徒；天主教的', 'El colegio tiene origen católico.', '这所学校起源于天主教机构。', 'adjective', 5806),
      w('estatua', '雕像', 'La estatua ocupa el centro de la plaza.', '雕像位于广场中央。', 'noun', 5831),
      w('feminista', '女权主义者；女权主义的', 'El movimiento feminista organizó la marcha.', '女权运动组织了游行。', 'adjective', 5832),
      w('ferrocarril', '铁路；铁路运输', 'El ferrocarril conecta las dos ciudades.', '铁路连接这两座城市。', 'noun', 5833),
      w('legislatura', '立法届期；立法机构', 'La reforma se debatirá esta legislatura.', '改革将在本届立法期讨论。', 'noun', 5849),
      w('literario', '文学的', 'El premio literario se entrega en octubre.', '文学奖十月颁发。', 'adjective', 5852),
    ],
  },
  {
    id: 'expansion-b2-methods-culture-014', level: 'B2', scene: '学习', title: '方法、文化与认知表达',
    description: '理解技术方法、文化表达和认知框架', frameworkReference: B1_B2_PCIC,
    words: [
      w('manipulación', '操纵；操作；篡改', 'La manipulación de datos destruye la confianza.', '篡改数据会破坏信任。', 'noun', 5854),
      w('mecánica', '机械学；运作原理', 'La mecánica del sistema es sencilla.', '系统的运作原理很简单。', 'noun', 5856),
      w('paralelo', '平行的；对照', 'El informe establece un paralelo entre ambos casos.', '报告对两个案例作了对照。', 'noun', 5866),
      w('supervivencia', '生存；存活', 'El agua es esencial para la supervivencia.', '水对于生存至关重要。', 'noun', 5895),
      w('tribu', '部落；群体', 'La tribu conserva su lengua tradicional.', '这个部落保留其传统语言。', 'noun', 5903),
      w('acento', '重音；口音', 'La palabra lleva acento en la última sílaba.', '这个词的重音在最后一个音节。', 'noun', 5910),
      w('acusación', '指控；起诉', 'La acusación presentó nuevas pruebas.', '控方提交了新证据。', 'noun', 5911),
      w('armonía', '和谐；和声', 'Los colores combinan en armonía.', '这些颜色搭配和谐。', 'noun', 5918),
      w('auténtico', '真正的；正宗的', 'El documento parece auténtico.', '文件看起来是真的。', 'adjective', 5921),
      w('constituyente', '制宪的；制宪者', 'La asamblea constituyente redactó la carta.', '制宪会议起草了宪章。', 'adjective', 5935),
      w('esclavitud', '奴隶制；奴役', 'La exposición explica la historia de la esclavitud.', '展览讲述奴隶制历史。', 'noun', 5956),
      w('homicidio', '杀人罪；凶杀', 'La fiscalía investiga el homicidio.', '检察机关调查这起凶杀案。', 'noun', 5968),
    ],
  },
  {
    id: 'expansion-b2-science-expression-014', level: 'B2', scene: '学习', title: '科学实验与表达结构',
    description: '描述实验、互动、数学和叙事结构', frameworkReference: B1_B2_PCIC,
    words: [
      w('experimento', '实验；试验', 'El experimento confirma la hipótesis.', '实验证实了假设。', 'noun', 5961),
      w('interacción', '互动；相互作用', 'La interacción mejora el aprendizaje.', '互动能改善学习效果。', 'noun', 5977),
      w('maquillaje', '化妆；化妆品；掩饰', 'El maquillaje contiene ingredientes naturales.', '化妆品含有天然成分。', 'noun', 5982),
      w('matemática', '数学；数学的', 'La matemática ayuda a interpretar los datos.', '数学有助于解释数据。', 'noun', 5984),
      w('mentalidad', '思维方式；心态', 'La formación cambió su mentalidad.', '培训改变了他的思维方式。', 'noun', 5985),
      w('nacionalismo', '民族主义', 'El ensayo analiza el nacionalismo moderno.', '文章分析现代民族主义。', 'noun', 5990),
      w('narrativa', '叙事；叙事作品', 'La narrativa del informe es coherente.', '报告的叙述是连贯的。', 'noun', 5991),
      w('cálculo', '计算；估算', 'El cálculo incluye impuestos y gastos.', '计算包含税费和支出。', 'noun', 5194),
      w('determinación', '决心；确定', 'Actuó con determinación.', '他行事果断。', 'noun', 5822),
      w('enfrentamiento', '冲突；对抗', 'El enfrentamiento terminó con un acuerdo.', '冲突最终以协议结束。', 'noun', 5826),
      w('referéndum', '全民公投', 'La reforma será sometida a referéndum.', '改革将提交全民公投。', 'noun', 5777),
      w('balón', '球；皮球', 'El balón salió del campo.', '球出了场地。', 'noun', 5800),
    ],
  },
]
