import type { ExpansionDeck } from './lexiconExpansion'

const A1_A2_PCIC = 'https://cvc.cervantes.es/ensenanza/biblioteca_ele/plan_curricular/niveles/09_nociones_especificas_inventario_a1-a2.htm'
const B1_B2_PCIC = 'https://cvc.cervantes.es/ensenanza/biblioteca_ele/plan_curricular/niveles/09_nociones_especificas_inventario_b1-b2.htm'

// Production batch 008: 96 canonical daily and public-language targets.
export const expansionBatch008: ExpansionDeck[] = [
  {
    id: 'expansion-a1-travel-shopping-008', level: 'A1', scene: '旅行', title: '旅行、购物与常用物品',
    description: '在旅途中辨认地点、设备、交通和购物信息',
    frameworkReference: A1_A2_PCIC,
    words: [
      { spanish: 'costa', chinese: '海岸；沿海地区', example: 'El tren recorre la costa.', exampleChinese: '火车沿海岸行驶。', lemma: 'costa', partOfSpeech: 'noun', frequencyRank: 841 },
      { spanish: 'cámara', chinese: '相机；摄像机；房间', example: 'Llevo una cámara pequeña.', exampleChinese: '我带着一台小相机。', lemma: 'cámara', partOfSpeech: 'noun', frequencyRank: 845 },
      { spanish: 'guía', chinese: '指南；导游', example: 'La guía explica la ruta.', exampleChinese: '导游讲解路线。', lemma: 'guía', partOfSpeech: 'noun', frequencyRank: 2345 },
      { spanish: 'máquina', chinese: '机器；设备', example: 'La máquina acepta tarjetas.', exampleChinese: '机器接受银行卡。', lemma: 'máquina', partOfSpeech: 'noun', frequencyRank: 2356 },
      { spanish: 'gasolina', chinese: '汽油', example: 'Necesitamos gasolina para el viaje.', exampleChinese: '这次旅行我们需要汽油。', lemma: 'gasolina', partOfSpeech: 'noun', frequencyRank: 3786 },
      { spanish: 'pesca', chinese: '捕鱼；渔业', example: 'La pesca es importante en esta costa.', exampleChinese: '渔业在这片海岸很重要。', lemma: 'pesca', partOfSpeech: 'noun', frequencyRank: 3870 },
      { spanish: 'recepción', chinese: '前台；接待；接收', example: 'Deja la llave en recepción.', exampleChinese: '把钥匙留在前台。', lemma: 'recepción', partOfSpeech: 'noun', frequencyRank: 4189 },
      { spanish: 'océano', chinese: '海洋', example: 'La habitación tiene vistas al océano.', exampleChinese: '房间可以看到海洋。', lemma: 'océano', partOfSpeech: 'noun', frequencyRank: 4271 },
      { spanish: 'pizza', chinese: '比萨饼', example: 'Compartimos una pizza para cenar.', exampleChinese: '我们晚餐分吃一个比萨饼。', lemma: 'pizza', partOfSpeech: 'noun', frequencyRank: 4537 },
      { spanish: 'bus', chinese: '公交车；大巴', example: 'El bus sale a las nueve.', exampleChinese: '大巴九点出发。', lemma: 'bus', partOfSpeech: 'noun', frequencyRank: 4683 },
      { spanish: 'descuento', chinese: '折扣', example: 'La tienda ofrece un descuento hoy.', exampleChinese: '商店今天提供折扣。', lemma: 'descuento', partOfSpeech: 'noun', frequencyRank: 4879 },
      { spanish: 'sombrero', chinese: '帽子', example: 'Necesito un sombrero para el sol.', exampleChinese: '我需要一顶遮阳帽。', lemma: 'sombrero', partOfSpeech: 'noun', frequencyRank: 5892 },
    ],
  },
  {
    id: 'expansion-a1-health-kitchen-008', level: 'A1', scene: '健康', title: '身体、饮食与基础账单',
    description: '描述健康部位、用餐和日常付款事项',
    frameworkReference: A1_A2_PCIC,
    words: [
      { spanish: 'doctor', chinese: '医生', example: 'El doctor trabaja en esta clínica.', exampleChinese: '这位医生在这家诊所工作。', lemma: 'doctor', partOfSpeech: 'noun', frequencyRank: 1085 },
      { spanish: 'cerebro', chinese: '大脑', example: 'El cerebro necesita descanso.', exampleChinese: '大脑需要休息。', lemma: 'cerebro', partOfSpeech: 'noun', frequencyRank: 1972 },
      { spanish: 'herida', chinese: '伤口；受伤', example: 'La herida está limpia.', exampleChinese: '伤口是干净的。', lemma: 'herida', partOfSpeech: 'noun', frequencyRank: 4431 },
      { spanish: 'hombro', chinese: '肩膀', example: 'Me duele el hombro derecho.', exampleChinese: '我的右肩疼。', lemma: 'hombro', partOfSpeech: 'noun', frequencyRank: 5008 },
      { spanish: 'adulto', chinese: '成年人；成年的', example: 'Cada adulto necesita una entrada.', exampleChinese: '每位成年人都需要一张票。', lemma: 'adulto', partOfSpeech: 'noun', frequencyRank: 5062 },
      { spanish: 'almuerzo', chinese: '午餐', example: 'El almuerzo empieza a la una.', exampleChinese: '午餐一点开始。', lemma: 'almuerzo', partOfSpeech: 'noun', frequencyRank: 5277 },
      { spanish: 'hueso', chinese: '骨头；骨骼', example: 'La radiografía muestra un hueso roto.', exampleChinese: 'X光片显示一根骨头断了。', lemma: 'hueso', partOfSpeech: 'noun', frequencyRank: 5316 },
      { spanish: 'estómago', chinese: '胃；腹部', example: 'Me duele el estómago.', exampleChinese: '我胃疼。', lemma: 'estómago', partOfSpeech: 'noun', frequencyRank: 5615 },
      { spanish: 'sopa', chinese: '汤', example: 'La sopa lleva verduras.', exampleChinese: '汤里有蔬菜。', lemma: 'sopa', partOfSpeech: 'noun', frequencyRank: 5673 },
      { spanish: 'cuchillo', chinese: '刀；餐刀', example: 'Corta el pan con este cuchillo.', exampleChinese: '用这把刀切面包。', lemma: 'cuchillo', partOfSpeech: 'noun', frequencyRank: 5941 },
      { spanish: 'factura', chinese: '账单；发票', example: 'La factura incluye el impuesto.', exampleChinese: '账单包含税费。', lemma: 'factura', partOfSpeech: 'noun', frequencyRank: 5962 },
      { spanish: 'limón', chinese: '柠檬', example: 'Quiero agua con limón.', exampleChinese: '我想要柠檬水。', lemma: 'limón', partOfSpeech: 'noun', frequencyRank: 5980 },
    ],
  },
  {
    id: 'expansion-a2-education-008', level: 'A2', scene: '学习', title: '教育、阅读与学习路径',
    description: '谈论课程、学校阶段和学习方法',
    frameworkReference: A1_A2_PCIC,
    words: [
      { spanish: 'título', chinese: '标题；学位；证书', example: 'El texto tiene un título claro.', exampleChinese: '文章有一个清晰标题。', lemma: 'título', partOfSpeech: 'noun', frequencyRank: 860 },
      { spanish: 'facultad', chinese: '学院；能力', example: 'La facultad está cerca de la biblioteca.', exampleChinese: '学院在图书馆附近。', lemma: 'facultad', partOfSpeech: 'noun', frequencyRank: 1449 },
      { spanish: 'lectura', chinese: '阅读；读物', example: 'La lectura diaria mejora el vocabulario.', exampleChinese: '每日阅读能提高词汇量。', lemma: 'lectura', partOfSpeech: 'noun', frequencyRank: 2083 },
      { spanish: 'academia', chinese: '学院；培训机构', example: 'La academia ofrece clases por la tarde.', exampleChinese: '培训机构下午提供课程。', lemma: 'academia', partOfSpeech: 'noun', frequencyRank: 2433 },
      { spanish: 'diálogo', chinese: '对话；交流', example: 'El diálogo tiene cuatro preguntas.', exampleChinese: '这段对话有四个问题。', lemma: 'diálogo', partOfSpeech: 'noun', frequencyRank: 2445 },
      { spanish: 'escritura', chinese: '写作；书写', example: 'La escritura necesita mucha práctica.', exampleChinese: '写作需要大量练习。', lemma: 'escritura', partOfSpeech: 'noun', frequencyRank: 3049 },
      { spanish: 'aprendizaje', chinese: '学习；习得', example: 'El aprendizaje continúa fuera de clase.', exampleChinese: '学习在课外继续。', lemma: 'aprendizaje', partOfSpeech: 'noun', frequencyRank: 3381 },
      { spanish: 'ensayo', chinese: '文章；试验；排练', example: 'El ensayo presenta una opinión personal.', exampleChinese: '这篇文章提出个人观点。', lemma: 'ensayo', partOfSpeech: 'noun', frequencyRank: 3403 },
      { spanish: 'ocupación', chinese: '职业；占用', example: 'Escriba su ocupación en el formulario.', exampleChinese: '请在表格中填写职业。', lemma: 'ocupación', partOfSpeech: 'noun', frequencyRank: 3500 },
      { spanish: 'orientación', chinese: '指导；方向；方位', example: 'El centro ofrece orientación laboral.', exampleChinese: '该中心提供就业指导。', lemma: 'orientación', partOfSpeech: 'noun', frequencyRank: 3580 },
      { spanish: 'académico', chinese: '学术的；学年相关的', example: 'El curso académico empieza en septiembre.', exampleChinese: '学年九月开始。', lemma: 'académico', partOfSpeech: 'adjective', frequencyRank: 3750 },
      { spanish: 'lección', chinese: '课；教训', example: 'La lección incluye un ejercicio de audio.', exampleChinese: '这节课包含一个听力练习。', lemma: 'lección', partOfSpeech: 'noun', frequencyRank: 4088 },
    ],
  },
  {
    id: 'expansion-a2-emotional-health-008', level: 'A2', scene: '情绪', title: '心理感受与个人状态',
    description: '描述性格、情绪变化和常见心理状态',
    frameworkReference: A1_A2_PCIC,
    words: [
      { spanish: 'sensación', chinese: '感觉；感受', example: 'Tengo una sensación extraña.', exampleChinese: '我有一种奇怪的感觉。', lemma: 'sensación', partOfSpeech: 'noun', frequencyRank: 1996 },
      { spanish: 'felicidad', chinese: '幸福；快乐', example: 'La familia celebró la noticia con felicidad.', exampleChinese: '全家幸福地庆祝这条消息。', lemma: 'felicidad', partOfSpeech: 'noun', frequencyRank: 2342 },
      { spanish: 'personalidad', chinese: '个性；人格', example: 'Tiene una personalidad abierta.', exampleChinese: '他的性格很开朗。', lemma: 'personalidad', partOfSpeech: 'noun', frequencyRank: 2357 },
      { spanish: 'paciencia', chinese: '耐心', example: 'Aprender un idioma requiere paciencia.', exampleChinese: '学习一门语言需要耐心。', lemma: 'paciencia', partOfSpeech: 'noun', frequencyRank: 3275 },
      { spanish: 'curiosidad', chinese: '好奇心', example: 'La pregunta despertó mi curiosidad.', exampleChinese: '这个问题激起了我的好奇心。', lemma: 'curiosidad', partOfSpeech: 'noun', frequencyRank: 3390 },
      { spanish: 'soledad', chinese: '孤独；独处', example: 'La soledad puede afectar al bienestar.', exampleChinese: '孤独可能影响身心健康。', lemma: 'soledad', partOfSpeech: 'noun', frequencyRank: 3517 },
      { spanish: 'temor', chinese: '担忧；恐惧', example: 'Existe temor a perder el trabajo.', exampleChinese: '人们担心失去工作。', lemma: 'temor', partOfSpeech: 'noun', frequencyRank: 3520 },
      { spanish: 'calma', chinese: '平静；冷静', example: 'Habla con calma.', exampleChinese: '请冷静地说。', lemma: 'calma', partOfSpeech: 'noun', frequencyRank: 3615 },
      { spanish: 'depresión', chinese: '抑郁；低气压；下降', example: 'La depresión requiere atención profesional.', exampleChinese: '抑郁需要专业关注。', lemma: 'depresión', partOfSpeech: 'noun', frequencyRank: 3772 },
      { spanish: 'emoción', chinese: '情绪；激动', example: 'Cada emoción tiene una causa.', exampleChinese: '每种情绪都有原因。', lemma: 'emoción', partOfSpeech: 'noun', frequencyRank: 3777 },
      { spanish: 'tristeza', chinese: '悲伤', example: 'La despedida produjo tristeza.', exampleChinese: '告别带来了悲伤。', lemma: 'tristeza', partOfSpeech: 'noun', frequencyRank: 4046 },
      { spanish: 'confusión', chinese: '困惑；混乱', example: 'La explicación causó más confusión.', exampleChinese: '这番解释造成了更多困惑。', lemma: 'confusión', partOfSpeech: 'noun', frequencyRank: 4691 },
    ],
  },
  {
    id: 'expansion-b1-environment-economy-008', level: 'B1', scene: '环境', title: '环境、产业与经济变化',
    description: '讨论能源、生产、经济指标和社会变化',
    frameworkReference: B1_B2_PCIC,
    words: [
      { spanish: 'solar', chinese: '太阳的；太阳能的', example: 'La energía solar reduce el gasto.', exampleChinese: '太阳能降低支出。', lemma: 'solar', partOfSpeech: 'adjective', frequencyRank: 3215 },
      { spanish: 'explotación', chinese: '开发；经营；剥削', example: 'La explotación de recursos exige control.', exampleChinese: '资源开发需要监管。', lemma: 'explotación', partOfSpeech: 'noun', frequencyRank: 3322 },
      { spanish: 'incremento', chinese: '增加；增长', example: 'El informe muestra un incremento del empleo.', exampleChinese: '报告显示就业增长。', lemma: 'incremento', partOfSpeech: 'noun', frequencyRank: 3330 },
      { spanish: 'expansión', chinese: '扩张；扩展', example: 'La empresa prepara su expansión regional.', exampleChinese: '公司准备在地区内扩张。', lemma: 'expansión', partOfSpeech: 'noun', frequencyRank: 3631 },
      { spanish: 'rescate', chinese: '营救；救援', example: 'El equipo de rescate llegó pronto.', exampleChinese: '救援队很快到达。', lemma: 'rescate', partOfSpeech: 'noun', frequencyRank: 3657 },
      { spanish: 'transformación', chinese: '转变；改造', example: 'La ciudad vive una transformación rápida.', exampleChinese: '这座城市正在快速转型。', lemma: 'transformación', partOfSpeech: 'noun', frequencyRank: 3746 },
      { spanish: 'coordinación', chinese: '协调；配合', example: 'La respuesta necesita buena coordinación.', exampleChinese: '应对工作需要良好协调。', lemma: 'coordinación', partOfSpeech: 'noun', frequencyRank: 3768 },
      { spanish: 'flujo', chinese: '流动；流程；流量', example: 'El sistema controla el flujo de agua.', exampleChinese: '系统控制水流。', lemma: 'flujo', partOfSpeech: 'noun', frequencyRank: 3783 },
      { spanish: 'química', chinese: '化学', example: 'La química explica esta reacción.', exampleChinese: '化学解释了这一反应。', lemma: 'química', partOfSpeech: 'noun', frequencyRank: 3806 },
      { spanish: 'ética', chinese: '伦理；道德规范', example: 'La investigación debe respetar la ética.', exampleChinese: '研究必须遵守伦理规范。', lemma: 'ética', partOfSpeech: 'noun', frequencyRank: 3891 },
      { spanish: 'ideología', chinese: '意识形态；思想体系', example: 'El debate no depende de una sola ideología.', exampleChinese: '这场讨论不取决于单一意识形态。', lemma: 'ideología', partOfSpeech: 'noun', frequencyRank: 4015 },
      { spanish: 'inflación', chinese: '通货膨胀', example: 'La inflación afecta a los precios.', exampleChinese: '通货膨胀影响价格。', lemma: 'inflación', partOfSpeech: 'noun', frequencyRank: 4018 },
    ],
  },
  {
    id: 'expansion-b1-administration-008', level: 'B1', scene: '行政', title: '行政、金融与正式文件',
    description: '理解居留、司法、金融和公共文件流程',
    frameworkReference: B1_B2_PCIC,
    words: [
      { spanish: 'nacionalidad', chinese: '国籍', example: 'El formulario pregunta la nacionalidad.', exampleChinese: '表格询问国籍。', lemma: 'nacionalidad', partOfSpeech: 'noun', frequencyRank: 3945 },
      { spanish: 'redacción', chinese: '写作；编辑部；措辞', example: 'La redacción del contrato debe ser clara.', exampleChinese: '合同措辞必须清晰。', lemma: 'redacción', partOfSpeech: 'noun', frequencyRank: 4037 },
      { spanish: 'banca', chinese: '银行业；银行系统', example: 'La banca ofrece nuevos servicios digitales.', exampleChinese: '银行业提供新的数字服务。', lemma: 'banca', partOfSpeech: 'noun', frequencyRank: 4056 },
      { spanish: 'censo', chinese: '人口普查；名册', example: 'El censo recoge datos de población.', exampleChinese: '人口普查收集人口数据。', lemma: 'censo', partOfSpeech: 'noun', frequencyRank: 4060 },
      { spanish: 'crónica', chinese: '纪实报道；编年史', example: 'La crónica describe los hechos del día.', exampleChinese: '报道描述了当天发生的事情。', lemma: 'crónica', partOfSpeech: 'noun', frequencyRank: 4069 },
      { spanish: 'delegación', chinese: '代表团；办事处；授权', example: 'La delegación se reunió con el alcalde.', exampleChinese: '代表团会见了市长。', lemma: 'delegación', partOfSpeech: 'noun', frequencyRank: 4071 },
      { spanish: 'despacho', chinese: '办公室；事务所', example: 'La cita es en el despacho número cuatro.', exampleChinese: '预约地点在四号办公室。', lemma: 'despacho', partOfSpeech: 'noun', frequencyRank: 4072 },
      { spanish: 'documentación', chinese: '文件资料；证件', example: 'Traiga toda la documentación necesaria.', exampleChinese: '请带齐所需文件。', lemma: 'documentación', partOfSpeech: 'noun', frequencyRank: 4076 },
      { spanish: 'finanzas', chinese: '财务；金融', example: 'El curso explica las finanzas personales.', exampleChinese: '课程讲解个人财务。', lemma: 'finanzas', partOfSpeech: 'noun', frequencyRank: 4079 },
      { spanish: 'juzgado', chinese: '法院；法庭机构', example: 'El documento se presenta en el juzgado.', exampleChinese: '文件提交到法院。', lemma: 'juzgado', partOfSpeech: 'noun', frequencyRank: 4169 },
      { spanish: 'convenio', chinese: '协议；协定', example: 'Las dos entidades firmaron un convenio.', exampleChinese: '两个机构签署了协议。', lemma: 'convenio', partOfSpeech: 'noun', frequencyRank: 4145 },
      { spanish: 'regulación', chinese: '监管；规定', example: 'La regulación protege a los consumidores.', exampleChinese: '监管规定保护消费者。', lemma: 'regulación', partOfSpeech: 'noun', frequencyRank: 4282 },
    ],
  },
  {
    id: 'expansion-b2-public-state-008', level: 'B2', scene: '社会', title: '公共状态与制度范围',
    description: '描述制度稳定性、地域范围和社会后果',
    frameworkReference: B1_B2_PCIC,
    words: [
      { spanish: 'esencial', chinese: '必不可少的；本质的', example: 'La transparencia es esencial para la confianza.', exampleChinese: '透明度对于建立信任必不可少。', lemma: 'esencial', partOfSpeech: 'adjective', frequencyRank: 3780 },
      { spanish: 'totalidad', chinese: '全部；整体', example: 'La medida afecta a la totalidad del sector.', exampleChinese: '这项措施影响整个行业。', lemma: 'totalidad', partOfSpeech: 'noun', frequencyRank: 3815 },
      { spanish: 'panorama', chinese: '全景；局面', example: 'El informe ofrece un panorama general.', exampleChinese: '报告提供总体概况。', lemma: 'panorama', partOfSpeech: 'noun', frequencyRank: 4098 },
      { spanish: 'sufrimiento', chinese: '痛苦；苦难', example: 'La crisis causó mucho sufrimiento.', exampleChinese: '危机造成了许多痛苦。', lemma: 'sufrimiento', partOfSpeech: 'noun', frequencyRank: 4120 },
      { spanish: 'estable', chinese: '稳定的', example: 'La situación permanece estable.', exampleChinese: '局势保持稳定。', lemma: 'estable', partOfSpeech: 'adjective', frequencyRank: 4160 },
      { spanish: 'exceso', chinese: '过量；超出', example: 'El exceso de tráfico aumenta la contaminación.', exampleChinese: '交通过量加剧污染。', lemma: 'exceso', partOfSpeech: 'noun', frequencyRank: 4162 },
      { spanish: 'institucional', chinese: '机构的；制度的', example: 'La reforma necesita apoyo institucional.', exampleChinese: '改革需要机构支持。', lemma: 'institucional', partOfSpeech: 'adjective', frequencyRank: 4168 },
      { spanish: 'longitud', chinese: '长度；经度', example: 'La longitud del puente supera un kilómetro.', exampleChinese: '这座桥的长度超过一公里。', lemma: 'longitud', partOfSpeech: 'noun', frequencyRank: 4174 },
      { spanish: 'represión', chinese: '镇压；压制', example: 'El informe denuncia la represión política.', exampleChinese: '报告谴责政治压制。', lemma: 'represión', partOfSpeech: 'noun', frequencyRank: 4194 },
      { spanish: 'territorial', chinese: '领土的；地域的', example: 'La reforma cambia la organización territorial.', exampleChinese: '改革改变地域组织方式。', lemma: 'territorial', partOfSpeech: 'adjective', frequencyRank: 4205 },
      { spanish: 'tragedia', chinese: '悲剧；灾难', example: 'La comunidad recuerda la tragedia.', exampleChinese: '社区铭记这场悲剧。', lemma: 'tragedia', partOfSpeech: 'noun', frequencyRank: 4207 },
      { spanish: 'vigente', chinese: '现行的；有效的', example: 'La norma vigente exige una licencia.', exampleChinese: '现行规定要求许可证。', lemma: 'vigente', partOfSpeech: 'adjective', frequencyRank: 4209 },
    ],
  },
  {
    id: 'expansion-b2-strategy-language-008', level: 'B2', scene: '工作', title: '策略、协定与理解过程',
    description: '说明目标、动力、约定和复杂沟通关系',
    frameworkReference: B1_B2_PCIC,
    words: [
      { spanish: 'finalidad', chinese: '目的；宗旨', example: 'La medida tiene una finalidad preventiva.', exampleChinese: '这项措施具有预防目的。', lemma: 'finalidad', partOfSpeech: 'noun', frequencyRank: 4249 },
      { spanish: 'inspiración', chinese: '灵感；启发', example: 'El proyecto toma inspiración de la naturaleza.', exampleChinese: '项目从自然中获得灵感。', lemma: 'inspiración', partOfSpeech: 'noun', frequencyRank: 4258 },
      { spanish: 'dinámica', chinese: '动态；运作方式', example: 'La nueva dinámica mejora la colaboración.', exampleChinese: '新的运作方式改善协作。', lemma: 'dinámica', partOfSpeech: 'noun', frequencyRank: 4323 },
      { spanish: 'disciplina', chinese: '纪律；学科；自律', example: 'El aprendizaje diario exige disciplina.', exampleChinese: '每日学习需要自律。', lemma: 'disciplina', partOfSpeech: 'noun', frequencyRank: 4324 },
      { spanish: 'esencia', chinese: '本质；精髓', example: 'La esencia del acuerdo es la cooperación.', exampleChinese: '协议的核心是合作。', lemma: 'esencia', partOfSpeech: 'noun', frequencyRank: 4333 },
      { spanish: 'convención', chinese: '惯例；公约；大会', example: 'La convención establece reglas comunes.', exampleChinese: '公约确立共同规则。', lemma: 'convención', partOfSpeech: 'noun', frequencyRank: 4406 },
      { spanish: 'facilidad', chinese: '容易；便利；能力', example: 'Tiene facilidad para explicar ideas complejas.', exampleChinese: '他很擅长解释复杂观点。', lemma: 'facilidad', partOfSpeech: 'noun', frequencyRank: 4336 },
      { spanish: 'impulso', chinese: '推动；冲动；动力', example: 'La inversión dio impulso al proyecto.', exampleChinese: '投资推动了项目。', lemma: 'impulso', partOfSpeech: 'noun', frequencyRank: 4344 },
      { spanish: 'instancia', chinese: '机构；阶段；申请', example: 'La decisión pasa a otra instancia.', exampleChinese: '该决定进入另一个审理阶段。', lemma: 'instancia', partOfSpeech: 'noun', frequencyRank: 4346 },
      { spanish: 'percepción', chinese: '感知；看法', example: 'La encuesta mide la percepción pública.', exampleChinese: '调查衡量公众看法。', lemma: 'percepción', partOfSpeech: 'noun', frequencyRank: 4366 },
      { spanish: 'soporte', chinese: '支持；支架；载体', example: 'El equipo ofrece soporte técnico.', exampleChinese: '团队提供技术支持。', lemma: 'soporte', partOfSpeech: 'noun', frequencyRank: 4382 },
      { spanish: 'comprensión', chinese: '理解；领会', example: 'La lectura mejora la comprensión del tema.', exampleChinese: '阅读能加深对主题的理解。', lemma: 'comprensión', partOfSpeech: 'noun', frequencyRank: 4405 },
    ],
  },
]
