import type { ExpansionDeck } from './lexiconExpansion'

const A1_A2_PCIC = 'https://cvc.cervantes.es/ensenanza/biblioteca_ele/plan_curricular/niveles/09_nociones_especificas_inventario_a1-a2.htm'
const B1_B2_PCIC = 'https://cvc.cervantes.es/ensenanza/biblioteca_ele/plan_curricular/niveles/09_nociones_especificas_inventario_b1-b2.htm'
type ExpansionWord = ExpansionDeck['words'][number]
const w = (spanish: string, chinese: string, example: string, exampleChinese: string, partOfSpeech: ExpansionWord['partOfSpeech'], frequencyRank: number): ExpansionWord => ({ spanish, chinese, example, exampleChinese, lemma: spanish, partOfSpeech, frequencyRank })

// Production batch 011: 96 canonical targets filling broad high-frequency gaps.
export const expansionBatch011: ExpansionDeck[] = [
  {
    id: 'expansion-a2-general-description-011', level: 'A2', scene: '日常', title: '常用描述与基本关系',
    description: '补齐高频描述词以及位置、范围和整体关系', frameworkReference: A1_A2_PCIC,
    words: [
      w('verdad', '事实；真相', 'Quiero saber la verdad.', '我想知道真相。', 'noun', 171),
      w('final', '结尾；最终的', 'El final de la película fue triste.', '电影结尾很悲伤。', 'noun', 247),
      w('social', '社会的；社交的', 'Es un problema social.', '这是一个社会问题。', 'adjective', 276),
      w('igual', '相同的；平等的', 'El precio es igual en las dos tiendas.', '两家商店的价格相同。', 'adjective', 280),
      w('frente', '前面；正面；阵线', 'La farmacia está frente al banco.', '药店在银行对面。', 'noun', 319),
      w('único', '唯一的；独特的', 'Es el único documento que falta.', '这是唯一缺少的文件。', 'adjective', 368),
      w('siguiente', '下一个的；接下来的', 'Lea la página siguiente.', '请阅读下一页。', 'adjective', 389),
      w('personal', '个人的；员工', 'Es una decisión personal.', '这是个人决定。', 'adjective', 422),
      w('total', '总数；全部的', 'El total aparece en la factura.', '总额显示在账单上。', 'noun', 423),
      w('especial', '特别的；特殊的', 'Necesito una dieta especial.', '我需要特殊饮食。', 'adjective', 432),
      w('mundial', '世界的；全球性的', 'Es un problema mundial.', '这是一个全球性问题。', 'adjective', 446),
      w('vista', '视力；景色；视图', 'La habitación tiene buena vista.', '房间景色很好。', 'noun', 544),
    ],
  },
  {
    id: 'expansion-a2-daily-information-011', level: 'A2', scene: '学习', title: '日常信息与学习材料',
    description: '理解常见文本、度量、生活习惯和说明材料', frameworkReference: A1_A2_PCIC,
    words: [
      w('diario', '日记；日报；每日的', 'Escribo un diario en español.', '我用西语写日记。', 'noun', 846),
      w('posición', '位置；立场；姿势', 'Cambia la posición de la silla.', '改变椅子的位置。', 'noun', 858),
      w('suficiente', '足够的', 'Tenemos tiempo suficiente.', '我们有足够的时间。', 'adjective', 859),
      w('normal', '正常的；普通的', 'La temperatura es normal.', '体温正常。', 'adjective', 917),
      w('presencia', '在场；存在', 'Su presencia es necesaria.', '他需要到场。', 'noun', 946),
      w('versión', '版本；说法', 'Instala la nueva versión.', '安装新版本。', 'noun', 956),
      w('unidad', '单位；单元；统一', 'El curso tiene diez unidades y esta unidad es la primera.', '课程有十个单元，这是第一单元。', 'noun', 978),
      w('frase', '句子；短语', 'Escribe una frase corta.', '写一个短句。', 'noun', 1815),
      w('masa', '质量；面团；大众', 'La masa del pan debe reposar.', '面团需要静置。', 'noun', 2036),
      w('costumbre', '习惯；习俗', 'Tengo la costumbre de caminar por la tarde.', '我习惯下午散步。', 'noun', 2975),
      w('vidrio', '玻璃', 'El vaso es de vidrio.', '杯子是玻璃制的。', 'noun', 4669),
      w('manual', '手册；手动的', 'Consulta el manual del aparato.', '请查阅设备手册。', 'noun', 3717),
    ],
  },
  {
    id: 'expansion-b1-organisations-results-011', level: 'B1', scene: '工作', title: '组织、成果与业务判断',
    description: '讨论组织活动、选择结果和业务数据', frameworkReference: B1_B2_PCIC,
    words: [
      w('asociación', '协会；联系', 'La asociación organiza cursos gratuitos.', '协会组织免费课程。', 'noun', 1079),
      w('edición', '版本；编辑；届次', 'La nueva edición incluye más ejemplos.', '新版包含更多例子。', 'noun', 1087),
      w('creación', '创造；成立；作品', 'La creación de empleo es una prioridad.', '创造就业是优先事项。', 'noun', 1108),
      w('legal', '合法的；法律的', 'El contrato es legal.', '这份合同是合法的。', 'adjective', 1113),
      w('doble', '双倍的；双人的', 'La habitación doble cuesta más.', '双人房价格更高。', 'adjective', 1139),
      w('selección', '选择；选集；代表队', 'La selección depende de la experiencia.', '选择取决于经验。', 'noun', 1183),
      w('excelente', '优秀的；极好的', 'El servicio fue excelente.', '服务非常好。', 'adjective', 1195),
      w('pérdida', '损失；丢失', 'La pérdida de datos causó retrasos.', '数据丢失造成了延误。', 'noun', 1652),
      w('beneficio', '好处；利润', 'El cambio aporta un beneficio claro.', '这一改变带来明显好处。', 'noun', 2068),
      w('cifra', '数字；数额', 'La cifra supera el año anterior.', '这个数字超过去年。', 'noun', 3233),
      w('seguimiento', '跟踪；后续检查', 'El paciente necesita seguimiento médico.', '患者需要医疗随访。', 'noun', 3737),
      w('consumidor', '消费者', 'La ley protege al consumidor.', '法律保护消费者。', 'noun', 5083),
    ],
  },
  {
    id: 'expansion-b1-culture-profession-011', level: 'B1', scene: '社会', title: '文化、职业与公共身份',
    description: '描述文化产品、职业身份和公共人物', frameworkReference: B1_B2_PCIC,
    words: [
      w('cultural', '文化的', 'El centro ofrece un programa cultural.', '该中心提供文化项目。', 'adjective', 983),
      w('interesante', '有趣的；值得关注的', 'El informe plantea una pregunta interesante.', '报告提出了一个有趣的问题。', 'adjective', 992),
      w('original', '原创的；原件', 'Necesito el documento original.', '我需要文件原件。', 'adjective', 997),
      w('nación', '国家；民族', 'La nación aprobó una nueva constitución.', '这个国家通过了新宪法。', 'noun', 1038),
      w('profesional', '专业的；专业人士', 'Busque ayuda profesional.', '请寻求专业帮助。', 'adjective', 1044),
      w('misión', '任务；使命', 'La misión del equipo es mejorar el servicio.', '团队的任务是改善服务。', 'noun', 1323),
      w('independiente', '独立的；自主的', 'Trabaja como profesional independiente.', '他是一名自由职业者。', 'adjective', 1348),
      w('festival', '节日活动；艺术节', 'El festival empieza el viernes.', '艺术节周五开始。', 'noun', 1377),
      w('responsable', '负责的；负责人', 'Ella es responsable del proyecto.', '她负责这个项目。', 'adjective', 1394),
      w('personaje', '人物；角色', 'El personaje principal vive en Madrid.', '主角住在马德里。', 'noun', 1418),
      w('visión', '视野；观点；愿景', 'El plan presenta una visión a largo plazo.', '计划提出长期愿景。', 'noun', 1432),
      w('comentario', '评论；意见', 'Deje un comentario al final.', '请在最后留下评论。', 'noun', 1439),
    ],
  },
  {
    id: 'expansion-b1-history-community-011', level: 'B1', scene: '社会', title: '历史、群体与公共说明',
    description: '描述代际变化、地方机构和公开说明', frameworkReference: B1_B2_PCIC,
    words: [
      w('generación', '一代人；生成', 'La nueva generación usa otras herramientas.', '新一代使用不同工具。', 'noun', 1450),
      w('figura', '人物；图形；身材', 'La figura muestra los resultados.', '图形显示了结果。', 'noun', 1481),
      w('genial', '极好的；天才的', 'La idea parece genial.', '这个想法很棒。', 'adjective', 1482),
      w('municipal', '市政的；市级的', 'La oficina municipal abre a las nueve.', '市政办公室九点开门。', 'adjective', 1486),
      w('fundación', '基金会；建立', 'La fundación apoya a familias vulnerables.', '基金会帮助弱势家庭。', 'noun', 1509),
      w('histórico', '历史的；历史性的', 'El acuerdo es un paso histórico.', '这项协议是历史性的一步。', 'adjective', 1511),
      w('secretario', '秘书；书记；部长', 'El secretario confirmó la reunión.', '秘书确认了会议。', 'noun', 1531),
      w('continuación', '继续；后续部分', 'A continuación aparece el resumen.', '接下来是摘要。', 'noun', 1542),
      w('existencia', '存在；生存', 'No hay prueba de su existencia.', '没有证据证明它的存在。', 'noun', 1573),
      w('belleza', '美；美丽', 'La región destaca por su belleza natural.', '该地区以自然美景著称。', 'noun', 1597),
      w('declaración', '声明；申报；陈述', 'La declaración contiene nuevos datos.', '声明包含新数据。', 'noun', 1601),
      w('regional', '地区的；区域性的', 'El tren regional sale pronto.', '区域列车很快出发。', 'adjective', 1788),
    ],
  },
  {
    id: 'expansion-b2-law-science-011', level: 'B2', scene: '社会', title: '法律、科学与社会状态',
    description: '分析法律制度、科学领域和社会变化', frameworkReference: B1_B2_PCIC,
    words: [
      w('judicial', '司法的；法院的', 'El proceso judicial duró varios meses.', '司法程序持续了数月。', 'adjective', 1550),
      w('sexual', '性的；性别相关的', 'La educación sexual debe ser responsable.', '性教育应当负责任。', 'adjective', 1589),
      w('estatal', '国家的；国有的', 'La empresa recibe apoyo estatal.', '公司获得国家支持。', 'adjective', 1604),
      w('artista', '艺术家；艺人', 'La artista presentó su nueva obra.', '这位艺术家展示了新作品。', 'noun', 1625),
      w('global', '全球的；整体的', 'Necesitamos una respuesta global.', '我们需要全球性回应。', 'adjective', 1816),
      w('física', '物理学；身体的', 'La física explica el movimiento.', '物理学解释运动。', 'noun', 1678),
      w('ejecutivo', '行政的；高管；执行者', 'El comité ejecutivo aprobó el presupuesto.', '执行委员会批准了预算。', 'adjective', 1724),
      w('penal', '刑事的；处罚的', 'El caso pasó a la vía penal.', '案件进入刑事程序。', 'adjective', 1740),
      w('prisión', '监狱；监禁', 'El tribunal dictó una pena de prisión.', '法院判处监禁。', 'noun', 1746),
      w('actualidad', '当前；当今；新闻', 'El tema sigue siendo de actualidad.', '这个话题仍具有现实性。', 'noun', 1753),
      w('tradicional', '传统的', 'El mercado conserva su diseño tradicional.', '市场保留了传统设计。', 'adjective', 1797),
      w('condición', '条件；状况', 'La oferta incluye una condición especial.', '这项优惠包含一个特殊条件。', 'noun', 1806),
    ],
  },
  {
    id: 'expansion-b2-institutions-dialogue-011', level: 'B2', scene: '行政', title: '机构、对话与正式程序',
    description: '理解机构职责、公开对话和正式程序文件', frameworkReference: B1_B2_PCIC,
    words: [
      w('inteligente', '聪明的；智能的', 'El sistema inteligente detecta errores.', '智能系统能发现错误。', 'adjective', 1819),
      w('presidencia', '总统职位；主席团', 'La presidencia publicó el calendario.', '主席团公布了日程。', 'noun', 1826),
      w('división', '划分；部门；除法', 'La división de tareas mejoró el trabajo.', '任务划分改善了工作。', 'noun', 1847),
      w('humanidad', '人类；人性', 'El cambio afecta a toda la humanidad.', '这一变化影响全人类。', 'noun', 1856),
      w('institución', '机构；制度', 'La institución ofrece asesoría gratuita.', '该机构提供免费咨询。', 'noun', 1858),
      w('moral', '道德；士气；道德的', 'La decisión plantea un problema moral.', '这一决定提出了道德问题。', 'noun', 1866),
      w('técnico', '技术的；技术人员', 'El informe técnico explica la avería.', '技术报告解释了故障。', 'adjective', 1884),
      w('conversación', '交谈；对话', 'La conversación duró una hora.', '谈话持续了一个小时。', 'noun', 1932),
      w('escenario', '场景；舞台；局面', 'El informe analiza el peor escenario.', '报告分析了最坏情况。', 'noun', 1934),
      w('exposición', '展览；陈述；暴露', 'La exposición presenta arte contemporáneo.', '展览展示当代艺术。', 'noun', 1936),
      w('sentencia', '判决；句子', 'El juez publicó la sentencia.', '法官公布了判决。', 'noun', 1958),
      w('sesión', '会议；场次；疗程', 'La sesión comienza a las cuatro.', '会议四点开始。', 'noun', 1959),
    ],
  },
  {
    id: 'expansion-b2-public-systems-011', level: 'B2', scene: '工作', title: '公共系统与集体行动',
    description: '讨论公共机构、产业活动和制度性行动', frameworkReference: B1_B2_PCIC,
    words: [
      w('intervención', '干预；发言；手术', 'La intervención pública redujo el riesgo.', '公共干预降低了风险。', 'noun', 1988),
      w('agencia', '机构；代理公司', 'La agencia publicó nuevas recomendaciones.', '该机构发布了新建议。', 'noun', 2005),
      w('constante', '持续的；常数', 'El cambio requiere un esfuerzo constante.', '改变需要持续努力。', 'adjective', 2015),
      w('industrial', '工业的；产业的', 'La zona industrial queda fuera de la ciudad.', '工业区位于城外。', 'adjective', 2031),
      w('anual', '每年的；年度的', 'El informe anual ya está disponible.', '年度报告已经发布。', 'adjective', 2065),
      w('dictadura', '独裁统治；独裁政权', 'El país sufrió una larga dictadura.', '这个国家经历了长期独裁统治。', 'noun', 2077),
      w('universal', '普遍的；通用的', 'El acceso a la salud debe ser universal.', '医疗服务应当普惠。', 'adjective', 2140),
      w('occidental', '西方的；西部的', 'La región occidental recibe más lluvia.', '西部地区降雨更多。', 'adjective', 2179),
      w('constitucional', '宪法的；合宪的', 'El tribunal revisa si la medida es constitucional.', '法院审查该措施是否符合宪法。', 'adjective', 2201),
      w('parlamento', '议会', 'El parlamento debatirá la reforma.', '议会将讨论改革。', 'noun', 2218),
      w('colectivo', '群体；集体的', 'El colectivo reclama mejores condiciones.', '这个群体要求改善条件。', 'noun', 2241),
      w('poesía', '诗歌；诗意', 'La poesía utiliza un lenguaje preciso.', '诗歌使用精确语言。', 'noun', 2262),
    ],
  },
]
