import type { ExpansionDeck } from './lexiconExpansion'

const A1_A2_PCIC = 'https://cvc.cervantes.es/ensenanza/biblioteca_ele/plan_curricular/niveles/09_nociones_especificas_inventario_a1-a2.htm'
const B1_B2_PCIC = 'https://cvc.cervantes.es/ensenanza/biblioteca_ele/plan_curricular/niveles/09_nociones_especificas_inventario_b1-b2.htm'
type ExpansionWord = ExpansionDeck['words'][number]
const w = (spanish: string, chinese: string, example: string, exampleChinese: string, partOfSpeech: ExpansionWord['partOfSpeech'], frequencyRank: number): ExpansionWord => ({ spanish, chinese, example, exampleChinese, lemma: spanish, partOfSpeech, frequencyRank })

// Production batch 012: 96 canonical education, culture, work and public-life targets.
export const expansionBatch012: ExpansionDeck[] = [
  {
    id: 'expansion-a2-culture-media-012', level: 'A2', scene: '学习', title: '文化、媒体与学习描述',
    description: '理解文化作品、学习状态和常见评价', frameworkReference: A1_A2_PCIC,
    words: [
      w('increíble', '难以置信的；极好的', 'La vista desde aquí es increíble.', '从这里看到的景色令人惊叹。', 'adjective', 1293),
      w('mental', '心理的；精神的', 'El descanso es importante para la salud mental.', '休息对心理健康很重要。', 'adjective', 2402),
      w('musical', '音乐的；音乐剧', 'El teatro presenta un espectáculo musical.', '剧院上演音乐节目。', 'adjective', 2404),
      w('pintura', '绘画；油漆', 'La pintura de la pared está seca.', '墙上的油漆干了。', 'noun', 2413),
      w('pista', '线索；跑道；轨道', 'La policía encontró una pista importante.', '警方发现了一条重要线索。', 'noun', 2414),
      w('positivo', '积极的；阳性的', 'El cambio tuvo un efecto positivo.', '这一变化产生了积极影响。', 'adjective', 2416),
      w('reciente', '最近的；新近的', 'Es una noticia reciente.', '这是一条近期新闻。', 'adjective', 2419),
      w('activo', '活跃的；有效的；资产', 'El usuario sigue activo.', '该用户仍然活跃。', 'adjective', 2435),
      w('agente', '代理人；工作人员；因素', 'El agente revisó el pasaporte.', '工作人员检查了护照。', 'noun', 2436),
      w('ausencia', '缺席；不存在', 'Su ausencia retrasó la reunión.', '他的缺席使会议推迟。', 'noun', 2438),
      w('inicial', '最初的；首字母', 'La reunión inicial duró una hora.', '第一次会议持续了一个小时。', 'adjective', 2452),
      w('rural', '乡村的；农村的', 'Vive en una zona rural.', '他住在农村地区。', 'adjective', 2473),
    ],
  },
  {
    id: 'expansion-a2-events-people-012', level: 'A2', scene: '日常', title: '活动、人物与公共信息',
    description: '谈论纪念活动、人物作品和公共信息', frameworkReference: A1_A2_PCIC,
    words: [
      w('electrónico', '电子的', 'Necesito el billete electrónico.', '我需要电子票。', 'adjective', 2495),
      w('clásico', '经典的；古典的', 'Es un ejemplo clásico.', '这是一个经典例子。', 'adjective', 2547),
      w('aniversario', '周年纪念日', 'Celebramos nuestro aniversario en mayo.', '我们五月庆祝周年纪念日。', 'noun', 2589),
      w('comparación', '比较；对比', 'La comparación muestra una diferencia clara.', '比较显示出明显差异。', 'noun', 2594),
      w('homenaje', '致敬；纪念活动', 'La ciudad organizó un homenaje al escritor.', '城市为这位作家举办了纪念活动。', 'noun', 2612),
      w('individual', '个人的；单独的', 'Cada alumno recibe atención individual.', '每位学生都获得个别关注。', 'adjective', 2721),
      w('celebración', '庆祝；庆典', 'La celebración empieza al mediodía.', '庆典中午开始。', 'noun', 2760),
      w('científico', '科学家；科学的', 'El científico presentó los resultados.', '科学家介绍了研究结果。', 'noun', 2764),
      w('cantante', '歌手', 'La cantante actuará esta noche.', '这位歌手今晚演出。', 'noun', 2813),
      w('documental', '纪录片；文献的', 'Vimos un documental sobre el océano.', '我们看了一部关于海洋的纪录片。', 'noun', 2928),
      w('continente', '大陆；洲', 'Europa es un continente pequeño.', '欧洲是一个较小的洲。', 'noun', 2974),
      w('agradable', '令人愉快的；舒适的', 'La temperatura es agradable.', '温度很舒适。', 'adjective', 3098),
    ],
  },
  {
    id: 'expansion-b1-organisations-media-012', level: 'B1', scene: '社会', title: '组织、媒体与公共结果',
    description: '理解机构行动、信息传播和公共判断', frameworkReference: B1_B2_PCIC,
    words: [
      w('federación', '联合会；联邦', 'La federación publicó el calendario.', '联合会公布了日程。', 'noun', 2562),
      w('ejecución', '执行；实施；处决', 'La ejecución del plan requiere recursos.', '计划实施需要资源。', 'noun', 2604),
      w('lanzamiento', '发布；发射；推出', 'El lanzamiento del producto será mañana.', '产品将于明天发布。', 'noun', 2672),
      w('criminal', '犯罪的；罪犯', 'La investigación criminal continúa.', '刑事调查仍在继续。', 'adjective', 2767),
      w('crítico', '关键的；批评的；评论家', 'El sistema está en un momento crítico.', '系统正处于关键时刻。', 'adjective', 2820),
      w('secretaría', '秘书处；办事处', 'Entregue el formulario en secretaría.', '请把表格交到秘书处。', 'noun', 2844),
      w('transmisión', '传播；传输；直播', 'La transmisión empieza a las ocho.', '直播八点开始。', 'noun', 2849),
      w('organismo', '机构；生物体', 'El organismo regulador publicó el informe.', '监管机构发布了报告。', 'noun', 2894),
      w('culpable', '有罪的；责任人', 'El tribunal declaró culpable al acusado.', '法院判定被告有罪。', 'adjective', 2923),
      w('temporal', '临时的；暂时的', 'El cierre es temporal.', '关闭是暂时的。', 'adjective', 2956),
      w('impresionante', '令人印象深刻的', 'El resultado es impresionante.', '结果令人印象深刻。', 'adjective', 2986),
      w('liberación', '释放；解放', 'La liberación del prisionero fue confirmada.', '囚犯获释得到确认。', 'noun', 2992),
    ],
  },
  {
    id: 'expansion-b1-local-education-012', level: 'B1', scene: '学习', title: '地方教育与信息准备',
    description: '描述地方事务、教育内容和信息准备流程', frameworkReference: B1_B2_PCIC,
    words: [
      w('localidad', '城镇；地点', 'La localidad tiene un centro de salud.', '这个城镇有一个医疗中心。', 'noun', 2993),
      w('gigante', '巨大的；巨人', 'La empresa se convirtió en un gigante tecnológico.', '这家公司成为科技巨头。', 'noun', 3052),
      w('votación', '投票；表决', 'La votación termina esta tarde.', '投票今天下午结束。', 'noun', 3092),
      w('brillante', '明亮的；出色的', 'Presentó una solución brillante.', '他提出了一个出色的解决方案。', 'adjective', 3103),
      w('periodismo', '新闻业；新闻学', 'Estudia periodismo en la universidad.', '她在大学学习新闻学。', 'noun', 3135),
      w('portal', '门户网站；入口', 'La solicitud se presenta en el portal oficial.', '申请通过官方网站提交。', 'noun', 3136),
      w('preparación', '准备；制备', 'La preparación del examen lleva tiempo.', '备考需要时间。', 'noun', 3139),
      w('destrucción', '破坏；毁灭', 'El incendio causó la destrucción del edificio.', '火灾造成建筑物毁坏。', 'noun', 3175),
      w('vigilancia', '监控；警戒', 'La zona tiene vigilancia las veinticuatro horas.', '该区域全天有人监控。', 'noun', 3220),
      w('aventura', '冒险；奇遇', 'El viaje fue una aventura inolvidable.', '这次旅行是一次难忘的冒险。', 'noun', 3304),
      w('habitual', '通常的；惯常的', 'Tome su ruta habitual.', '走您平常的路线。', 'adjective', 3328),
      w('instrumento', '工具；仪器；乐器', 'El médico utiliza un instrumento pequeño.', '医生使用一个小型器械。', 'noun', 3422),
    ],
  },
  {
    id: 'expansion-b1-training-environment-012', level: 'B1', scene: '工作', title: '培训、环境与任务状态',
    description: '讨论教育环境、工作设施和任务进度', frameworkReference: B1_B2_PCIC,
    words: [
      w('universitario', '大学的；大学生', 'El campus universitario está cerca.', '大学校园就在附近。', 'adjective', 3453),
      w('ambiental', '环境的；环保的', 'La empresa publica un informe ambiental.', '公司发布环境报告。', 'adjective', 3457),
      w('establecimiento', '场所；机构；建立', 'El establecimiento cierra a las diez.', '这家场所十点关门。', 'noun', 3481),
      w('pendiente', '待处理的；悬挂的；斜坡', 'La tarea sigue pendiente.', '任务仍待处理。', 'adjective', 3505),
      w('educativo', '教育的', 'El centro ofrece material educativo.', '该中心提供教育材料。', 'adjective', 3550),
      w('equivalente', '相等的；等价物', 'Este título es equivalente al anterior.', '这个学位与之前的等同。', 'adjective', 3553),
      w('ficción', '虚构；小说类作品', 'La novela mezcla historia y ficción.', '这部小说把历史与虚构结合起来。', 'noun', 3557),
      w('funcionario', '公务员；官员', 'El funcionario revisó la documentación.', '公务员检查了文件。', 'noun', 3559),
      w('típico', '典型的；当地特色的', 'Es un plato típico de la región.', '这是该地区的特色菜。', 'adjective', 3596),
      w('valiente', '勇敢的', 'Fue una decisión valiente.', '这是一个勇敢的决定。', 'adjective', 3599),
      w('composición', '构成；作文；作品', 'La etiqueta indica la composición del producto.', '标签标明产品成分。', 'noun', 3684),
      w('multa', '罚款；罚单', 'Recibió una multa por exceso de velocidad.', '他因超速收到罚单。', 'noun', 4355),
    ],
  },
  {
    id: 'expansion-b2-systems-settings-012', level: 'B2', scene: '社会', title: '制度环境与组织设置',
    description: '分析增长、精神生活、制度设置和企业活动', frameworkReference: B1_B2_PCIC,
    words: [
      w('creciente', '不断增长的；上升的', 'Existe una demanda creciente de vivienda.', '住房需求不断增长。', 'adjective', 3691),
      w('espiritual', '精神的；宗教的', 'El viaje tuvo un significado espiritual.', '这次旅行具有精神意义。', 'adjective', 3702),
      w('instalación', '安装；设施', 'La instalación eléctrica necesita revisión.', '电气设施需要检查。', 'noun', 3714),
      w('oración', '句子；祈祷', 'La oración contiene dos verbos.', '这个句子包含两个动词。', 'noun', 3726),
      w('parcial', '部分的；兼职的；偏颇的', 'El informe ofrece una visión parcial.', '报告只提供了片面的视角。', 'adjective', 3728),
      w('tranquilidad', '平静；安心', 'La garantía ofrece tranquilidad al cliente.', '保修让客户更安心。', 'noun', 4660),
      w('empresario', '企业家；商人', 'El empresario anunció una nueva inversión.', '企业家宣布了一项新投资。', 'noun', 3778),
      w('galería', '画廊；长廊；图片库', 'La galería presenta artistas jóvenes.', '画廊展示年轻艺术家的作品。', 'noun', 3784),
      w('protagonista', '主角；核心人物', 'La científica fue protagonista del debate.', '这位科学家是讨论的核心人物。', 'noun', 3804),
      w('combinación', '组合；结合；密码', 'La combinación de métodos dio buen resultado.', '多种方法的结合取得了好结果。', 'noun', 3830),
      w('específico', '具体的；特定的', 'Necesitamos un objetivo específico.', '我们需要一个具体目标。', 'adjective', 3843),
      w('formal', '正式的；形式上的', 'Presentó una queja formal.', '他提出了正式投诉。', 'adjective', 3845),
    ],
  },
  {
    id: 'expansion-b2-regulation-safety-012', level: 'B2', scene: '行政', title: '监管、安全与公共事件',
    description: '理解规章、风险事件和公共安全措施', frameworkReference: B1_B2_PCIC,
    words: [
      w('reglamento', '规章；条例', 'El reglamento prohíbe fumar aquí.', '条例禁止在这里吸烟。', 'noun', 3875),
      w('separación', '分开；分离；间隔', 'La separación de residuos es obligatoria.', '垃圾分类是强制性的。', 'noun', 3881),
      w('casualidad', '巧合；偶然', 'Nos encontramos por casualidad.', '我们偶然相遇。', 'noun', 3903),
      w('explosión', '爆炸；激增', 'La explosión dañó varias ventanas.', '爆炸损坏了多扇窗户。', 'noun', 3920),
      w('inocente', '无辜的；天真的', 'El tribunal declaró inocente al acusado.', '法院判定被告无罪。', 'adjective', 3931),
      w('reproducción', '复制；繁殖；播放', 'La reproducción del vídeo se detuvo.', '视频播放停止了。', 'noun', 3957),
      w('circulación', '交通；流通；循环', 'La circulación está cortada.', '交通已中断。', 'noun', 3989),
      w('sensible', '敏感的；易受影响的', 'El documento contiene información sensible.', '文件包含敏感信息。', 'adjective', 4042),
      w('amable', '友善的；亲切的', 'El personal fue muy amable.', '工作人员非常友善。', 'adjective', 4052),
      w('docente', '教师；教学的', 'El equipo docente prepara el curso.', '教师团队准备课程。', 'noun', 4075),
      w('campamento', '营地；夏令营', 'El campamento está junto al lago.', '营地在湖边。', 'noun', 4141),
      w('cristal', '玻璃；水晶', 'La puerta de cristal está cerrada.', '玻璃门关着。', 'noun', 4147),
    ],
  },
  {
    id: 'expansion-b2-process-participation-012', level: 'B2', scene: '工作', title: '流程、参与与正式记录',
    description: '描述制作流程、记录特征和正式参与状态', frameworkReference: B1_B2_PCIC,
    words: [
      w('elaboración', '制作；拟定', 'La elaboración del informe tardó un mes.', '报告编写花了一个月。', 'noun', 4158),
      w('característica', '特征；特点', 'La rapidez es una característica del sistema.', '快速是这个系统的特点。', 'noun', 4223),
      w('censura', '审查；删减', 'La ley limita la censura previa.', '法律限制事先审查。', 'noun', 4225),
      w('emisión', '排放；播出；发行', 'La emisión de gases ha disminuido.', '气体排放已经下降。', 'noun', 4241),
      w('incidente', '事件；事故', 'El incidente no causó heridos.', '事件没有造成人员受伤。', 'noun', 4254),
      w('inscripción', '报名；注册；铭文', 'La inscripción termina el viernes.', '报名周五截止。', 'noun', 4257),
      w('invitación', '邀请；请柬', 'Recibí una invitación a la conferencia.', '我收到了会议邀请。', 'noun', 4259),
      w('mención', '提及；表彰', 'El informe hace mención del problema.', '报告提到了这个问题。', 'noun', 4263),
      w('notable', '显著的；杰出的', 'Hubo una mejora notable.', '出现了显著改善。', 'adjective', 4268),
      w('suspensión', '暂停；悬挂；停职', 'La lluvia causó la suspensión del partido.', '下雨导致比赛暂停。', 'noun', 4286),
      w('vital', '至关重要的；生命的', 'El agua es un recurso vital.', '水是至关重要的资源。', 'adjective', 4292),
      w('calendario', '日历；日程表', 'El calendario incluye todas las fechas.', '日程表包含所有日期。', 'noun', 4305),
    ],
  },
]
