import type { ExpansionDeck } from './lexiconExpansion'

const A1_A2_PCIC = 'https://cvc.cervantes.es/ensenanza/biblioteca_ele/plan_curricular/niveles/09_nociones_especificas_inventario_a1-a2.htm'
const B1_B2_PCIC = 'https://cvc.cervantes.es/ensenanza/biblioteca_ele/plan_curricular/niveles/09_nociones_especificas_inventario_b1-b2.htm'

// Production batch 007: 96 canonical, frequency-backed targets for transport,
// clothing, emotions, public services, industry and practical analysis.
export const expansionBatch007: ExpansionDeck[] = [
  {
    id: 'expansion-a1-transport-clothing-007', level: 'A1', scene: '城市', title: '交通工具与随身衣物',
    description: '辨认常见车辆、道路位置和基础穿戴物品',
    frameworkReference: A1_A2_PCIC,
    words: [
      { spanish: 'barco', chinese: '船', example: 'El barco sale del puerto.', exampleChinese: '船从港口出发。', lemma: 'barco', partOfSpeech: 'noun', frequencyRank: 2543 },
      { spanish: 'vehículo', chinese: '车辆；交通工具', example: 'El vehículo está delante del hotel.', exampleChinese: '车辆停在酒店前面。', lemma: 'vehículo', partOfSpeech: 'noun', frequencyRank: 2959 },
      { spanish: 'carro', chinese: '汽车；车', example: 'El carro necesita gasolina.', exampleChinese: '汽车需要加油。', lemma: 'carro', partOfSpeech: 'noun', frequencyRank: 3230 },
      { spanish: 'avenida', chinese: '大街；大道', example: 'La tienda está en esta avenida.', exampleChinese: '商店在这条大街上。', lemma: 'avenida', partOfSpeech: 'noun', frequencyRank: 3303 },
      { spanish: 'rueda', chinese: '车轮；轮子', example: 'La bicicleta tiene una rueda nueva.', exampleChinese: '自行车换了一个新轮子。', lemma: 'rueda', partOfSpeech: 'noun', frequencyRank: 3516 },
      { spanish: 'parada', chinese: '车站；停靠；停止', example: 'La próxima parada es el centro.', exampleChinese: '下一站是市中心。', lemma: 'parada', partOfSpeech: 'noun', frequencyRank: 3646 },
      { spanish: 'moto', chinese: '摩托车', example: 'La moto está junto a la puerta.', exampleChinese: '摩托车停在门旁。', lemma: 'moto', partOfSpeech: 'noun', frequencyRank: 3864 },
      { spanish: 'bicicleta', chinese: '自行车', example: 'Voy al trabajo en bicicleta.', exampleChinese: '我骑自行车上班。', lemma: 'bicicleta', partOfSpeech: 'noun', frequencyRank: 3899 },
      { spanish: 'camión', chinese: '卡车；货车', example: 'El camión entrega los muebles.', exampleChinese: '卡车运送家具。', lemma: 'camión', partOfSpeech: 'noun', frequencyRank: 4481 },
      { spanish: 'bolsillo', chinese: '口袋', example: 'Las llaves están en mi bolsillo.', exampleChinese: '钥匙在我的口袋里。', lemma: 'bolsillo', partOfSpeech: 'noun', frequencyRank: 3900 },
      { spanish: 'camiseta', chinese: 'T恤；汗衫', example: 'La camiseta blanca está limpia.', exampleChinese: '白色T恤是干净的。', lemma: 'camiseta', partOfSpeech: 'noun', frequencyRank: 3902 },
      { spanish: 'camisa', chinese: '衬衫', example: 'Necesito una camisa para la entrevista.', exampleChinese: '我面试需要一件衬衫。', lemma: 'camisa', partOfSpeech: 'noun', frequencyRank: 4975 },
    ],
  },
  {
    id: 'expansion-a1-food-senses-007', level: 'A1', scene: '日常', title: '饮食、颜色与感官',
    description: '描述食物、颜色、天气和基本感官体验',
    frameworkReference: A1_A2_PCIC,
    words: [
      { spanish: 'vino', chinese: '葡萄酒', example: 'Este vino es de la región.', exampleChinese: '这种葡萄酒产自本地区。', lemma: 'vino', partOfSpeech: 'noun', frequencyRank: 979 },
      { spanish: 'oído', chinese: '听觉；耳朵内部', example: 'Tengo dolor de oído.', exampleChinese: '我耳朵疼。', lemma: 'oído', partOfSpeech: 'noun', frequencyRank: 2737 },
      { spanish: 'lago', chinese: '湖', example: 'El lago está cerca de la montaña.', exampleChinese: '湖在山附近。', lemma: 'lago', partOfSpeech: 'noun', frequencyRank: 2784 },
      { spanish: 'flor', chinese: '花', example: 'Hay una flor en la mesa.', exampleChinese: '桌上有一朵花。', lemma: 'flor', partOfSpeech: 'noun', frequencyRank: 2831 },
      { spanish: 'sabor', chinese: '味道；风味', example: 'La sopa tiene buen sabor.', exampleChinese: '这汤味道很好。', lemma: 'sabor', partOfSpeech: 'noun', frequencyRank: 2953 },
      { spanish: 'tormenta', chinese: '暴风雨；风暴', example: 'La tormenta llega esta noche.', exampleChinese: '暴风雨今晚到来。', lemma: 'tormenta', partOfSpeech: 'noun', frequencyRank: 3028 },
      { spanish: 'chocolate', chinese: '巧克力', example: 'El chocolate está caliente.', exampleChinese: '巧克力饮品是热的。', lemma: 'chocolate', partOfSpeech: 'noun', frequencyRank: 3165 },
      { spanish: 'hielo', chinese: '冰', example: 'Quiero agua con hielo.', exampleChinese: '我想要加冰的水。', lemma: 'hielo', partOfSpeech: 'noun', frequencyRank: 3187 },
      { spanish: 'botella', chinese: '瓶子；一瓶', example: 'Necesito una botella de agua.', exampleChinese: '我需要一瓶水。', lemma: 'botella', partOfSpeech: 'noun', frequencyRank: 3675 },
      { spanish: 'amarillo', chinese: '黄色的；黄色', example: 'El autobús es amarillo.', exampleChinese: '公交车是黄色的。', lemma: 'amarillo', partOfSpeech: 'adjective', frequencyRank: 3755 },
      { spanish: 'gris', chinese: '灰色的；灰色', example: 'El cielo está gris.', exampleChinese: '天空是灰色的。', lemma: 'gris', partOfSpeech: 'adjective', frequencyRank: 3846 },
      { spanish: 'manzana', chinese: '苹果', example: 'Como una manzana por la mañana.', exampleChinese: '我早上吃一个苹果。', lemma: 'manzana', partOfSpeech: 'noun', frequencyRank: 5407 },
    ],
  },
  {
    id: 'expansion-a2-services-tools-007', level: 'A2', scene: '工作', title: '服务、工具与基本办事',
    description: '处理保险、登记、住房、设备和城市服务',
    frameworkReference: A1_A2_PCIC,
    words: [
      { spanish: 'seguro', chinese: '保险；安全的', example: 'El seguro cubre el accidente.', exampleChinese: '保险承保这次事故。', lemma: 'seguro', partOfSpeech: 'noun', frequencyRank: 335 },
      { spanish: 'modelo', chinese: '型号；模型；范例', example: 'Este modelo consume menos energía.', exampleChinese: '这个型号能耗更低。', lemma: 'modelo', partOfSpeech: 'noun', frequencyRank: 828 },
      { spanish: 'instituto', chinese: '中学；研究所', example: 'El instituto ofrece cursos de idiomas.', exampleChinese: '这所学校提供语言课程。', lemma: 'instituto', partOfSpeech: 'noun', frequencyRank: 971 },
      { spanish: 'marca', chinese: '品牌；标记', example: 'No conozco esta marca.', exampleChinese: '我不认识这个品牌。', lemma: 'marca', partOfSpeech: 'noun', frequencyRank: 1143 },
      { spanish: 'práctica', chinese: '练习；实践', example: 'La práctica diaria mejora la escritura.', exampleChinese: '每天练习能改善书写。', lemma: 'práctica', partOfSpeech: 'noun', frequencyRank: 1149 },
      { spanish: 'registro', chinese: '登记；记录', example: 'El registro se hace en línea.', exampleChinese: '登记在线完成。', lemma: 'registro', partOfSpeech: 'noun', frequencyRank: 1301 },
      { spanish: 'planta', chinese: '植物；楼层；工厂', example: 'La oficina está en la segunda planta.', exampleChinese: '办公室在二楼。', lemma: 'planta', partOfSpeech: 'noun', frequencyRank: 1358 },
      { spanish: 'digital', chinese: '数字的；数码的', example: 'Prefiero la versión digital.', exampleChinese: '我更喜欢数字版本。', lemma: 'digital', partOfSpeech: 'adjective', frequencyRank: 1506 },
      { spanish: 'municipio', chinese: '市镇；市政府辖区', example: 'El municipio organiza el transporte local.', exampleChinese: '市政府组织当地交通。', lemma: 'municipio', partOfSpeech: 'noun', frequencyRank: 1738 },
      { spanish: 'tasa', chinese: '比率；费用', example: 'La tasa incluye el servicio.', exampleChinese: '这项费用包含服务。', lemma: 'tasa', partOfSpeech: 'noun', frequencyRank: 2136 },
      { spanish: 'vivienda', chinese: '住房；住宅', example: 'Buscamos una vivienda cerca del trabajo.', exampleChinese: '我们在找靠近工作地点的住房。', lemma: 'vivienda', partOfSpeech: 'noun', frequencyRank: 2143 },
      { spanish: 'motor', chinese: '发动机；马达', example: 'El motor hace un ruido extraño.', exampleChinese: '发动机发出奇怪的声音。', lemma: 'motor', partOfSpeech: 'noun', frequencyRank: 2176 },
    ],
  },
  {
    id: 'expansion-a2-emotions-relationships-007', level: 'A2', scene: '情绪', title: '情绪与人际关系',
    description: '表达感受、态度以及人与人之间的联系',
    frameworkReference: A1_A2_PCIC,
    words: [
      { spanish: 'odio', chinese: '憎恨；厌恶', example: 'El odio no resuelve el conflicto.', exampleChinese: '仇恨不能解决冲突。', lemma: 'odio', partOfSpeech: 'noun', frequencyRank: 942 },
      { spanish: 'respeto', chinese: '尊重', example: 'Toda relación necesita respeto.', exampleChinese: '任何关系都需要尊重。', lemma: 'respeto', partOfSpeech: 'noun', frequencyRank: 949 },
      { spanish: 'carácter', chinese: '性格；特征', example: 'Tiene un carácter tranquilo.', exampleChinese: '他的性格很平和。', lemma: 'carácter', partOfSpeech: 'noun', frequencyRank: 1338 },
      { spanish: 'actitud', chinese: '态度', example: 'Su actitud cambió después de hablar.', exampleChinese: '谈话后他的态度变了。', lemma: 'actitud', partOfSpeech: 'noun', frequencyRank: 1562 },
      { spanish: 'humor', chinese: '心情；幽默', example: 'Hoy estoy de buen humor.', exampleChinese: '我今天心情很好。', lemma: 'humor', partOfSpeech: 'noun', frequencyRank: 1857 },
      { spanish: 'alegría', chinese: '喜悦；快乐', example: 'La noticia nos dio mucha alegría.', exampleChinese: '这条消息给我们带来很多喜悦。', lemma: 'alegría', partOfSpeech: 'noun', frequencyRank: 2146 },
      { spanish: 'amistad', chinese: '友谊', example: 'Nuestra amistad empezó en la universidad.', exampleChinese: '我们的友谊始于大学。', lemma: 'amistad', partOfSpeech: 'noun', frequencyRank: 2147 },
      { spanish: 'cariño', chinese: '关爱；喜爱', example: 'Recuerdo aquel lugar con cariño.', exampleChinese: '我怀着喜爱之情记得那个地方。', lemma: 'cariño', partOfSpeech: 'noun', frequencyRank: 2198 },
      { spanish: 'orgullo', chinese: '自豪；骄傲', example: 'Siento orgullo por el equipo.', exampleChinese: '我为团队感到自豪。', lemma: 'orgullo', partOfSpeech: 'noun', frequencyRank: 2406 },
      { spanish: 'risa', chinese: '笑；笑声', example: 'Su risa se escucha desde fuera.', exampleChinese: '从外面就能听到他的笑声。', lemma: 'risa', partOfSpeech: 'noun', frequencyRank: 2472 },
      { spanish: 'abrazo', chinese: '拥抱', example: 'Le doy un abrazo antes de salir.', exampleChinese: '出门前我给他一个拥抱。', lemma: 'abrazo', partOfSpeech: 'noun', frequencyRank: 2641 },
      { spanish: 'sonrisa', chinese: '微笑', example: 'La niña tiene una sonrisa enorme.', exampleChinese: '女孩露出灿烂的微笑。', lemma: 'sonrisa', partOfSpeech: 'noun', frequencyRank: 2687 },
    ],
  },
  {
    id: 'expansion-b1-public-industry-007', level: 'B1', scene: '社会', title: '公共机构、产业与交通',
    description: '理解公共服务、生产活动和城市运行信息',
    frameworkReference: B1_B2_PCIC,
    words: [
      { spanish: 'tribunal', chinese: '法院；法庭', example: 'El tribunal publicó la decisión.', exampleChinese: '法院公布了裁决。', lemma: 'tribunal', partOfSpeech: 'noun', frequencyRank: 1229 },
      { spanish: 'agricultura', chinese: '农业', example: 'La agricultura depende del clima.', exampleChinese: '农业依赖气候。', lemma: 'agricultura', partOfSpeech: 'noun', frequencyRank: 2372 },
      { spanish: 'petróleo', chinese: '石油', example: 'El precio del petróleo volvió a subir.', exampleChinese: '石油价格再次上涨。', lemma: 'petróleo', partOfSpeech: 'noun', frequencyRank: 2626 },
      { spanish: 'residencia', chinese: '住所；居留；宿舍', example: 'Solicitó un permiso de residencia.', exampleChinese: '他申请了居留许可。', lemma: 'residencia', partOfSpeech: 'noun', frequencyRank: 2685 },
      { spanish: 'vecino', chinese: '邻居；附近居民', example: 'Un vecino avisó del problema.', exampleChinese: '一位邻居报告了问题。', lemma: 'vecino', partOfSpeech: 'noun', frequencyRank: 2689 },
      { spanish: 'infancia', chinese: '童年；儿童时期', example: 'Pasó su infancia en un pueblo pequeño.', exampleChinese: '他在一个小镇度过童年。', lemma: 'infancia', partOfSpeech: 'noun', frequencyRank: 2723 },
      { spanish: 'tabla', chinese: '表格；木板', example: 'La tabla compara los resultados.', exampleChinese: '表格比较各项结果。', lemma: 'tabla', partOfSpeech: 'noun', frequencyRank: 2808 },
      { spanish: 'fábrica', chinese: '工厂', example: 'La fábrica emplea a cien personas.', exampleChinese: '工厂雇用了一百人。', lemma: 'fábrica', partOfSpeech: 'noun', frequencyRank: 2833 },
      { spanish: 'metal', chinese: '金属', example: 'La pieza está hecha de metal.', exampleChinese: '这个零件由金属制成。', lemma: 'metal', partOfSpeech: 'noun', frequencyRank: 3000 },
      { spanish: 'socio', chinese: '合伙人；会员', example: 'Cada socio tiene derecho a votar.', exampleChinese: '每位会员都有投票权。', lemma: 'socio', partOfSpeech: 'noun', frequencyRank: 3017 },
      { spanish: 'tránsito', chinese: '交通；通行', example: 'El tránsito es lento esta mañana.', exampleChinese: '今天早上交通缓慢。', lemma: 'tránsito', partOfSpeech: 'noun', frequencyRank: 3157 },
      { spanish: 'electricidad', chinese: '电；电力', example: 'La casa se quedó sin electricidad.', exampleChinese: '房子停电了。', lemma: 'electricidad', partOfSpeech: 'noun', frequencyRank: 3247 },
    ],
  },
  {
    id: 'expansion-b1-records-environment-007', level: 'B1', scene: '行政', title: '记录、职业与环境安全',
    description: '处理身份材料、职业信息和环境风险',
    frameworkReference: B1_B2_PCIC,
    words: [
      { spanish: 'humo', chinese: '烟；烟雾', example: 'El humo entró por la ventana.', exampleChinese: '烟从窗户进入。', lemma: 'humo', partOfSpeech: 'noun', frequencyRank: 3258 },
      { spanish: 'identificación', chinese: '身份证明；识别', example: 'Debe mostrar una identificación válida.', exampleChinese: '您必须出示有效身份证明。', lemma: 'identificación', partOfSpeech: 'noun', frequencyRank: 3329 },
      { spanish: 'combustible', chinese: '燃料', example: 'El vehículo consume poco combustible.', exampleChinese: '这辆车耗油很少。', lemma: 'combustible', partOfSpeech: 'noun', frequencyRank: 3388 },
      { spanish: 'habilidad', chinese: '技能；能力', example: 'La comunicación es una habilidad importante.', exampleChinese: '沟通是一项重要技能。', lemma: 'habilidad', partOfSpeech: 'noun', frequencyRank: 3416 },
      { spanish: 'incendio', chinese: '火灾', example: 'El incendio obligó a cerrar la carretera.', exampleChinese: '火灾迫使公路关闭。', lemma: 'incendio', partOfSpeech: 'noun', frequencyRank: 3421 },
      { spanish: 'conducta', chinese: '行为；举止', example: 'La norma regula la conducta profesional.', exampleChinese: '该规定约束职业行为。', lemma: 'conducta', partOfSpeech: 'noun', frequencyRank: 3470 },
      { spanish: 'profesión', chinese: '职业；专业', example: 'La medicina es una profesión exigente.', exampleChinese: '医学是一项要求很高的职业。', lemma: 'profesión', partOfSpeech: 'noun', frequencyRank: 3651 },
      { spanish: 'dato', chinese: '数据；事实', example: 'Este dato confirma la tendencia.', exampleChinese: '这项数据证实了趋势。', lemma: 'dato', partOfSpeech: 'noun', frequencyRank: 3770 },
      { spanish: 'gráfico', chinese: '图表；图形的', example: 'El gráfico muestra una caída.', exampleChinese: '图表显示下降。', lemma: 'gráfico', partOfSpeech: 'noun', frequencyRank: 3847 },
      { spanish: 'cultivo', chinese: '种植；农作物', example: 'El cultivo necesita mucha agua.', exampleChinese: '这种农作物需要大量水。', lemma: 'cultivo', partOfSpeech: 'noun', frequencyRank: 3832 },
      { spanish: 'embajada', chinese: '大使馆', example: 'La embajada tramita el documento.', exampleChinese: '大使馆办理这份文件。', lemma: 'embajada', partOfSpeech: 'noun', frequencyRank: 3841 },
      { spanish: 'domicilio', chinese: '住址；住所', example: 'Escriba su domicilio completo.', exampleChinese: '请填写完整住址。', lemma: 'domicilio', partOfSpeech: 'noun', frequencyRank: 3913 },
    ],
  },
  {
    id: 'expansion-b2-decisions-measures-007', level: 'B2', scene: '工作', title: '决策、衡量与项目结果',
    description: '评价方案、范围、资源和执行结果',
    frameworkReference: B1_B2_PCIC,
    words: [
      { spanish: 'impresión', chinese: '印象；打印；印刷', example: 'La primera impresión fue positiva.', exampleChinese: '第一印象是积极的。', lemma: 'impresión', partOfSpeech: 'noun', frequencyRank: 2567 },
      { spanish: 'extensión', chinese: '范围；延伸；分机', example: 'No conocemos la extensión del daño.', exampleChinese: '我们不知道损害的范围。', lemma: 'extensión', partOfSpeech: 'noun', frequencyRank: 2609 },
      { spanish: 'entidad', chinese: '机构；实体', example: 'La entidad gestiona los fondos públicos.', exampleChinese: '该机构管理公共资金。', lemma: 'entidad', partOfSpeech: 'noun', frequencyRank: 2655 },
      { spanish: 'aprobación', chinese: '批准；认可', example: 'El proyecto espera la aprobación final.', exampleChinese: '项目正在等待最终批准。', lemma: 'aprobación', partOfSpeech: 'noun', frequencyRank: 2758 },
      { spanish: 'evidente', chinese: '明显的；显然的', example: 'La diferencia es evidente.', exampleChinese: '差异很明显。', lemma: 'evidente', partOfSpeech: 'adjective', frequencyRank: 2773 },
      { spanish: 'excepción', chinese: '例外', example: 'La norma permite una excepción.', exampleChinese: '该规定允许一个例外。', lemma: 'excepción', partOfSpeech: 'noun', frequencyRank: 2774 },
      { spanish: 'formato', chinese: '格式；形式', example: 'Envíe el archivo en formato digital.', exampleChinese: '请以数字格式发送文件。', lemma: 'formato', partOfSpeech: 'noun', frequencyRank: 2777 },
      { spanish: 'potencia', chinese: '功率；力量；强国', example: 'El motor tiene suficiente potencia.', exampleChinese: '发动机功率足够。', lemma: 'potencia', partOfSpeech: 'noun', frequencyRank: 2797 },
      { spanish: 'riqueza', chinese: '财富；丰富性', example: 'La región protege su riqueza natural.', exampleChinese: '该地区保护其自然资源。', lemma: 'riqueza', partOfSpeech: 'noun', frequencyRank: 2803 },
      { spanish: 'fracaso', chinese: '失败', example: 'El fracaso reveló un problema de diseño.', exampleChinese: '这次失败暴露了一个设计问题。', lemma: 'fracaso', partOfSpeech: 'noun', frequencyRank: 2832 },
      { spanish: 'gasto', chinese: '支出；花费', example: 'El gasto mensual superó el presupuesto.', exampleChinese: '每月支出超过预算。', lemma: 'gasto', partOfSpeech: 'noun', frequencyRank: 2834 },
      { spanish: 'margen', chinese: '余地；边缘；利润率', example: 'Todavía hay margen para mejorar.', exampleChinese: '仍有改进余地。', lemma: 'margen', partOfSpeech: 'noun', frequencyRank: 2838 },
    ],
  },
  {
    id: 'expansion-b2-process-public-007', level: 'B2', scene: '社会', title: '公共过程与制度讨论',
    description: '说明请求、抗议、程序设计和制度执行',
    frameworkReference: B1_B2_PCIC,
    words: [
      { spanish: 'intercambio', chinese: '交换；交流', example: 'El programa facilita el intercambio de ideas.', exampleChinese: '该项目促进思想交流。', lemma: 'intercambio', partOfSpeech: 'noun', frequencyRank: 2890 },
      { spanish: 'introducción', chinese: '介绍；引言；引入', example: 'La introducción resume el objetivo.', exampleChinese: '引言概述目标。', lemma: 'introducción', partOfSpeech: 'noun', frequencyRank: 2891 },
      { spanish: 'raíz', chinese: '根；根源', example: 'El informe analiza la raíz del conflicto.', exampleChinese: '报告分析冲突的根源。', lemma: 'raíz', partOfSpeech: 'noun', frequencyRank: 2901 },
      { spanish: 'fraude', chinese: '欺诈；舞弊', example: 'La auditoría detectó un fraude.', exampleChinese: '审计发现了一起欺诈。', lemma: 'fraude', partOfSpeech: 'noun', frequencyRank: 3051 },
      { spanish: 'petición', chinese: '请求；请愿', example: 'La administración recibió la petición.', exampleChinese: '行政部门收到了请求。', lemma: 'petición', partOfSpeech: 'noun', frequencyRank: 3068 },
      { spanish: 'programación', chinese: '编程；节目安排；排期', example: 'La programación del proyecto cambió.', exampleChinese: '项目排期改变了。', lemma: 'programación', partOfSpeech: 'noun', frequencyRank: 3075 },
      { spanish: 'protesta', chinese: '抗议；异议', example: 'La protesta reunió a miles de personas.', exampleChinese: '抗议活动聚集了数千人。', lemma: 'protesta', partOfSpeech: 'noun', frequencyRank: 3077 },
      { spanish: 'arquitectura', chinese: '建筑；架构', example: 'La arquitectura del sistema es flexible.', exampleChinese: '系统架构很灵活。', lemma: 'arquitectura', partOfSpeech: 'noun', frequencyRank: 3099 },
      { spanish: 'duración', chinese: '持续时间', example: 'La duración del contrato es de un año.', exampleChinese: '合同期限为一年。', lemma: 'duración', partOfSpeech: 'noun', frequencyRank: 3115 },
      { spanish: 'postura', chinese: '立场；姿势', example: 'El comité explicó su postura.', exampleChinese: '委员会解释了其立场。', lemma: 'postura', partOfSpeech: 'noun', frequencyRank: 3137 },
      { spanish: 'clasificación', chinese: '分类；排名', example: 'La clasificación utiliza criterios públicos.', exampleChinese: '该分类使用公开标准。', lemma: 'clasificación', partOfSpeech: 'noun', frequencyRank: 3166 },
      { spanish: 'cumplimiento', chinese: '履行；合规', example: 'La empresa revisa el cumplimiento de la norma.', exampleChinese: '公司检查规定的执行情况。', lemma: 'cumplimiento', partOfSpeech: 'noun', frequencyRank: 3170 },
    ],
  },
]
