import type { ExpansionDeck } from './lexiconExpansion'

const A1_A2_PCIC = 'https://cvc.cervantes.es/ensenanza/biblioteca_ele/plan_curricular/niveles/09_nociones_especificas_inventario_a1-a2.htm'
const B1_B2_PCIC = 'https://cvc.cervantes.es/ensenanza/biblioteca_ele/plan_curricular/niveles/09_nociones_especificas_inventario_b1-b2.htm'
type ExpansionWord = ExpansionDeck['words'][number]
const w = (spanish: string, chinese: string, example: string, exampleChinese: string, partOfSpeech: ExpansionWord['partOfSpeech'], frequencyRank: number): ExpansionWord => ({ spanish, chinese, example, exampleChinese, lemma: spanish, partOfSpeech, frequencyRank })

// Production batch 013: 96 canonical civic, service, work and culture targets.
export const expansionBatch013: ExpansionDeck[] = [
  {
    id: 'expansion-a2-events-services-013', level: 'A2', scene: '日常', title: '活动、服务与常见地点',
    description: '描述活动开始、常用物品和服务人员', frameworkReference: A1_A2_PCIC,
    words: [
      w('nacimiento', '出生；诞生', 'La fecha de nacimiento aparece en el documento.', '出生日期显示在证件上。', 'noun', 2303),
      w('actuación', '表演；行动；表现', 'La actuación comienza a las nueve.', '演出九点开始。', 'noun', 2325),
      w('apertura', '开放；开幕；开启', 'La apertura de la tienda será mañana.', '商店明天开业。', 'noun', 2329),
      w('definición', '定义；清晰度', 'Busca la definición en el diccionario.', '在词典中查找定义。', 'noun', 2336),
      w('pieza', '件；零件；作品', 'Falta una pieza de la máquina.', '机器缺少一个零件。', 'noun', 2412),
      w('promoción', '促销；晋升；推广', 'La promoción termina el domingo.', '促销周日结束。', 'noun', 2417),
      w('locura', '疯狂；荒唐事', 'Comprar eso sería una locura.', '买那个会很荒唐。', 'noun', 2454),
      w('catedral', '大教堂', 'La catedral está en el centro histórico.', '大教堂位于历史中心。', 'noun', 4307),
      w('gerente', '经理；负责人', 'La gerente aprobó el cambio.', '经理批准了这项改变。', 'noun', 4430),
      w('diccionario', '词典；字典', 'Consulta el diccionario para confirmar la palabra.', '查词典确认这个单词。', 'noun', 4700),
      w('fantasía', '幻想；奇幻作品', 'La película mezcla realidad y fantasía.', '电影融合了现实与幻想。', 'noun', 4709),
      w('asistente', '助手；参加者', 'El asistente prepara la sala.', '助手准备会议室。', 'noun', 4766),
    ],
  },
  {
    id: 'expansion-a2-digital-feelings-013', level: 'A2', scene: '科技', title: '数字信息与个人感受',
    description: '理解数字内容、频率、情绪与服务体验', frameworkReference: A1_A2_PCIC,
    words: [
      w('grabación', '录音；录像', 'La grabación dura cinco minutos.', '录音持续五分钟。', 'noun', 4793),
      w('relevante', '相关的；重要的', 'Incluya solo la información relevante.', '只填写相关信息。', 'adjective', 4832),
      w('conveniente', '合适的；方便的', 'Es conveniente reservar con tiempo.', '提前预订比较合适。', 'adjective', 4874),
      w('emocional', '情绪的；情感的', 'El estrés afecta al bienestar emocional.', '压力影响情绪健康。', 'adjective', 4888),
      w('estancia', '停留；房间', 'La estancia incluye el desayuno.', '住宿包含早餐。', 'noun', 4893),
      w('frecuente', '频繁的；常见的', 'Es un error frecuente.', '这是一个常见错误。', 'adjective', 4900),
      w('gráfica', '图表；图形的', 'La gráfica muestra los cambios mensuales.', '图表显示每月变化。', 'noun', 4906),
      w('informática', '计算机技术；信息学', 'Estudia informática por la tarde.', '她下午学习计算机技术。', 'noun', 4911),
      w('lógico', '合乎逻辑的；逻辑的', 'El resultado parece lógico.', '结果看起来合乎逻辑。', 'adjective', 4918),
      w('mensual', '每月的；月刊', 'La cuota mensual es fija.', '月费是固定的。', 'adjective', 4922),
      w('salvaje', '野生的；野蛮的', 'Es una especie salvaje protegida.', '这是一种受保护的野生物种。', 'adjective', 4941),
      w('satisfacción', '满意；满足', 'La encuesta mide la satisfacción del cliente.', '调查衡量客户满意度。', 'noun', 4943),
    ],
  },
  {
    id: 'expansion-b1-civic-economy-013', level: 'B1', scene: '社会', title: '公共治理与经济生活',
    description: '理解公共职位、制度选择和经济活动', frameworkReference: B1_B2_PCIC,
    words: [
      w('presidente', '总统；主席；会长', 'El presidente abrió la reunión.', '主席宣布会议开始。', 'noun', 227),
      w('política', '政策；政治', 'La empresa cambió su política de privacidad.', '公司修改了隐私政策。', 'noun', 249),
      w('república', '共和国', 'La república aprobó una nueva ley.', '共和国通过了一项新法律。', 'noun', 582),
      w('revolución', '革命；重大变革', 'La tecnología produjo una revolución industrial.', '技术带来了一场工业革命。', 'noun', 1002),
      w('económico', '经济的；便宜的', 'Busco un hotel económico.', '我在找一家经济实惠的酒店。', 'adjective', 1054),
      w('federal', '联邦的', 'La ley federal se aplica en todo el país.', '联邦法律适用于全国。', 'adjective', 1056),
      w('fiscal', '税务的；检察官', 'El año fiscal termina en diciembre.', '财政年度十二月结束。', 'adjective', 1214),
      w('comercial', '商业的；广告', 'La zona comercial está cerca.', '商业区就在附近。', 'adjective', 1237),
      w('electoral', '选举的', 'La campaña electoral empieza mañana.', '竞选活动明天开始。', 'adjective', 1266),
      w('provincial', '省级的；省份的', 'El gobierno provincial publicó el plan.', '省政府公布了计划。', 'adjective', 2684),
      w('popularidad', '受欢迎程度；知名度', 'La aplicación ganó popularidad.', '这款应用变得更受欢迎。', 'noun', 4739),
      w('adopción', '采用；收养', 'La adopción de la norma fue rápida.', '这项规范很快得到采用。', 'noun', 4848),
    ],
  },
  {
    id: 'expansion-b1-business-travel-013', level: 'B1', scene: '工作', title: '业务、出行与基础设施',
    description: '处理授权、公司事务、交通设施和能源项目', frameworkReference: B1_B2_PCIC,
    words: [
      w('consentimiento', '同意；许可', 'El tratamiento requiere consentimiento informado.', '治疗需要知情同意。', 'noun', 4871),
      w('corporación', '公司；法人团体', 'La corporación publicó sus resultados.', '公司公布了业绩。', 'noun', 4875),
      w('utilidad', '用途；效用；利润', 'La herramienta tiene mucha utilidad práctica.', '这个工具很实用。', 'noun', 4957),
      w('visible', '可见的；明显的', 'La señal debe estar visible.', '标志必须清晰可见。', 'adjective', 4959),
      w('atractivo', '有吸引力的；吸引力', 'El barrio resulta atractivo para familias.', '这个社区对家庭很有吸引力。', 'adjective', 4970),
      w('bahía', '海湾', 'El puerto está dentro de la bahía.', '港口位于海湾内。', 'noun', 4973),
      w('directiva', '指令；管理层', 'La directiva aprobó el presupuesto.', '管理层批准了预算。', 'noun', 4987),
      w('eléctrico', '电的；电动的', 'El vehículo eléctrico necesita carga.', '电动车需要充电。', 'adjective', 4991),
      w('minería', '采矿业；采矿', 'La minería consume mucha agua.', '采矿业消耗大量水。', 'noun', 5016),
      w('pasaje', '通道；票；段落', 'El pasaje incluye una maleta.', '这张票包含一件行李。', 'noun', 5026),
      w('renovación', '更新；续期；翻新', 'La renovación del permiso tarda una semana.', '许可证续期需要一周。', 'noun', 5039),
      w('terminal', '航站楼；终端', 'El vuelo sale de la terminal dos.', '航班从二号航站楼出发。', 'noun', 5050),
    ],
  },
  {
    id: 'expansion-b1-health-education-013', level: 'B1', scene: '健康', title: '健康、教育与生活支持',
    description: '描述身心状态、专业记录和社会支持', frameworkReference: B1_B2_PCIC,
    words: [
      w('debilidad', '虚弱；弱点', 'La fiebre puede causar debilidad.', '发烧可能导致虚弱。', 'noun', 5090),
      w('eficiente', '高效的；效率高的', 'El sistema es más eficiente.', '这个系统效率更高。', 'adjective', 5099),
      w('geografía', '地理；地理学', 'Estudia la geografía de América Latina.', '她学习拉丁美洲地理。', 'noun', 5112),
      w('historial', '记录；病史；浏览记录', 'El médico revisó el historial del paciente.', '医生查看了患者病史。', 'noun', 5115),
      w('mortal', '致命的；凡人', 'La enfermedad rara vez es mortal.', '这种疾病很少致命。', 'adjective', 5138),
      w('municipalidad', '市政府；市镇', 'La municipalidad gestiona el servicio.', '市政府管理这项服务。', 'noun', 5139),
      w('pánico', '恐慌；惊恐', 'La noticia causó pánico.', '这条消息引发恐慌。', 'noun', 5147),
      w('saludable', '健康的；有益健康的', 'Mantiene una dieta saludable.', '他保持健康饮食。', 'adjective', 5154),
      w('caridad', '慈善；仁爱', 'La organización trabaja por caridad.', '该组织从事慈善工作。', 'noun', 5182),
      w('empresarial', '企业的；商业管理的', 'El curso analiza la estrategia empresarial.', '课程分析企业战略。', 'adjective', 5196),
      w('entretenimiento', '娱乐；消遣', 'La plataforma ofrece entretenimiento familiar.', '平台提供家庭娱乐内容。', 'noun', 5197),
      w('espacial', '空间的；太空的', 'La agencia espacial lanzó un satélite.', '航天机构发射了一颗卫星。', 'adjective', 5198),
    ],
  },
  {
    id: 'expansion-b2-finance-change-013', level: 'B2', scene: '工作', title: '资金、变革与长期影响',
    description: '分析融资、变革过程和长期社会影响', frameworkReference: B1_B2_PCIC,
    words: [
      w('estética', '美学；外观风格', 'La reforma cambió la estética del edificio.', '翻修改变了建筑外观。', 'noun', 5201),
      w('financiamiento', '融资；资金支持', 'El proyecto necesita financiamiento público.', '项目需要公共资金支持。', 'noun', 5204),
      w('inauguración', '开幕；启用仪式', 'La inauguración será el lunes.', '开幕仪式将在周一举行。', 'noun', 5217),
      w('inevitable', '不可避免的', 'El cambio parece inevitable.', '变化似乎不可避免。', 'adjective', 5219),
      w('inseguridad', '不安全感；治安问题', 'La falta de luz aumenta la inseguridad.', '照明不足加剧不安全感。', 'noun', 5220),
      w('sabiduría', '智慧；明智', 'La experiencia aporta sabiduría.', '经验带来智慧。', 'noun', 5253),
      w('adquisición', '购买；收购；获得', 'La adquisición incluye todos los activos.', '此次收购包括所有资产。', 'noun', 5274),
      w('antigüedad', '年代；资历；古老物品', 'El salario depende de la antigüedad.', '工资取决于工龄。', 'noun', 5279),
      w('considerable', '相当大的；可观的', 'La obra requiere una inversión considerable.', '工程需要可观投资。', 'adjective', 5294),
      w('humedad', '湿度；潮湿', 'La humedad dañó la pared.', '潮湿损坏了墙壁。', 'noun', 5317),
      w('lealtad', '忠诚；忠实', 'La marca valora la lealtad del cliente.', '品牌重视客户忠诚度。', 'noun', 5324),
      w('modificación', '修改；变更', 'Toda modificación debe quedar registrada.', '所有修改都必须留有记录。', 'noun', 5333),
    ],
  },
  {
    id: 'expansion-b2-knowledge-quality-013', level: 'B2', scene: '学习', title: '知识、质量与实施能力',
    description: '评价知识活动、质量标准和方案实施', frameworkReference: B1_B2_PCIC,
    words: [
      w('seminario', '研讨会；专题课', 'El seminario reúne a varios especialistas.', '研讨会汇集了多位专家。', 'noun', 5350),
      w('consideración', '考虑；体谅', 'La propuesta merece consideración.', '这项建议值得考虑。', 'noun', 5386),
      w('continuidad', '连续性；延续', 'El acuerdo garantiza la continuidad del servicio.', '协议保障服务连续性。', 'noun', 5387),
      w('perfección', '完美；完善', 'El sistema no funciona a la perfección.', '系统运行得并不完美。', 'noun', 5419),
      w('sensibilidad', '敏感性；体贴', 'El tema requiere sensibilidad cultural.', '这个话题需要文化敏感性。', 'noun', 5435),
      w('agresión', '攻击；侵犯', 'La policía investiga la agresión.', '警方正在调查袭击事件。', 'noun', 5455),
      w('artificial', '人工的；人造的', 'La inteligencia artificial analiza los datos.', '人工智能分析数据。', 'adjective', 5462),
      w('civilización', '文明；文明社会', 'El museo explica la antigua civilización.', '博物馆介绍这个古代文明。', 'noun', 5473),
      w('diversión', '娱乐；乐趣', 'El viaje combina aprendizaje y diversión.', '旅行结合了学习和乐趣。', 'noun', 5498),
      w('escritorio', '书桌；桌面', 'Guarda el archivo en el escritorio.', '把文件保存在桌面上。', 'noun', 5504),
      w('especialista', '专家；专科医生', 'Consulte a un especialista.', '请咨询专家。', 'noun', 5505),
      w('implementación', '实施；部署', 'La implementación empieza el próximo mes.', '实施工作下个月开始。', 'noun', 5519),
    ],
  },
  {
    id: 'expansion-b2-rules-development-013', level: 'B2', scene: '行政', title: '规则、重建与技术发展',
    description: '理解正式限制、重建工作和技术发展成果', frameworkReference: B1_B2_PCIC,
    words: [
      w('novedad', '新情况；新事物', 'La actualización incluye una novedad importante.', '更新包含一项重要新功能。', 'noun', 5539),
      w('obligatorio', '强制的；必修的', 'El seguro es obligatorio.', '保险是强制性的。', 'adjective', 5541),
      w('prohibición', '禁止；禁令', 'La prohibición entra en vigor mañana.', '禁令明天生效。', 'noun', 5551),
      w('reconstrucción', '重建；重构', 'La reconstrucción del puente tardará un año.', '桥梁重建需要一年。', 'noun', 5556),
      w('significativo', '显著的；有意义的', 'El estudio encontró un cambio significativo.', '研究发现了显著变化。', 'adjective', 5562),
      w('tecnológico', '技术的；科技的', 'El avance tecnológico reduce costes.', '技术进步降低成本。', 'adjective', 5567),
      w('contribución', '贡献；捐款', 'Su contribución mejoró el proyecto.', '他的贡献改善了项目。', 'noun', 5596),
      w('elegante', '优雅的；简洁漂亮的', 'El diseño es sencillo y elegante.', '设计简洁而优雅。', 'adjective', 5611),
      w('expedición', '探险；远征；签发', 'La expedición científica duró dos meses.', '科学考察持续了两个月。', 'noun', 5616),
      w('mediodía', '中午', 'La oficina cierra al mediodía.', '办公室中午关门。', 'noun', 5636),
      w('certeza', '确定；确信', 'No existe certeza sobre la fecha.', '日期尚不能确定。', 'noun', 5699),
      w('exportación', '出口；导出', 'La exportación de datos requiere permiso.', '导出数据需要许可。', 'noun', 5729),
    ],
  },
]
