import type { ExpansionDeck } from './lexiconExpansion'

const A1_A2_PCIC = 'https://cvc.cervantes.es/ensenanza/biblioteca_ele/plan_curricular/niveles/09_nociones_especificas_inventario_a1-a2.htm'
const B1_B2_PCIC = 'https://cvc.cervantes.es/ensenanza/biblioteca_ele/plan_curricular/niveles/09_nociones_especificas_inventario_b1-b2.htm'
type ExpansionWord = ExpansionDeck['words'][number]
const w = (spanish: string, chinese: string, example: string, exampleChinese: string, partOfSpeech: ExpansionWord['partOfSpeech'], frequencyRank: number): ExpansionWord => ({ spanish, chinese, example, exampleChinese, lemma: spanish, partOfSpeech, frequencyRank })

// Production batch 017: 72 canonical targets covering everyday objects,
// personal description, work, public life, and advanced discourse.
export const expansionBatch017: ExpansionDeck[] = [
  {
    id: 'expansion-a2-everyday-objects-017', level: 'A2', scene: '日常', title: '人物、动物与身边物品',
    description: '补充描述家庭、动物、物品和常见状态的实用词', frameworkReference: A1_A2_PCIC,
    words: [
      w('gato', '猫', 'El gato duerme junto a la ventana.', '猫在窗边睡觉。', 'noun', 2081),
      w('dueño', '主人；所有者', 'El dueño de la tienda vive aquí.', '店主住在这里。', 'noun', 2112),
      w('letra', '字母；歌词', 'Escribe tu nombre con letra clara.', '请用清楚的字迹写下你的名字。', 'noun', 2119),
      w('entero', '完整的；整个的', 'Leí el libro entero durante el viaje.', '我在旅途中读完了整本书。', 'adjective', 2208),
      w('divertido', '有趣的；好玩的', 'El juego es sencillo y divertido.', '这个游戏简单又有趣。', 'adjective', 2246),
      w('útil', '有用的；实用的', 'Esta información puede ser útil.', '这些信息可能会有用。', 'adjective', 2279),
      w('alcohol', '酒精；酒', 'Esta bebida no contiene alcohol.', '这杯饮料不含酒精。', 'noun', 2326),
      w('caballo', '马', 'El caballo corre por el campo.', '马在田野里奔跑。', 'noun', 2330),
      w('firme', '牢固的；坚定的', 'La mesa está firme y no se mueve.', '桌子很稳，不会晃动。', 'adjective', 2343),
      w('inmediato', '立即的；紧邻的', 'Necesitamos apoyo inmediato.', '我们需要立即获得支持。', 'adjective', 2349),
      w('cabello', '头发', 'Tiene el cabello corto y oscuro.', '他留着深色短发。', 'noun', 2440),
      w('cercano', '附近的；亲近的', 'Busca un hotel cercano a la estación.', '找一家离车站近的酒店。', 'adjective', 2441),
    ],
  },
  {
    id: 'expansion-a2-family-feelings-017', level: 'A2', scene: '家庭', title: '家庭、感受与日常交流',
    description: '表达家庭关系、心情、活动和简单评价', frameworkReference: A1_A2_PCIC,
    words: [
      w('poquito', '一点点', 'Pon solo un poquito de sal.', '只放一点点盐。', 'adverb', 2468),
      w('ánimo', '心情；精神；鼓励', 'Hoy tengo buen ánimo.', '我今天心情不错。', 'noun', 2481),
      w('hoja', '纸张；叶子', 'Escribe la dirección en esta hoja.', '把地址写在这张纸上。', 'noun', 3564),
      w('aviso', '通知；提醒', 'Recibí un aviso en el móvil.', '我在手机上收到了一条通知。', 'noun', 2592),
      w('baile', '舞蹈；舞会', 'Hay una clase de baile los viernes.', '每周五有舞蹈课。', 'noun', 2644),
      w('abuelo', '祖父；外祖父', 'Mi abuelo prepara café por la mañana.', '我爷爷早上煮咖啡。', 'noun', 2693),
      w('apellido', '姓氏', '¿Cómo se escribe su apellido?', '您的姓怎么拼？', 'noun', 3534),
      w('contento', '高兴的；满意的', 'Estoy contento con el resultado.', '我对结果感到满意。', 'adjective', 3541),
      w('curioso', '好奇的；有趣的', 'Es curioso, pero nadie llamó.', '很奇怪，不过没人打电话。', 'adjective', 3543),
      w('feo', '难看的；糟糕的', 'Hace un día feo y lluvioso.', '今天阴雨绵绵，天气很糟。', 'adjective', 3556),
      w('maravilloso', '精彩的；美妙的', 'Pasamos un día maravilloso juntos.', '我们一起度过了美好的一天。', 'adjective', 3718),
      w('chiste', '笑话', 'Contó un chiste durante la cena.', '他在晚饭时讲了一个笑话。', 'noun', 3988),
    ],
  },
  {
    id: 'expansion-b1-work-society-017', level: 'B1', scene: '工作', title: '协作、社会与现实问题',
    description: '讨论合作关系、复杂情况和社会事件', frameworkReference: B1_B2_PCIC,
    words: [
      w('alianza', '联盟；合作关系', 'Las dos empresas formaron una alianza.', '两家公司建立了合作关系。', 'noun', 2232),
      w('complejo', '复杂的；综合体', 'El proceso parece más complejo de lo previsto.', '这个流程看起来比预想的更复杂。', 'adjective', 2242),
      w('mezcla', '混合；混合物', 'La ciudad es una mezcla de culturas.', '这座城市融合了多种文化。', 'noun', 2257),
      w('raza', '种族；品种', 'La ley prohíbe discriminar por raza.', '法律禁止种族歧视。', 'noun', 2266),
      w('rostro', '脸；面容', 'Su rostro mostraba preocupación.', '他的脸上显露出担忧。', 'noun', 2316),
      w('desastre', '灾难；惨败', 'La tormenta causó un desastre en la zona.', '暴风雨在该地区造成了灾害。', 'noun', 2337),
      w('robo', '盗窃；抢劫', 'Denunció el robo de su bicicleta.', '他报案称自行车被盗。', 'noun', 2424),
      w('tono', '语气；音调；色调', 'Su tono fue tranquilo y respetuoso.', '他的语气平静而有礼貌。', 'noun', 2428),
      w('actor', '演员；参与者', 'El actor respondió a las preguntas.', '这位演员回答了问题。', 'noun', 2484),
      w('poeta', '诗人', 'La poeta leyó su obra en público.', '这位诗人公开朗读了自己的作品。', 'noun', 2519),
      w('cuadro', '画；图表；方框', 'El informe incluye un cuadro comparativo.', '报告中包含一张对比表。', 'noun', 2551),
      w('físico', '身体的；物理的', 'El trabajo exige esfuerzo físico.', '这份工作需要体力。', 'adjective', 2611),
    ],
  },
  {
    id: 'expansion-b1-experience-description-017', level: 'B1', scene: '日常', title: '经历、环境与准确描述',
    description: '讲述经历并更准确地描述人物、地点和状态', frameworkReference: B1_B2_PCIC,
    words: [
      w('meta', '目标；终点', 'Nuestra meta es reducir el tiempo de espera.', '我们的目标是缩短等待时间。', 'noun', 2619),
      w('espectáculo', '演出；景象', 'El espectáculo empieza a las nueve.', '演出九点开始。', 'noun', 2658),
      w('esposo', '丈夫；配偶', 'Su esposo trabaja desde casa.', '她的丈夫在家办公。', 'noun', 2659),
      w('colonia', '街区；殖民地；香水', 'Vive en una colonia tranquila.', '他住在一个安静的街区。', 'noun', 2699),
      w('exacto', '准确的；确切的', 'No recuerdo el número exacto.', '我不记得确切的数字。', 'adjective', 2713),
      w('extra', '额外的；附加项', 'Necesito una copia extra del documento.', '我还需要一份文件副本。', 'adjective', 2714),
      w('oscuro', '黑暗的；深色的', 'El pasillo está demasiado oscuro.', '走廊太暗了。', 'adjective', 2736),
      w('partida', '出发；比赛；一局', 'La partida del tren se retrasó.', '火车出发时间推迟了。', 'noun', 2738),
      w('rol', '角色；作用', 'Cada persona tiene un rol diferente.', '每个人都有不同的角色。', 'noun', 2746),
      w('vacío', '空的；空白', 'El depósito está casi vacío.', '油箱几乎空了。', 'adjective', 2753),
      w('falso', '假的；错误的', 'El mensaje contenía un dato falso.', '这条消息包含一项错误信息。', 'adjective', 2776),
      w('hierro', '铁；铁制品', 'La puerta está hecha de hierro.', '这扇门是铁制的。', 'noun', 2781),
    ],
  },
  {
    id: 'expansion-b2-reasoning-connectors-017', level: 'B2', scene: '学习', title: '论述程度、顺序与让步',
    description: '用精确副词和连接成分组织较复杂的说明', frameworkReference: B1_B2_PCIC,
    words: [
      w('suma', '总和；加法', 'La suma de los gastos supera el presupuesto.', '各项支出的总和超过了预算。', 'noun', 2135),
      w('absolutamente', '绝对地；完全地', 'La información es absolutamente confidencial.', '这些信息完全保密。', 'adverb', 2145),
      w('anteriormente', '以前；先前', 'El edificio se usaba anteriormente como escuela.', '这栋楼以前被用作学校。', 'adverb', 2148),
      w('prácticamente', '几乎；实际上', 'El proyecto está prácticamente terminado.', '这个项目几乎完成了。', 'adverb', 2183),
      w('perfectamente', '完全地；完美地', 'Entiendo perfectamente su preocupación.', '我完全理解您的担忧。', 'adverb', 2222),
      w('pese', '尽管', 'Pese a la lluvia, continuó el acto.', '尽管下雨，活动仍继续进行。', 'preposition', 2307),
      w('fácilmente', '容易地', 'El documento puede consultarse fácilmente.', '这份文件很容易查阅。', 'adverb', 2344),
      w('únicamente', '仅仅；只', 'La entrada es únicamente para residentes.', '入口仅供居民使用。', 'adverb', 2432),
      w('obviamente', '显然地', 'Obviamente, todavía faltan algunos datos.', '显然，目前还缺少一些数据。', 'adverb', 2515),
      w('posteriormente', '后来；随后', 'El acuerdo fue modificado posteriormente.', '该协议后来经过了修改。', 'adverb', 2628),
      w('profundo', '深的；深刻的', 'El cambio tuvo un efecto profundo.', '这项变化产生了深远影响。', 'adjective', 2631),
      w('particularmente', '尤其；特别地', 'La medida afecta particularmente a los jóvenes.', '这项措施尤其影响年轻人。', 'adverb', 2679),
    ],
  },
  {
    id: 'expansion-b2-analysis-culture-017', level: 'B2', scene: '社会', title: '分析、叙事与公共话语',
    description: '分析观点、公共事件和文化叙事中的常用概念', frameworkReference: B1_B2_PCIC,
    words: [
      w('sujeto', '主体；对象；主语', 'El sujeto del estudio permanece anónimo.', '研究对象保持匿名。', 'noun', 2748),
      w('posterior', '之后的；后部的', 'La evaluación posterior confirmó el resultado.', '后续评估确认了结果。', 'adjective', 2796),
      w('aparentemente', '表面上；看起来', 'Aparentemente, las dos versiones coinciden.', '表面看来，两种说法是一致的。', 'adverb', 2919),
      w('posiblemente', '可能地', 'El precio aumentará posiblemente el próximo año.', '价格明年可能会上涨。', 'adverb', 2946),
      w('relativamente', '相对地', 'La solución es relativamente sencilla.', '这个解决方案相对简单。', 'adverb', 2950),
      w('terror', '恐怖；极度恐惧', 'La población vivió meses de terror.', '居民经历了数月的恐惧。', 'noun', 3025),
      w('fama', '名声；声誉', 'La ciudad tiene fama de ser acogedora.', '这座城市以热情好客著称。', 'noun', 3181),
      w('jurado', '评审团；陪审团', 'El jurado anunció su decisión final.', '评审团宣布了最终决定。', 'noun', 3194),
      w('propaganda', '宣传；宣传材料', 'La campaña difundió propaganda engañosa.', '该活动传播了误导性宣传。', 'noun', 3205),
      w('concreto', '具体的；混凝土', 'Necesitamos un ejemplo concreto.', '我们需要一个具体例子。', 'adjective', 3235),
      w('constantemente', '不断地；经常地', 'Las condiciones cambian constantemente.', '条件在不断变化。', 'adverb', 3237),
      w('leyenda', '传说；图例', 'La leyenda explica el origen del pueblo.', '这个传说解释了村庄的起源。', 'noun', 3264),
    ],
  },
]
