import type { ExpansionDeck } from './lexiconExpansion'

const A1_A2_PCIC = 'https://cvc.cervantes.es/ensenanza/biblioteca_ele/plan_curricular/niveles/09_nociones_especificas_inventario_a1-a2.htm'
const B1_B2_PCIC = 'https://cvc.cervantes.es/ensenanza/biblioteca_ele/plan_curricular/niveles/09_nociones_especificas_inventario_b1-b2.htm'

// Production batch 005: 96 daily-use canonical targets selected from the
// fixed wordfreq snapshot and mapped conservatively to PCIC domains.
export const expansionBatch005: ExpansionDeck[] = [
  {
    id: 'expansion-a1-city-services-005', level: 'A1', scene: '城市', title: '城市服务与出行',
    description: '在街区、公共场所和旅途中辨认基础信息',
    frameworkReference: A1_A2_PCIC,
    words: [
      { spanish: 'zona', chinese: '区域；地带', example: 'Esta zona es muy tranquila.', exampleChinese: '这个区域很安静。', lemma: 'zona', partOfSpeech: 'noun', frequencyRank: 442 },
      { spanish: 'policía', chinese: '警察；警方', example: 'La policía está en la estación.', exampleChinese: '警察在车站。', lemma: 'policía', partOfSpeech: 'noun', frequencyRank: 436 },
      { spanish: 'puente', chinese: '桥', example: 'El autobús cruza el puente.', exampleChinese: '公交车驶过桥。', lemma: 'puente', partOfSpeech: 'noun', frequencyRank: 1697 },
      { spanish: 'accidente', chinese: '事故；意外', example: 'Hay un accidente en la carretera.', exampleChinese: '公路上发生了事故。', lemma: 'accidente', partOfSpeech: 'noun', frequencyRank: 1752 },
      { spanish: 'biblioteca', chinese: '图书馆', example: 'La biblioteca abre a las nueve.', exampleChinese: '图书馆九点开门。', lemma: 'biblioteca', partOfSpeech: 'noun', frequencyRank: 1759 },
      { spanish: 'celular', chinese: '手机', example: 'Mi celular está sin batería.', exampleChinese: '我的手机没电了。', lemma: 'celular', partOfSpeech: 'noun', frequencyRank: 1761 },
      { spanish: 'ruta', chinese: '路线；线路', example: 'Esta ruta llega al centro.', exampleChinese: '这条线路到市中心。', lemma: 'ruta', partOfSpeech: 'noun', frequencyRank: 1792 },
      { spanish: 'carretera', chinese: '公路', example: 'La carretera está cerrada.', exampleChinese: '公路关闭了。', lemma: 'carretera', partOfSpeech: 'noun', frequencyRank: 2103 },
      { spanish: 'esquina', chinese: '街角；拐角', example: 'La farmacia está en la esquina.', exampleChinese: '药店在街角。', lemma: 'esquina', partOfSpeech: 'noun', frequencyRank: 2882 },
      { spanish: 'restaurante', chinese: '餐厅', example: 'El restaurante sirve comida local.', exampleChinese: '这家餐厅供应当地菜。', lemma: 'restaurante', partOfSpeech: 'noun', frequencyRank: 2952 },
      { spanish: 'reloj', chinese: '钟；手表', example: 'El reloj marca las ocho.', exampleChinese: '钟显示八点。', lemma: 'reloj', partOfSpeech: 'noun', frequencyRank: 3440 },
      { spanish: 'plato', chinese: '盘子；一道菜', example: 'Este plato lleva arroz.', exampleChinese: '这道菜里有米饭。', lemma: 'plato', partOfSpeech: 'noun', frequencyRank: 3507 },
    ],
  },
  {
    id: 'expansion-a1-weather-leisure-005', level: 'A1', scene: '日常', title: '天气、自然与休闲',
    description: '描述季节、声音、活动和日常感受',
    frameworkReference: A1_A2_PCIC,
    words: [
      { spanish: 'animal', chinese: '动物', example: 'Este animal vive en el bosque.', exampleChinese: '这种动物生活在森林里。', lemma: 'animal', partOfSpeech: 'noun', frequencyRank: 1836 },
      { spanish: 'museo', chinese: '博物馆', example: 'El museo cierra los lunes.', exampleChinese: '博物馆星期一闭馆。', lemma: 'museo', partOfSpeech: 'noun', frequencyRank: 1867 },
      { spanish: 'cumpleaños', chinese: '生日', example: 'Mi cumpleaños es en marzo.', exampleChinese: '我的生日在三月。', lemma: 'cumpleaños', partOfSpeech: 'noun', frequencyRank: 1892 },
      { spanish: 'valle', chinese: '山谷；河谷', example: 'El río cruza el valle.', exampleChinese: '河流穿过山谷。', lemma: 'valle', partOfSpeech: 'noun', frequencyRank: 1925 },
      { spanish: 'señal', chinese: '信号；标志', example: 'No hay señal dentro del túnel.', exampleChinese: '隧道里没有信号。', lemma: 'señal', partOfSpeech: 'noun', frequencyRank: 1918 },
      { spanish: 'invierno', chinese: '冬天', example: 'En invierno oscurece pronto.', exampleChinese: '冬天天黑得早。', lemma: 'invierno', partOfSpeech: 'noun', frequencyRank: 1941 },
      { spanish: 'viento', chinese: '风', example: 'Hoy hace mucho viento.', exampleChinese: '今天风很大。', lemma: 'viento', partOfSpeech: 'noun', frequencyRank: 1926 },
      { spanish: 'sonido', chinese: '声音；音响', example: 'El sonido está demasiado alto.', exampleChinese: '声音太大了。', lemma: 'sonido', partOfSpeech: 'noun', frequencyRank: 1961 },
      { spanish: 'sorpresa', chinese: '惊喜；意外', example: 'Tengo una sorpresa para ti.', exampleChinese: '我给你准备了一个惊喜。', lemma: 'sorpresa', partOfSpeech: 'noun', frequencyRank: 1962 },
      { spanish: 'caliente', chinese: '热的；烫的', example: 'La sopa está caliente.', exampleChinese: '汤很烫。', lemma: 'caliente', partOfSpeech: 'adjective', frequencyRank: 2196 },
      { spanish: 'lluvia', chinese: '雨；降雨', example: 'La lluvia empieza por la tarde.', exampleChinese: '下午开始下雨。', lemma: 'lluvia', partOfSpeech: 'noun', frequencyRank: 2120 },
      { spanish: 'concierto', chinese: '音乐会', example: 'El concierto empieza a las ocho.', exampleChinese: '音乐会八点开始。', lemma: 'concierto', partOfSpeech: 'noun', frequencyRank: 2154 },
    ],
  },
  {
    id: 'expansion-a2-shopping-services-005', level: 'A2', scene: '购物', title: '购物、服务与旅行安排',
    description: '处理订单、价格、付款和旅途中的常见需求',
    frameworkReference: A1_A2_PCIC,
    words: [
      { spanish: 'producto', chinese: '产品；商品', example: 'Este producto tiene garantía.', exampleChinese: '这件商品有保修。', lemma: 'producto', partOfSpeech: 'noun', frequencyRank: 1179 },
      { spanish: 'crédito', chinese: '信用；贷款；学分', example: 'Pago la compra a crédito.', exampleChinese: '我用信用方式支付这笔购物。', lemma: 'crédito', partOfSpeech: 'noun', frequencyRank: 1631 },
      { spanish: 'gas', chinese: '燃气；气体', example: 'La factura del gas llega mañana.', exampleChinese: '燃气账单明天到。', lemma: 'gas', partOfSpeech: 'noun', frequencyRank: 1636 },
      { spanish: 'pedido', chinese: '订单；点单', example: 'El pedido llega esta tarde.', exampleChinese: '订单今天下午送到。', lemma: 'pedido', partOfSpeech: 'noun', frequencyRank: 1646 },
      { spanish: 'costo', chinese: '成本；费用', example: 'El costo incluye el transporte.', exampleChinese: '费用包含运输。', lemma: 'costo', partOfSpeech: 'noun', frequencyRank: 1763 },
      { spanish: 'entrega', chinese: '交付；配送', example: 'La entrega es gratuita.', exampleChinese: '配送免费。', lemma: 'entrega', partOfSpeech: 'noun', frequencyRank: 1769 },
      { spanish: 'oferta', chinese: '优惠；报价；提议', example: 'La oferta termina hoy.', exampleChinese: '优惠今天结束。', lemma: 'oferta', partOfSpeech: 'noun', frequencyRank: 1950 },
      { spanish: 'vuelo', chinese: '航班；飞行', example: 'El vuelo sale a las siete.', exampleChinese: '航班七点起飞。', lemma: 'vuelo', partOfSpeech: 'noun', frequencyRank: 2061 },
      { spanish: 'cerveza', chinese: '啤酒', example: 'Quiero una cerveza sin alcohol.', exampleChinese: '我想要一杯无酒精啤酒。', lemma: 'cerveza', partOfSpeech: 'noun', frequencyRank: 2546 },
      { spanish: 'azúcar', chinese: '糖', example: 'No tomo azúcar con el café.', exampleChinese: '我喝咖啡不加糖。', lemma: 'azúcar', partOfSpeech: 'noun', frequencyRank: 2863 },
      { spanish: 'bar', chinese: '酒吧；小餐馆', example: 'El bar sirve desayunos.', exampleChinese: '这家小餐馆供应早餐。', lemma: 'bar', partOfSpeech: 'noun', frequencyRank: 2489 },
      { spanish: 'emergencia', chinese: '紧急情况；急诊', example: 'Llama a emergencias si hay una emergencia.', exampleChinese: '如遇紧急情况，请拨打急救电话。', lemma: 'emergencia', partOfSpeech: 'noun', frequencyRank: 2340 },
    ],
  },
  {
    id: 'expansion-a2-home-nature-005', level: 'A2', scene: '家庭', title: '居住、自然与周围环境',
    description: '谈论家中物品、方位、自然和季节变化',
    frameworkReference: A1_A2_PCIC,
    words: [
      { spanish: 'cola', chinese: '队伍；尾巴', example: 'Hay una cola delante de la taquilla.', exampleChinese: '售票处前排着队。', lemma: 'cola', partOfSpeech: 'noun', frequencyRank: 2105 },
      { spanish: 'oeste', chinese: '西方；西部', example: 'El sol baja por el oeste.', exampleChinese: '太阳从西边落下。', lemma: 'oeste', partOfSpeech: 'noun', frequencyRank: 2125 },
      { spanish: 'fotografía', chinese: '照片；摄影', example: 'Esta fotografía es de mi familia.', exampleChinese: '这张照片是我的家人。', lemma: 'fotografía', partOfSpeech: 'noun', frequencyRank: 2250 },
      { spanish: 'salón', chinese: '客厅；大厅', example: 'El salón tiene mucha luz.', exampleChinese: '客厅光线很好。', lemma: 'salón', partOfSpeech: 'noun', frequencyRank: 2269 },
      { spanish: 'árbol', chinese: '树', example: 'Hay un árbol delante de la casa.', exampleChinese: '房子前面有一棵树。', lemma: 'árbol', partOfSpeech: 'noun', frequencyRank: 2277 },
      { spanish: 'bosque', chinese: '森林', example: 'Caminamos por el bosque.', exampleChinese: '我们穿过森林散步。', lemma: 'bosque', partOfSpeech: 'noun', frequencyRank: 2283 },
      { spanish: 'primavera', chinese: '春天', example: 'Las flores aparecen en primavera.', exampleChinese: '花在春天开放。', lemma: 'primavera', partOfSpeech: 'noun', frequencyRank: 2311 },
      { spanish: 'ruido', chinese: '噪声；声响', example: 'La calle tiene mucho ruido.', exampleChinese: '这条街很吵。', lemma: 'ruido', partOfSpeech: 'noun', frequencyRank: 2317 },
      { spanish: 'sal', chinese: '盐', example: 'La sopa necesita un poco de sal.', exampleChinese: '汤需要加一点盐。', lemma: 'sal', partOfSpeech: 'noun', frequencyRank: 2318 },
      { spanish: 'vestido', chinese: '连衣裙；服装', example: 'El vestido azul está en oferta.', exampleChinese: '蓝色连衣裙正在打折。', lemma: 'vestido', partOfSpeech: 'noun', frequencyRank: 2322 },
      { spanish: 'jardín', chinese: '花园', example: 'Los niños juegan en el jardín.', exampleChinese: '孩子们在花园里玩。', lemma: 'jardín', partOfSpeech: 'noun', frequencyRank: 2351 },
      { spanish: 'montaña', chinese: '山；山区', example: 'La montaña tiene nieve.', exampleChinese: '山上有雪。', lemma: 'montaña', partOfSpeech: 'noun', frequencyRank: 2403 },
    ],
  },
  {
    id: 'expansion-b1-work-thinking-005', level: 'B1', scene: '工作', title: '工作、计划与思考',
    description: '组织项目、表达策略并说明职业环境',
    frameworkReference: B1_B2_PCIC,
    words: [
      { spanish: 'inteligencia', chinese: '智力；智能', example: 'La inteligencia se desarrolla con práctica.', exampleChinese: '智力可以通过练习发展。', lemma: 'inteligencia', partOfSpeech: 'noun', frequencyRank: 1640 },
      { spanish: 'permiso', chinese: '许可；请假', example: 'Necesito permiso para entrar.', exampleChinese: '我需要许可才能进入。', lemma: 'permiso', partOfSpeech: 'noun', frequencyRank: 1693 },
      { spanish: 'presentación', chinese: '展示；介绍', example: 'La presentación dura veinte minutos.', exampleChinese: '展示持续二十分钟。', lemma: 'presentación', partOfSpeech: 'noun', frequencyRank: 1694 },
      { spanish: 'reconocimiento', chinese: '认可；识别', example: 'Su trabajo recibió reconocimiento público.', exampleChinese: '他的工作获得了公众认可。', lemma: 'reconocimiento', partOfSpeech: 'noun', frequencyRank: 1699 },
      { spanish: 'categoría', chinese: '类别；等级', example: 'Cada producto pertenece a una categoría.', exampleChinese: '每件商品属于一个类别。', lemma: 'categoría', partOfSpeech: 'noun', frequencyRank: 1716 },
      { spanish: 'concurso', chinese: '比赛；竞赛；招聘考试', example: 'El equipo ganó el concurso.', exampleChinese: '团队赢得了比赛。', lemma: 'concurso', partOfSpeech: 'noun', frequencyRank: 1718 },
      { spanish: 'estrategia', chinese: '策略；战略', example: 'La estrategia debe ser sencilla.', exampleChinese: '策略应该简单。', lemma: 'estrategia', partOfSpeech: 'noun', frequencyRank: 1727 },
      { spanish: 'pensamiento', chinese: '思想；思考', example: 'El pensamiento crítico requiere tiempo.', exampleChinese: '批判性思考需要时间。', lemma: 'pensamiento', partOfSpeech: 'noun', frequencyRank: 1741 },
      { spanish: 'periodista', chinese: '记者', example: 'La periodista trabaja para una radio local.', exampleChinese: '这位记者在当地广播电台工作。', lemma: 'periodista', partOfSpeech: 'noun', frequencyRank: 1742 },
      { spanish: 'etapa', chinese: '阶段', example: 'El proyecto entra en una nueva etapa.', exampleChinese: '项目进入新阶段。', lemma: 'etapa', partOfSpeech: 'noun', frequencyRank: 1771 },
      { spanish: 'iniciativa', chinese: '主动性；倡议', example: 'La iniciativa ayuda a pequeños negocios.', exampleChinese: '这项倡议帮助小企业。', lemma: 'iniciativa', partOfSpeech: 'noun', frequencyRank: 1774 },
      { spanish: 'laboral', chinese: '工作的；劳动的', example: 'Busco una oportunidad laboral estable.', exampleChinese: '我在寻找稳定的工作机会。', lemma: 'laboral', partOfSpeech: 'adjective', frequencyRank: 1822 },
    ],
  },
  {
    id: 'expansion-b1-communication-culture-005', level: 'B1', scene: '学习', title: '沟通、媒体与文化活动',
    description: '理解文章、活动和合作交流中的常用词',
    frameworkReference: B1_B2_PCIC,
    words: [
      { spanish: 'publicidad', chinese: '广告；宣传', example: 'La publicidad aparece en redes sociales.', exampleChinese: '广告出现在社交网络上。', lemma: 'publicidad', partOfSpeech: 'noun', frequencyRank: 1827 },
      { spanish: 'trato', chinese: '对待；交易；协议', example: 'El trato con los clientes es amable.', exampleChinese: '对待顾客很友善。', lemma: 'trato', partOfSpeech: 'noun', frequencyRank: 1832 },
      { spanish: 'colaboración', chinese: '合作', example: 'La colaboración mejora el resultado.', exampleChinese: '合作改善了结果。', lemma: 'colaboración', partOfSpeech: 'noun', frequencyRank: 1840 },
      { spanish: 'conferencia', chinese: '会议；讲座', example: 'La conferencia comienza mañana.', exampleChinese: '会议明天开始。', lemma: 'conferencia', partOfSpeech: 'noun', frequencyRank: 1842 },
      { spanish: 'cuento', chinese: '故事；短篇小说', example: 'Leemos un cuento corto en clase.', exampleChinese: '我们在课堂上读一篇短故事。', lemma: 'cuento', partOfSpeech: 'noun', frequencyRank: 1843 },
      { spanish: 'frecuencia', chinese: '频率；班次', example: 'El autobús pasa con poca frecuencia.', exampleChinese: '公交车班次很少。', lemma: 'frecuencia', partOfSpeech: 'noun', frequencyRank: 1852 },
      { spanish: 'breve', chinese: '简短的；短暂的', example: 'El informe incluye un resumen breve.', exampleChinese: '报告包含一份简短摘要。', lemma: 'breve', partOfSpeech: 'adjective', frequencyRank: 1888 },
      { spanish: 'capítulo', chinese: '章节；一集', example: 'El capítulo explica el método.', exampleChinese: '这一章解释了方法。', lemma: 'capítulo', partOfSpeech: 'noun', frequencyRank: 1889 },
      { spanish: 'firma', chinese: '签名；公司', example: 'Falta tu firma en el documento.', exampleChinese: '文件上缺少你的签名。', lemma: 'firma', partOfSpeech: 'noun', frequencyRank: 1898 },
      { spanish: 'juventud', chinese: '青春；青年群体', example: 'La juventud participa en el proyecto.', exampleChinese: '青年群体参与了该项目。', lemma: 'juventud', partOfSpeech: 'noun', frequencyRank: 1902 },
      { spanish: 'tradición', chinese: '传统', example: 'La fiesta mantiene una tradición local.', exampleChinese: '这个节日保留了一项当地传统。', lemma: 'tradición', partOfSpeech: 'noun', frequencyRank: 1923 },
      { spanish: 'colección', chinese: '收藏；系列', example: 'El museo presenta una nueva colección.', exampleChinese: '博物馆展出一个新系列。', lemma: 'colección', partOfSpeech: 'noun', frequencyRank: 1930 },
    ],
  },
  {
    id: 'expansion-b2-society-analysis-005', level: 'B2', scene: '社会', title: '社会系统与问题分析',
    description: '讨论制度、公共决策、环境与行为影响',
    frameworkReference: B1_B2_PCIC,
    words: [
      { spanish: 'resistencia', chinese: '抵抗；耐力', example: 'El material ofrece buena resistencia.', exampleChinese: '这种材料具有良好的耐受性。', lemma: 'resistencia', partOfSpeech: 'noun', frequencyRank: 1655 },
      { spanish: 'consecuencia', chinese: '后果；结果', example: 'Cada decisión tiene una consecuencia.', exampleChinese: '每项决定都有后果。', lemma: 'consecuencia', partOfSpeech: 'noun', frequencyRank: 1672 },
      { spanish: 'impacto', chinese: '影响；冲击', example: 'La medida tendrá impacto social.', exampleChinese: '这项措施会产生社会影响。', lemma: 'impacto', partOfSpeech: 'noun', frequencyRank: 1818 },
      { spanish: 'igualdad', chinese: '平等', example: 'La ley busca mayor igualdad.', exampleChinese: '法律寻求更大程度的平等。', lemma: 'igualdad', partOfSpeech: 'noun', frequencyRank: 1940 },
      { spanish: 'método', chinese: '方法', example: 'El método combina teoría y práctica.', exampleChinese: '这种方法结合理论与实践。', lemma: 'método', partOfSpeech: 'noun', frequencyRank: 1947 },
      { spanish: 'clima', chinese: '气候；氛围', example: 'El clima afecta a la agricultura.', exampleChinese: '气候影响农业。', lemma: 'clima', partOfSpeech: 'noun', frequencyRank: 1974 },
      { spanish: 'comportamiento', chinese: '行为；表现', example: 'El informe analiza el comportamiento del mercado.', exampleChinese: '报告分析市场表现。', lemma: 'comportamiento', partOfSpeech: 'noun', frequencyRank: 1975 },
      { spanish: 'discusión', chinese: '讨论；争论', example: 'La propuesta abrió una discusión pública.', exampleChinese: '这项提议引发了公开讨论。', lemma: 'discusión', partOfSpeech: 'noun', frequencyRank: 1979 },
      { spanish: 'dominio', chinese: '掌握；领域；域名', example: 'El puesto exige dominio del español.', exampleChinese: '该职位要求熟练掌握西班牙语。', lemma: 'dominio', partOfSpeech: 'noun', frequencyRank: 1981 },
      { spanish: 'asistencia', chinese: '出席；援助', example: 'La asistencia al curso es obligatoria.', exampleChinese: '课程必须出席。', lemma: 'asistencia', partOfSpeech: 'noun', frequencyRank: 2008 },
      { spanish: 'ayuntamiento', chinese: '市政府；市政厅', example: 'El ayuntamiento publicó el nuevo plan.', exampleChinese: '市政府公布了新计划。', lemma: 'ayuntamiento', partOfSpeech: 'noun', frequencyRank: 2009 },
      { spanish: 'fundamental', chinese: '根本的；至关重要的', example: 'La confianza es fundamental para cooperar.', exampleChinese: '信任对于合作至关重要。', lemma: 'fundamental', partOfSpeech: 'adjective', frequencyRank: 2027 },
    ],
  },
  {
    id: 'expansion-b2-ideas-change-005', level: 'B2', scene: '学习', title: '观点、变化与精确表达',
    description: '描述发展过程、抽象关系和论证细节',
    frameworkReference: B1_B2_PCIC,
    words: [
      { spanish: 'disposición', chinese: '意愿；安排；规定', example: 'El equipo mostró buena disposición al cambio.', exampleChinese: '团队表现出良好的改变意愿。', lemma: 'disposición', partOfSpeech: 'noun', frequencyRank: 2111 },
      { spanish: 'sentimiento', chinese: '感情；感受', example: 'El texto expresa un sentimiento de pérdida.', exampleChinese: '文章表达了一种失落感。', lemma: 'sentimiento', partOfSpeech: 'noun', frequencyRank: 2132 },
      { spanish: 'descripción', chinese: '描述；说明', example: 'La descripción del problema es precisa.', exampleChinese: '对问题的描述很准确。', lemma: 'descripción', partOfSpeech: 'noun', frequencyRank: 2160 },
      { spanish: 'evolución', chinese: '演变；发展', example: 'El gráfico muestra la evolución de los precios.', exampleChinese: '图表显示价格的变化。', lemma: 'evolución', partOfSpeech: 'noun', frequencyRank: 2165 },
      { spanish: 'ingreso', chinese: '收入；进入', example: 'El ingreso medio aumentó este año.', exampleChinese: '今年平均收入提高了。', lemma: 'ingreso', partOfSpeech: 'noun', frequencyRank: 2172 },
      { spanish: 'permanente', chinese: '永久的；持续的', example: 'La mejora requiere atención permanente.', exampleChinese: '改进需要持续关注。', lemma: 'permanente', partOfSpeech: 'adjective', frequencyRank: 2181 },
      { spanish: 'traducción', chinese: '翻译；译文', example: 'La traducción conserva el sentido original.', exampleChinese: '译文保留了原意。', lemma: 'traducción', partOfSpeech: 'noun', frequencyRank: 2189 },
      { spanish: 'filosofía', chinese: '哲学；理念', example: 'La empresa cambió su filosofía de trabajo.', exampleChinese: '公司改变了工作理念。', lemma: 'filosofía', partOfSpeech: 'noun', frequencyRank: 2212 },
      { spanish: 'límite', chinese: '界限；限制', example: 'El acuerdo establece un límite claro.', exampleChinese: '协议设定了清晰界限。', lemma: 'límite', partOfSpeech: 'noun', frequencyRank: 2256 },
      { spanish: 'reacción', chinese: '反应；回应', example: 'La noticia provocó una reacción inmediata.', exampleChinese: '这条消息引发了即时反应。', lemma: 'reacción', partOfSpeech: 'noun', frequencyRank: 2267 },
      { spanish: 'significado', chinese: '意义；含义', example: 'El contexto aclara el significado de la palabra.', exampleChinese: '语境阐明了这个词的含义。', lemma: 'significado', partOfSpeech: 'noun', frequencyRank: 2320 },
      { spanish: 'factor', chinese: '因素；因子', example: 'El tiempo es un factor decisivo.', exampleChinese: '时间是一个决定性因素。', lemma: 'factor', partOfSpeech: 'noun', frequencyRank: 2983 },
    ],
  },
]
