import type { ExpansionDeck } from './lexiconExpansion'

const A1_A2_PCIC = 'https://cvc.cervantes.es/ensenanza/biblioteca_ele/plan_curricular/niveles/09_nociones_especificas_inventario_a1-a2.htm'
const B1_B2_PCIC = 'https://cvc.cervantes.es/ensenanza/biblioteca_ele/plan_curricular/niveles/09_nociones_especificas_inventario_b1-b2.htm'

// Production batch 004: 72 daily-use, frequency-backed canonical targets.
// Observed conjugations, plurals, proper names and productive gender variants
// were rejected instead of being used to inflate the learning-item count.
export const expansionBatch004: ExpansionDeck[] = [
  {
    id: 'expansion-a1-home-city-004', level: 'A1', scene: '城市', title: '家里与城市中的基础信息',
    description: '认路、联系、上学和处理日常小事的基础词',
    frameworkReference: A1_A2_PCIC,
    words: [
      { spanish: 'número', chinese: '数字；号码', example: 'Escribe tu número aquí.', exampleChinese: '把你的号码写在这里。', lemma: 'número', partOfSpeech: 'noun', frequencyRank: 282 },
      { spanish: 'mamá', chinese: '妈妈', example: 'Mi mamá vive cerca.', exampleChinese: '我妈妈住得很近。', lemma: 'mamá', partOfSpeech: 'noun', frequencyRank: 866 },
      { spanish: 'carta', chinese: '信；菜单', example: 'La carta llega mañana.', exampleChinese: '信明天到。', lemma: 'carta', partOfSpeech: 'noun', frequencyRank: 873 },
      { spanish: 'colegio', chinese: '学校', example: 'El colegio está al lado del parque.', exampleChinese: '学校就在公园旁边。', lemma: 'colegio', partOfSpeech: 'noun', frequencyRank: 888 },
      { spanish: 'abajo', chinese: '在下面；向下', example: 'El baño está abajo.', exampleChinese: '卫生间在楼下。', lemma: 'abajo', partOfSpeech: 'adverb', frequencyRank: 906 },
      { spanish: 'atrás', chinese: '在后面；向后', example: 'La salida está atrás.', exampleChinese: '出口在后面。', lemma: 'atrás', partOfSpeech: 'adverb', frequencyRank: 907 },
      { spanish: 'sala', chinese: '客厅；房间', example: 'La sala tiene dos ventanas.', exampleChinese: '客厅有两扇窗户。', lemma: 'sala', partOfSpeech: 'noun', frequencyRank: 1067 },
      { spanish: 'perro', chinese: '狗', example: 'El perro duerme en la sala.', exampleChinese: '狗睡在客厅里。', lemma: 'perro', partOfSpeech: 'noun', frequencyRank: 1119 },
      { spanish: 'parque', chinese: '公园', example: 'Caminamos por el parque.', exampleChinese: '我们在公园散步。', lemma: 'parque', partOfSpeech: 'noun', frequencyRank: 1254 },
      { spanish: 'caja', chinese: '箱子；收银台', example: 'Paga en la caja.', exampleChinese: '请在收银台付款。', lemma: 'caja', partOfSpeech: 'noun', frequencyRank: 1306 },
      { spanish: 'piso', chinese: '公寓；楼层；地面', example: 'Vivo en el tercer piso.', exampleChinese: '我住在三楼。', lemma: 'piso', partOfSpeech: 'noun', frequencyRank: 1419 },
      { spanish: 'calor', chinese: '热；高温', example: 'Hoy hace mucho calor.', exampleChinese: '今天很热。', lemma: 'calor', partOfSpeech: 'noun', frequencyRank: 1499 },
    ],
  },
  {
    id: 'expansion-a1-family-routine-004', level: 'A1', scene: '家庭', title: '家庭、作息与休闲',
    description: '描述家人、身体感受和日常安排',
    frameworkReference: A1_A2_PCIC,
    words: [
      { spanish: 'sueño', chinese: '困意；睡眠；梦', example: 'Tengo sueño después de comer.', exampleChinese: '吃完饭后我困了。', lemma: 'sueño', partOfSpeech: 'noun', frequencyRank: 1070 },
      { spanish: 'pareja', chinese: '伴侣；一对', example: 'Mi pareja trabaja desde casa.', exampleChinese: '我的伴侣居家工作。', lemma: 'pareja', partOfSpeech: 'noun', frequencyRank: 1097 },
      { spanish: 'hogar', chinese: '家；家庭', example: 'Este lugar es nuestro hogar.', exampleChinese: '这里是我们的家。', lemma: 'hogar', partOfSpeech: 'noun', frequencyRank: 1267 },
      { spanish: 'pelo', chinese: '头发；毛发', example: 'Tengo el pelo corto.', exampleChinese: '我留着短发。', lemma: 'pelo', partOfSpeech: 'noun', frequencyRank: 1328 },
      { spanish: 'afuera', chinese: '在外面；向外', example: 'Los niños juegan afuera.', exampleChinese: '孩子们在外面玩。', lemma: 'afuera', partOfSpeech: 'adverb', frequencyRank: 1398 },
      { spanish: 'cita', chinese: '预约；约会', example: 'Tengo una cita a las diez.', exampleChinese: '我十点有预约。', lemma: 'cita', partOfSpeech: 'noun', frequencyRank: 1470 },
      { spanish: 'vacaciones', chinese: '假期', example: 'Las vacaciones empiezan el lunes.', exampleChinese: '假期星期一开始。', lemma: 'vacaciones', partOfSpeech: 'noun', frequencyRank: 1594 },
      { spanish: 'tarea', chinese: '任务；作业', example: 'Termino la tarea antes de cenar.', exampleChinese: '我在晚饭前完成作业。', lemma: 'tarea', partOfSpeech: 'noun', frequencyRank: 1620 },
      { spanish: 'playa', chinese: '海滩', example: 'La playa está cerca del hotel.', exampleChinese: '海滩离酒店很近。', lemma: 'playa', partOfSpeech: 'noun', frequencyRank: 1648 },
      { spanish: 'dulce', chinese: '甜的；甜食', example: 'Este café está muy dulce.', exampleChinese: '这杯咖啡很甜。', lemma: 'dulce', partOfSpeech: 'adjective', frequencyRank: 1674 },
      { spanish: 'bebé', chinese: '婴儿', example: 'El bebé está dormido.', exampleChinese: '婴儿睡着了。', lemma: 'bebé', partOfSpeech: 'noun', frequencyRank: 1714 },
      { spanish: 'frío', chinese: '冷；寒冷的', example: 'El agua está fría, pero el aire está frío también.', exampleChinese: '水很凉，空气也很冷。', lemma: 'frío', partOfSpeech: 'adjective', frequencyRank: 1729 },
    ],
  },
  {
    id: 'expansion-a2-places-information-004', level: 'A2', scene: '城市', title: '地点、信息与出行',
    description: '理解地点说明、媒体信息和旅行环境',
    frameworkReference: A1_A2_PCIC,
    words: [
      { spanish: 'compañía', chinese: '公司；陪伴', example: 'Trabajo en una compañía pequeña.', exampleChinese: '我在一家小公司工作。', lemma: 'compañía', partOfSpeech: 'noun', frequencyRank: 705 },
      { spanish: 'interior', chinese: '内部；室内', example: 'El interior del edificio es moderno.', exampleChinese: '这栋楼的内部很现代。', lemma: 'interior', partOfSpeech: 'noun', frequencyRank: 709 },
      { spanish: 'nota', chinese: '笔记；分数；便条', example: 'Dejo una nota en la mesa.', exampleChinese: '我在桌上留了一张便条。', lemma: 'nota', partOfSpeech: 'noun', frequencyRank: 712 },
      { spanish: 'autor', chinese: '作者', example: 'El autor presenta su nuevo libro.', exampleChinese: '作者介绍他的新书。', lemma: 'autor', partOfSpeech: 'noun', frequencyRank: 737 },
      { spanish: 'puerto', chinese: '港口', example: 'El barco sale del puerto.', exampleChinese: '船从港口出发。', lemma: 'puerto', partOfSpeech: 'noun', frequencyRank: 776 },
      { spanish: 'departamento', chinese: '部门；公寓', example: 'Pregunta en el departamento de información.', exampleChinese: '去信息部门询问。', lemma: 'departamento', partOfSpeech: 'noun', frequencyRank: 805 },
      { spanish: 'mitad', chinese: '一半；中间', example: 'Solo necesito la mitad.', exampleChinese: '我只需要一半。', lemma: 'mitad', partOfSpeech: 'noun', frequencyRank: 809 },
      { spanish: 'radio', chinese: '收音机；广播', example: 'Escucho las noticias en la radio.', exampleChinese: '我通过广播听新闻。', lemma: 'radio', partOfSpeech: 'noun', frequencyRank: 833 },
      { spanish: 'llamada', chinese: '电话；呼叫', example: 'Espero una llamada esta tarde.', exampleChinese: '我今天下午在等一个电话。', lemma: 'llamada', partOfSpeech: 'noun', frequencyRank: 865 },
      { spanish: 'área', chinese: '区域；领域', example: 'Esta área es solo para clientes.', exampleChinese: '这个区域仅供顾客使用。', lemma: 'área', partOfSpeech: 'noun', frequencyRank: 883 },
      { spanish: 'vía', chinese: '道路；途径', example: 'La vía está cerrada hoy.', exampleChinese: '这条道路今天关闭。', lemma: 'vía', partOfSpeech: 'noun', frequencyRank: 905 },
      { spanish: 'isla', chinese: '岛；岛屿', example: 'La isla tiene un aeropuerto pequeño.', exampleChinese: '岛上有一座小机场。', lemma: 'isla', partOfSpeech: 'noun', frequencyRank: 939 },
    ],
  },
  {
    id: 'expansion-a2-shopping-work-004', level: 'A2', scene: '购物', title: '消费、工作与日常事务',
    description: '购物付款、拜访和处理基础工作信息',
    frameworkReference: A1_A2_PCIC,
    words: [
      { spanish: 'peso', chinese: '重量；比索', example: 'El peso de la maleta es correcto.', exampleChinese: '行李的重量符合要求。', lemma: 'peso', partOfSpeech: 'noun', frequencyRank: 998 },
      { spanish: 'asunto', chinese: '事情；事务', example: 'Necesito hablar de un asunto importante.', exampleChinese: '我需要谈一件重要的事。', lemma: 'asunto', partOfSpeech: 'noun', frequencyRank: 1011 },
      { spanish: 'cuarto', chinese: '房间；第四', example: 'El cuarto tiene una cama grande.', exampleChinese: '房间里有一张大床。', lemma: 'cuarto', partOfSpeech: 'noun', frequencyRank: 1030 },
      { spanish: 'negocio', chinese: '生意；商店', example: 'El negocio abre a las nueve.', exampleChinese: '商店九点开门。', lemma: 'negocio', partOfSpeech: 'noun', frequencyRank: 1039 },
      { spanish: 'suelo', chinese: '地面；土壤', example: 'La bolsa está en el suelo.', exampleChinese: '袋子在地上。', lemma: 'suelo', partOfSpeech: 'noun', frequencyRank: 1046 },
      { spanish: 'visita', chinese: '拜访；参观', example: 'La visita dura una hora.', exampleChinese: '参观持续一个小时。', lemma: 'visita', partOfSpeech: 'noun', frequencyRank: 1049 },
      { spanish: 'ambiente', chinese: '环境；气氛', example: 'El restaurante tiene buen ambiente.', exampleChinese: '这家餐厅气氛很好。', lemma: 'ambiente', partOfSpeech: 'noun', frequencyRank: 1050 },
      { spanish: 'pago', chinese: '付款；报酬', example: 'El pago se hace con tarjeta.', exampleChinese: '用银行卡付款。', lemma: 'pago', partOfSpeech: 'noun', frequencyRank: 1061 },
      { spanish: 'cuidado', chinese: '小心；照顾', example: 'Ten cuidado con el suelo mojado.', exampleChinese: '小心湿滑的地面。', lemma: 'cuidado', partOfSpeech: 'noun', frequencyRank: 1081 },
      { spanish: 'deseo', chinese: '愿望；欲望', example: 'Mi deseo es viajar más.', exampleChinese: '我的愿望是多旅行。', lemma: 'deseo', partOfSpeech: 'noun', frequencyRank: 1082 },
      { spanish: 'informe', chinese: '报告', example: 'El informe está listo.', exampleChinese: '报告已经准备好了。', lemma: 'informe', partOfSpeech: 'noun', frequencyRank: 1090 },
      { spanish: 'venta', chinese: '销售；出售', example: 'La entrada está a la venta.', exampleChinese: '门票正在出售。', lemma: 'venta', partOfSpeech: 'noun', frequencyRank: 1104 },
    ],
  },
  {
    id: 'expansion-b1-work-society-004', level: 'B1', scene: '工作', title: '工作沟通与社会生活',
    description: '阅读材料、衡量风险并讨论共同事务',
    frameworkReference: B1_B2_PCIC,
    words: [
      { spanish: 'material', chinese: '材料；资料', example: 'El material del curso está en línea.', exampleChinese: '课程资料在线上。', lemma: 'material', partOfSpeech: 'noun', frequencyRank: 1093 },
      { spanish: 'revista', chinese: '杂志', example: 'La revista publica una entrevista.', exampleChinese: '杂志刊登了一篇采访。', lemma: 'revista', partOfSpeech: 'noun', frequencyRank: 1125 },
      { spanish: 'distancia', chinese: '距离', example: 'La distancia entre las oficinas es corta.', exampleChinese: '两间办公室之间的距离很短。', lemma: 'distancia', partOfSpeech: 'noun', frequencyRank: 1138 },
      { spanish: 'riesgo', chinese: '风险', example: 'Debemos reducir el riesgo.', exampleChinese: '我们必须降低风险。', lemma: 'riesgo', partOfSpeech: 'noun', frequencyRank: 1155 },
      { spanish: 'silencio', chinese: '安静；沉默', example: 'Necesito silencio para trabajar.', exampleChinese: '我工作时需要安静。', lemma: 'silencio', partOfSpeech: 'noun', frequencyRank: 1158 },
      { spanish: 'temporada', chinese: '季节；一季；时期', example: 'La temporada alta empieza en junio.', exampleChinese: '旺季六月开始。', lemma: 'temporada', partOfSpeech: 'noun', frequencyRank: 1159 },
      { spanish: 'comercio', chinese: '商业；商店', example: 'El comercio local crea empleo.', exampleChinese: '本地商业创造就业。', lemma: 'comercio', partOfSpeech: 'noun', frequencyRank: 1163 },
      { spanish: 'daño', chinese: '损害；伤害', example: 'El agua causó daño al edificio.', exampleChinese: '水对建筑造成了损害。', lemma: 'daño', partOfSpeech: 'noun', frequencyRank: 1164 },
      { spanish: 'esfuerzo', chinese: '努力', example: 'El proyecto requiere mucho esfuerzo.', exampleChinese: '这个项目需要很多努力。', lemma: 'esfuerzo', partOfSpeech: 'noun', frequencyRank: 1167 },
      { spanish: 'contacto', chinese: '联系；接触', example: 'Mantengo contacto con el cliente.', exampleChinese: '我与客户保持联系。', lemma: 'contacto', partOfSpeech: 'noun', frequencyRank: 1191 },
      { spanish: 'verde', chinese: '绿色的；绿色', example: 'La línea verde llega al centro.', exampleChinese: '绿线到达市中心。', lemma: 'verde', partOfSpeech: 'adjective', frequencyRank: 1208 },
      { spanish: 'esperanza', chinese: '希望', example: 'Todavía existe esperanza de acuerdo.', exampleChinese: '达成协议仍有希望。', lemma: 'esperanza', partOfSpeech: 'noun', frequencyRank: 1213 },
    ],
  },
  {
    id: 'expansion-b1-health-community-004', level: 'B1', scene: '健康', title: '健康、环境与公共生活',
    description: '描述身体、医疗、社区环境和生活事件',
    frameworkReference: B1_B2_PCIC,
    words: [
      { spanish: 'diseño', chinese: '设计', example: 'El diseño facilita el uso diario.', exampleChinese: '这个设计方便日常使用。', lemma: 'diseño', partOfSpeech: 'noun', frequencyRank: 1265 },
      { spanish: 'expresión', chinese: '表达；表情', example: 'Su expresión muestra preocupación.', exampleChinese: '他的表情显得很担心。', lemma: 'expresión', partOfSpeech: 'noun', frequencyRank: 1288 },
      { spanish: 'maestro', chinese: '教师；大师', example: 'El maestro explica la tarea.', exampleChinese: '老师讲解作业。', lemma: 'maestro', partOfSpeech: 'noun', frequencyRank: 1296 },
      { spanish: 'enfermedad', chinese: '疾病', example: 'La enfermedad necesita tratamiento.', exampleChinese: '这种疾病需要治疗。', lemma: 'enfermedad', partOfSpeech: 'noun', frequencyRank: 1311 },
      { spanish: 'matrimonio', chinese: '婚姻；夫妻', example: 'El matrimonio vive en este barrio.', exampleChinese: '这对夫妻住在这个街区。', lemma: 'matrimonio', partOfSpeech: 'noun', frequencyRank: 1322 },
      { spanish: 'presión', chinese: '压力；血压', example: 'El médico controla la presión.', exampleChinese: '医生检查血压。', lemma: 'presión', partOfSpeech: 'noun', frequencyRank: 1329 },
      { spanish: 'operación', chinese: '手术；操作', example: 'La operación salió bien.', exampleChinese: '手术进行得很顺利。', lemma: 'operación', partOfSpeech: 'noun', frequencyRank: 1355 },
      { spanish: 'compra', chinese: '购买；采购', example: 'Guarda el recibo de la compra.', exampleChinese: '保留购物小票。', lemma: 'compra', partOfSpeech: 'noun', frequencyRank: 1368 },
      { spanish: 'piel', chinese: '皮肤', example: 'Esta crema protege la piel.', exampleChinese: '这种乳霜保护皮肤。', lemma: 'piel', partOfSpeech: 'noun', frequencyRank: 1389 },
      { spanish: 'velocidad', chinese: '速度', example: 'Reduce la velocidad cerca del colegio.', exampleChinese: '学校附近请减速。', lemma: 'velocidad', partOfSpeech: 'noun', frequencyRank: 1431 },
      { spanish: 'ejercicio', chinese: '锻炼；练习', example: 'El ejercicio diario mejora la salud.', exampleChinese: '每日锻炼有益健康。', lemma: 'ejercicio', partOfSpeech: 'noun', frequencyRank: 1478 },
      { spanish: 'basura', chinese: '垃圾', example: 'Separa la basura en casa.', exampleChinese: '在家里分类垃圾。', lemma: 'basura', partOfSpeech: 'noun', frequencyRank: 1563 },
    ],
  },
]
