import type { ExpansionDeck } from './lexiconExpansion'

const A1_A2_PCIC = 'https://cvc.cervantes.es/ensenanza/biblioteca_ele/plan_curricular/niveles/09_nociones_especificas_inventario_a1-a2.htm'
const B1_B2_PCIC = 'https://cvc.cervantes.es/ensenanza/biblioteca_ele/plan_curricular/niveles/09_nociones_especificas_inventario_b1-b2.htm'

// Production batch 009: 96 canonical targets prioritising practical A2 and broad B1–B2 coverage.
export const expansionBatch009: ExpansionDeck[] = [
  {
    id: 'expansion-a2-tools-services-009', level: 'A2', scene: '科技', title: '工具、设备与日常服务',
    description: '描述常用设备、信息载体和办理服务时遇到的物品',
    frameworkReference: A1_A2_PCIC,
    words: [
      { spanish: 'tamaño', chinese: '尺寸；大小', example: 'Necesito otro tamaño de camisa.', exampleChinese: '我需要另一个尺码的衬衫。', lemma: 'tamaño', partOfSpeech: 'noun', frequencyRank: 1396 },
      { spanish: 'madera', chinese: '木材；木头', example: 'La mesa es de madera.', exampleChinese: '这张桌子是木制的。', lemma: 'madera', partOfSpeech: 'noun', frequencyRank: 1780 },
      { spanish: 'móvil', chinese: '手机；移动的', example: 'He dejado el móvil en casa.', exampleChinese: '我把手机落在家里了。', lemma: 'móvil', partOfSpeech: 'noun', frequencyRank: 1824 },
      { spanish: 'moneda', chinese: '硬币；货币', example: 'La máquina acepta esta moneda.', exampleChinese: '机器接受这枚硬币。', lemma: 'moneda', partOfSpeech: 'noun', frequencyRank: 2175 },
      { spanish: 'herramienta', chinese: '工具', example: 'Esta herramienta sirve para cortar.', exampleChinese: '这个工具用来切割。', lemma: 'herramienta', partOfSpeech: 'noun', frequencyRank: 2348 },
      { spanish: 'consulta', chinese: '咨询；诊室；查询', example: 'La consulta empieza a las diez.', exampleChinese: '问诊十点开始。', lemma: 'consulta', partOfSpeech: 'noun', frequencyRank: 2388 },
      { spanish: 'copia', chinese: '副本；复制件', example: 'Guarda una copia del documento.', exampleChinese: '保存一份文件副本。', lemma: 'copia', partOfSpeech: 'noun', frequencyRank: 2817 },
      { spanish: 'anuncio', chinese: '广告；公告', example: 'El anuncio aparece en la pantalla.', exampleChinese: '公告显示在屏幕上。', lemma: 'anuncio', partOfSpeech: 'noun', frequencyRank: 2860 },
      { spanish: 'aparato', chinese: '设备；器械', example: 'Este aparato mide la temperatura.', exampleChinese: '这台设备测量温度。', lemma: 'aparato', partOfSpeech: 'noun', frequencyRank: 3895 },
      { spanish: 'dosis', chinese: '剂量；一剂', example: 'Tome una dosis después de comer.', exampleChinese: '饭后服用一剂。', lemma: 'dosis', partOfSpeech: 'noun', frequencyRank: 4328 },
      { spanish: 'certificado', chinese: '证明；证书', example: 'Necesito un certificado de residencia.', exampleChinese: '我需要一份居住证明。', lemma: 'certificado', partOfSpeech: 'noun', frequencyRank: 4483 },
      { spanish: 'dispositivo', chinese: '设备；装置', example: 'El dispositivo necesita batería.', exampleChinese: '这个设备需要电池。', lemma: 'dispositivo', partOfSpeech: 'noun', frequencyRank: 4702 },
    ],
  },
  {
    id: 'expansion-a2-health-home-009', level: 'A2', scene: '健康', title: '健康、居家与个人手续',
    description: '处理常见健康状况、家庭物品和个人财务事项',
    frameworkReference: A1_A2_PCIC,
    words: [
      { spanish: 'adolescente', chinese: '青少年', example: 'El adolescente necesita dormir más.', exampleChinese: '青少年需要更多睡眠。', lemma: 'adolescente', partOfSpeech: 'noun', frequencyRank: 4297 },
      { spanish: 'plástico', chinese: '塑料', example: 'Esta botella es de plástico.', exampleChinese: '这个瓶子是塑料制的。', lemma: 'plástico', partOfSpeech: 'noun', frequencyRank: 4539 },
      { spanish: 'remedio', chinese: '药物；解决办法', example: 'Este remedio calma la tos.', exampleChinese: '这种药能缓解咳嗽。', lemma: 'remedio', partOfSpeech: 'noun', frequencyRank: 4748 },
      { spanish: 'garganta', chinese: '喉咙', example: 'Me duele la garganta.', exampleChinese: '我喉咙疼。', lemma: 'garganta', partOfSpeech: 'noun', frequencyRank: 4905 },
      { spanish: 'préstamo', chinese: '贷款；借款', example: 'El banco aprobó el préstamo.', exampleChinese: '银行批准了贷款。', lemma: 'préstamo', partOfSpeech: 'noun', frequencyRank: 4934 },
      { spanish: 'estrés', chinese: '压力；应激', example: 'El descanso reduce el estrés.', exampleChinese: '休息能减轻压力。', lemma: 'estrés', partOfSpeech: 'noun', frequencyRank: 5001 },
      { spanish: 'horno', chinese: '烤箱；炉', example: 'El pan está en el horno.', exampleChinese: '面包在烤箱里。', lemma: 'horno', partOfSpeech: 'noun', frequencyRank: 5214 },
      { spanish: 'ordenador', chinese: '电脑', example: 'Trabajo con el ordenador portátil.', exampleChinese: '我用笔记本电脑工作。', lemma: 'ordenador', partOfSpeech: 'noun', frequencyRank: 5415 },
      { spanish: 'pensión', chinese: '养老金；小旅馆', example: 'Recibe una pensión cada mes.', exampleChinese: '他每月领取养老金。', lemma: 'pensión', partOfSpeech: 'noun', frequencyRank: 5418 },
      { spanish: 'escalera', chinese: '楼梯；梯子', example: 'Subimos por la escalera.', exampleChinese: '我们走楼梯上去。', lemma: 'escalera', partOfSpeech: 'noun', frequencyRank: 5502 },
      { spanish: 'urgencia', chinese: '紧急情况；急诊', example: 'La urgencia requiere atención inmediata.', exampleChinese: '紧急情况需要立即处理。', lemma: 'urgencia', partOfSpeech: 'noun', frequencyRank: 5573 },
      { spanish: 'teclado', chinese: '键盘', example: 'El teclado tiene una tecla rota.', exampleChinese: '键盘有一个按键坏了。', lemma: 'teclado', partOfSpeech: 'noun', frequencyRank: 5897 },
    ],
  },
  {
    id: 'expansion-b1-quantity-organisation-009', level: 'B1', scene: '工作', title: '数量、结构与工作安排',
    description: '说明整体与部分、任务顺序和可衡量的信息',
    frameworkReference: B1_B2_PCIC,
    words: [
      { spanish: 'parte', chinese: '部分；一方', example: 'Esta parte del informe está clara.', exampleChinese: '报告的这一部分很清楚。', lemma: 'parte', partOfSpeech: 'noun', frequencyRank: 72 },
      { spanish: 'orden', chinese: '顺序；秩序；命令', example: 'Sigue el orden de la lista.', exampleChinese: '请按照清单顺序进行。', lemma: 'orden', partOfSpeech: 'noun', frequencyRank: 409 },
      { spanish: 'lista', chinese: '清单；名单', example: 'Revisa la lista antes de salir.', exampleChinese: '出发前检查清单。', lemma: 'lista', partOfSpeech: 'noun', frequencyRank: 419 },
      { spanish: 'conjunto', chinese: '整体；集合；一套', example: 'El conjunto de datos está completo.', exampleChinese: '这组数据是完整的。', lemma: 'conjunto', partOfSpeech: 'noun', frequencyRank: 1029 },
      { spanish: 'posibilidad', chinese: '可能性；机会', example: 'Existe la posibilidad de cambiar la fecha.', exampleChinese: '日期有可能更改。', lemma: 'posibilidad', partOfSpeech: 'noun', frequencyRank: 1043 },
      { spanish: 'motivo', chinese: '原因；动机', example: 'Explique el motivo de la solicitud.', exampleChinese: '请说明申请原因。', lemma: 'motivo', partOfSpeech: 'noun', frequencyRank: 1145 },
      { spanish: 'referencia', chinese: '参考；编号；推荐人', example: 'Anote el número de referencia.', exampleChinese: '请记下参考编号。', lemma: 'referencia', partOfSpeech: 'noun', frequencyRank: 1151 },
      { spanish: 'función', chinese: '功能；职能；函数', example: 'Cada botón tiene una función distinta.', exampleChinese: '每个按钮有不同功能。', lemma: 'función', partOfSpeech: 'noun', frequencyRank: 1196 },
      { spanish: 'elección', chinese: '选择；选举', example: 'La elección depende del presupuesto.', exampleChinese: '选择取决于预算。', lemma: 'elección', partOfSpeech: 'noun', frequencyRank: 1242 },
      { spanish: 'altura', chinese: '高度；身高', example: 'La mesa tiene la altura adecuada.', exampleChinese: '桌子的高度合适。', lemma: 'altura', partOfSpeech: 'noun', frequencyRank: 1435 },
      { spanish: 'promedio', chinese: '平均值；平均的', example: 'El promedio mensual ha aumentado.', exampleChinese: '月平均值上升了。', lemma: 'promedio', partOfSpeech: 'noun', frequencyRank: 1650 },
      { spanish: 'volumen', chinese: '音量；体积；卷', example: 'Baja el volumen del teléfono.', exampleChinese: '把手机音量调低。', lemma: 'volumen', partOfSpeech: 'noun', frequencyRank: 2230 },
    ],
  },
  {
    id: 'expansion-b1-public-society-009', level: 'B1', scene: '社会', title: '社会参与与公共制度',
    description: '理解公共决策、安全保护和社会变化',
    frameworkReference: B1_B2_PCIC,
    words: [
      { spanish: 'mayoría', chinese: '大多数；多数', example: 'La mayoría apoyó la propuesta.', exampleChinese: '大多数人支持这项提议。', lemma: 'mayoría', partOfSpeech: 'noun', frequencyRank: 362 },
      { spanish: 'crisis', chinese: '危机', example: 'La crisis afectó a muchas familias.', exampleChinese: '危机影响了许多家庭。', lemma: 'crisis', partOfSpeech: 'noun', frequencyRank: 843 },
      { spanish: 'participación', chinese: '参与；参会率', example: 'La participación ciudadana es importante.', exampleChinese: '公民参与很重要。', lemma: 'participación', partOfSpeech: 'noun', frequencyRank: 867 },
      { spanish: 'violencia', chinese: '暴力', example: 'La campaña rechaza la violencia.', exampleChinese: '这项活动反对暴力。', lemma: 'violencia', partOfSpeech: 'noun', frequencyRank: 870 },
      { spanish: 'constitución', chinese: '宪法；构成', example: 'La constitución reconoce esos derechos.', exampleChinese: '宪法承认这些权利。', lemma: 'constitución', partOfSpeech: 'noun', frequencyRank: 932 },
      { spanish: 'juicio', chinese: '审判；判断', example: 'El juicio comenzará el lunes.', exampleChinese: '审判将于周一开始。', lemma: 'juicio', partOfSpeech: 'noun', frequencyRank: 994 },
      { spanish: 'democracia', chinese: '民主；民主制度', example: 'La democracia necesita participación.', exampleChinese: '民主制度需要公众参与。', lemma: 'democracia', partOfSpeech: 'noun', frequencyRank: 1032 },
      { spanish: 'protección', chinese: '保护；防护', example: 'La ley ofrece protección al consumidor.', exampleChinese: '法律为消费者提供保护。', lemma: 'protección', partOfSpeech: 'noun', frequencyRank: 1064 },
      { spanish: 'territorio', chinese: '领土；地区', example: 'El servicio cubre todo el territorio.', exampleChinese: '这项服务覆盖整个地区。', lemma: 'territorio', partOfSpeech: 'noun', frequencyRank: 1127 },
      { spanish: 'aumento', chinese: '增加；上涨', example: 'El aumento de precios preocupa a todos.', exampleChinese: '价格上涨让大家担忧。', lemma: 'aumento', partOfSpeech: 'noun', frequencyRank: 1132 },
      { spanish: 'ciencia', chinese: '科学', example: 'La ciencia necesita pruebas claras.', exampleChinese: '科学需要明确证据。', lemma: 'ciencia', partOfSpeech: 'noun', frequencyRank: 1135 },
      { spanish: 'debate', chinese: '辩论；讨论', example: 'El debate continúa esta tarde.', exampleChinese: '讨论今天下午继续。', lemma: 'debate', partOfSpeech: 'noun', frequencyRank: 1263 },
    ],
  },
  {
    id: 'expansion-b1-analysis-thinking-009', level: 'B1', scene: '学习', title: '分析过程与表达意图',
    description: '组织概念、解释变化并表达想法背后的意图',
    frameworkReference: B1_B2_PCIC,
    words: [
      { spanish: 'proceso', chinese: '过程；流程', example: 'El proceso tarda varios días.', exampleChinese: '这个流程需要几天。', lemma: 'proceso', partOfSpeech: 'noun', frequencyRank: 394 },
      { spanish: 'sentido', chinese: '意义；方向；感觉', example: 'La frase cambia de sentido.', exampleChinese: '这句话的意思变了。', lemma: 'sentido', partOfSpeech: 'noun', frequencyRank: 395 },
      { spanish: 'efecto', chinese: '效果；影响', example: 'La medida tuvo un efecto positivo.', exampleChinese: '这项措施产生了积极效果。', lemma: 'efecto', partOfSpeech: 'noun', frequencyRank: 937 },
      { spanish: 'memoria', chinese: '记忆；内存；报告', example: 'La práctica mejora la memoria.', exampleChinese: '练习能改善记忆。', lemma: 'memoria', partOfSpeech: 'noun', frequencyRank: 1144 },
      { spanish: 'crecimiento', chinese: '增长；成长', example: 'El informe confirma el crecimiento del empleo.', exampleChinese: '报告确认就业增长。', lemma: 'crecimiento', partOfSpeech: 'noun', frequencyRank: 1193 },
      { spanish: 'estructura', chinese: '结构；构造', example: 'El texto tiene una estructura sencilla.', exampleChinese: '文章结构简单。', lemma: 'estructura', partOfSpeech: 'noun', frequencyRank: 1313 },
      { spanish: 'grado', chinese: '程度；学位；度数', example: 'El grado de dificultad es medio.', exampleChinese: '难度为中等。', lemma: 'grado', partOfSpeech: 'noun', frequencyRank: 1317 },
      { spanish: 'teoría', chinese: '理论；推测', example: 'La teoría debe explicar los datos.', exampleChinese: '理论应当解释数据。', lemma: 'teoría', partOfSpeech: 'noun', frequencyRank: 1363 },
      { spanish: 'concepto', chinese: '概念', example: 'El profesor explica el concepto con ejemplos.', exampleChinese: '老师用例子解释这个概念。', lemma: 'concepto', partOfSpeech: 'noun', frequencyRank: 1369 },
      { spanish: 'gestión', chinese: '管理；办理', example: 'La gestión se puede hacer por internet.', exampleChinese: '这项办理可以在网上完成。', lemma: 'gestión', partOfSpeech: 'noun', frequencyRank: 1451 },
      { spanish: 'contexto', chinese: '语境；背景', example: 'La palabra cambia según el contexto.', exampleChinese: '这个词会随语境变化。', lemma: 'contexto', partOfSpeech: 'noun', frequencyRank: 1472 },
      { spanish: 'intención', chinese: '意图；打算', example: 'Mi intención es ayudar al equipo.', exampleChinese: '我的意图是帮助团队。', lemma: 'intención', partOfSpeech: 'noun', frequencyRank: 1512 },
    ],
  },
  {
    id: 'expansion-b2-culture-power-009', level: 'B2', scene: '社会', title: '文化、权力与社会差异',
    description: '讨论制度力量、文化身份和社会不平等',
    frameworkReference: B1_B2_PCIC,
    words: [
      { spanish: 'oposición', chinese: '反对；反对派；对立', example: 'La propuesta encontró mucha oposición.', exampleChinese: '这项提议遭到强烈反对。', lemma: 'oposición', partOfSpeech: 'noun', frequencyRank: 1300 },
      { spanish: 'autoridad', chinese: '权威；当局；权限', example: 'La autoridad publicó una nueva norma.', exampleChinese: '主管部门发布了新规定。', lemma: 'autoridad', partOfSpeech: 'noun', frequencyRank: 1537 },
      { spanish: 'influencia', chinese: '影响；影响力', example: 'La publicidad tiene mucha influencia.', exampleChinese: '广告具有很大影响力。', lemma: 'influencia', partOfSpeech: 'noun', frequencyRank: 1549 },
      { spanish: 'lenguaje', chinese: '语言；表达方式', example: 'El informe usa un lenguaje técnico.', exampleChinese: '报告使用技术语言。', lemma: 'lenguaje', partOfSpeech: 'noun', frequencyRank: 1551 },
      { spanish: 'literatura', chinese: '文学；文献', example: 'La literatura refleja su época.', exampleChinese: '文学反映其时代。', lemma: 'literatura', partOfSpeech: 'noun', frequencyRank: 1552 },
      { spanish: 'pobreza', chinese: '贫困', example: 'El programa busca reducir la pobreza.', exampleChinese: '该计划旨在减少贫困。', lemma: 'pobreza', partOfSpeech: 'noun', frequencyRank: 1586 },
      { spanish: 'distribución', chinese: '分配；分布；配送', example: 'La distribución de recursos no es igual.', exampleChinese: '资源分配并不均等。', lemma: 'distribución', partOfSpeech: 'noun', frequencyRank: 1634 },
      { spanish: 'identidad', chinese: '身份；认同', example: 'La lengua forma parte de la identidad.', exampleChinese: '语言是身份认同的一部分。', lemma: 'identidad', partOfSpeech: 'noun', frequencyRank: 1639 },
      { spanish: 'voluntad', chinese: '意愿；意志', example: 'Existe voluntad de llegar a un acuerdo.', exampleChinese: '各方有达成协议的意愿。', lemma: 'voluntad', partOfSpeech: 'noun', frequencyRank: 1662 },
      { spanish: 'delito', chinese: '犯罪；罪行', example: 'La policía investiga el delito.', exampleChinese: '警方正在调查这起犯罪。', lemma: 'delito', partOfSpeech: 'noun', frequencyRank: 1766 },
      { spanish: 'religión', chinese: '宗教', example: 'La ley protege la libertad de religión.', exampleChinese: '法律保护宗教自由。', lemma: 'religión', partOfSpeech: 'noun', frequencyRank: 1879 },
      { spanish: 'víctima', chinese: '受害者', example: 'La víctima recibió apoyo psicológico.', exampleChinese: '受害者获得了心理支持。', lemma: 'víctima', partOfSpeech: 'noun', frequencyRank: 2002 },
    ],
  },
  {
    id: 'expansion-b2-analysis-relations-009', level: 'B2', scene: '学习', title: '论证关系与分析视角',
    description: '概括材料、建立联系并比较不同分析角度',
    frameworkReference: B1_B2_PCIC,
    words: [
      { spanish: 'representación', chinese: '代表；呈现；表征', example: 'El gráfico ofrece una representación visual.', exampleChinese: '图表提供了一种视觉呈现。', lemma: 'representación', partOfSpeech: 'noun', frequencyRank: 2046 },
      { spanish: 'resumen', chinese: '摘要；总结', example: 'El resumen recoge las ideas principales.', exampleChinese: '摘要概括了主要观点。', lemma: 'resumen', partOfSpeech: 'noun', frequencyRank: 2048 },
      { spanish: 'ámbito', chinese: '领域；范围', example: 'La medida se aplica en el ámbito laboral.', exampleChinese: '这项措施适用于劳动领域。', lemma: 'ámbito', partOfSpeech: 'noun', frequencyRank: 2231 },
      { spanish: 'amenaza', chinese: '威胁', example: 'El cambio climático es una amenaza global.', exampleChinese: '气候变化是全球威胁。', lemma: 'amenaza', partOfSpeech: 'noun', frequencyRank: 2233 },
      { spanish: 'conexión', chinese: '连接；联系', example: 'El estudio muestra una conexión clara.', exampleChinese: '研究显示出明确联系。', lemma: 'conexión', partOfSpeech: 'noun', frequencyRank: 2243 },
      { spanish: 'fase', chinese: '阶段；时期', example: 'El proyecto entra en una nueva fase.', exampleChinese: '项目进入新阶段。', lemma: 'fase', partOfSpeech: 'noun', frequencyRank: 2293 },
      { spanish: 'perspectiva', chinese: '视角；前景', example: 'Analicemos el problema desde otra perspectiva.', exampleChinese: '让我们从另一个视角分析问题。', lemma: 'perspectiva', partOfSpeech: 'noun', frequencyRank: 2358 },
      { spanish: 'alternativa', chinese: '替代方案；选择', example: 'Necesitamos una alternativa más barata.', exampleChinese: '我们需要更便宜的替代方案。', lemma: 'alternativa', partOfSpeech: 'noun', frequencyRank: 2374 },
      { spanish: 'dignidad', chinese: '尊严；庄重', example: 'Toda persona merece vivir con dignidad.', exampleChinese: '每个人都应有尊严地生活。', lemma: 'dignidad', partOfSpeech: 'noun', frequencyRank: 2395 },
      { spanish: 'ritmo', chinese: '节奏；速度', example: 'La economía crece a un ritmo moderado.', exampleChinese: '经济以温和速度增长。', lemma: 'ritmo', partOfSpeech: 'noun', frequencyRank: 2423 },
      { spanish: 'variedad', chinese: '多样性；品种', example: 'El mercado ofrece una gran variedad.', exampleChinese: '市场提供丰富的品种。', lemma: 'variedad', partOfSpeech: 'noun', frequencyRank: 2430 },
      { spanish: 'elemento', chinese: '要素；元素', example: 'La confianza es un elemento esencial.', exampleChinese: '信任是一个关键要素。', lemma: 'elemento', partOfSpeech: 'noun', frequencyRank: 2710 },
    ],
  },
  {
    id: 'expansion-b2-evaluation-009', level: 'B2', scene: '工作', title: '评估标准与复杂结果',
    description: '评价模式、依赖关系、质量和诊断结论',
    frameworkReference: B1_B2_PCIC,
    words: [
      { spanish: 'patrón', chinese: '模式；样式；雇主', example: 'Los datos muestran un patrón estable.', exampleChinese: '数据显示出稳定模式。', lemma: 'patrón', partOfSpeech: 'noun', frequencyRank: 3581 },
      { spanish: 'rechazo', chinese: '拒绝；排斥', example: 'El rechazo de la solicitud debe justificarse.', exampleChinese: '拒绝申请必须说明理由。', lemma: 'rechazo', partOfSpeech: 'noun', frequencyRank: 3654 },
      { spanish: 'adicional', chinese: '额外的；附加的', example: 'Necesitamos información adicional.', exampleChinese: '我们需要额外信息。', lemma: 'adicional', partOfSpeech: 'adjective', frequencyRank: 3753 },
      { spanish: 'apariencia', chinese: '外观；表象', example: 'La apariencia puede resultar engañosa.', exampleChinese: '表象可能具有欺骗性。', lemma: 'apariencia', partOfSpeech: 'noun', frequencyRank: 4054 },
      { spanish: 'integral', chinese: '全面的；整体的', example: 'El problema requiere una solución integral.', exampleChinese: '这个问题需要全面解决方案。', lemma: 'integral', partOfSpeech: 'adjective', frequencyRank: 4083 },
      { spanish: 'intensidad', chinese: '强度；程度', example: 'La intensidad del ruido ha bajado.', exampleChinese: '噪声强度已经下降。', lemma: 'intensidad', partOfSpeech: 'noun', frequencyRank: 4436 },
      { spanish: 'dependencia', chinese: '依赖；隶属机构', example: 'La dependencia energética aumenta el riesgo.', exampleChinese: '能源依赖增加风险。', lemma: 'dependencia', partOfSpeech: 'noun', frequencyRank: 4500 },
      { spanish: 'gravedad', chinese: '严重性；重力', example: 'El informe confirma la gravedad del problema.', exampleChinese: '报告确认了问题的严重性。', lemma: 'gravedad', partOfSpeech: 'noun', frequencyRank: 4513 },
      { spanish: 'reputación', chinese: '声誉；名声', example: 'La empresa protege su reputación.', exampleChinese: '公司维护自己的声誉。', lemma: 'reputación', partOfSpeech: 'noun', frequencyRank: 4749 },
      { spanish: 'diagnóstico', chinese: '诊断；判断', example: 'El diagnóstico se basa en varias pruebas.', exampleChinese: '诊断基于多项检查。', lemma: 'diagnóstico', partOfSpeech: 'noun', frequencyRank: 4781 },
      { spanish: 'aceptación', chinese: '接受；认可', example: 'La propuesta logró una amplia aceptación.', exampleChinese: '这项提议获得广泛认可。', lemma: 'aceptación', partOfSpeech: 'noun', frequencyRank: 4964 },
      { spanish: 'eficiencia', chinese: '效率；效能', example: 'La reforma mejoró la eficiencia del servicio.', exampleChinese: '改革提高了服务效率。', lemma: 'eficiencia', partOfSpeech: 'noun', frequencyRank: 5392 },
    ],
  },
]
