import type { ExpansionDeck } from './lexiconExpansion'

const A1_A2_PCIC = 'https://cvc.cervantes.es/ensenanza/biblioteca_ele/plan_curricular/niveles/09_nociones_especificas_inventario_a1-a2.htm'
const B1_B2_PCIC = 'https://cvc.cervantes.es/ensenanza/biblioteca_ele/plan_curricular/niveles/09_nociones_especificas_inventario_b1-b2.htm'
type ExpansionWord = ExpansionDeck['words'][number]
const w = (spanish: string, chinese: string, example: string, exampleChinese: string, partOfSpeech: ExpansionWord['partOfSpeech'], frequencyRank: number): ExpansionWord => ({ spanish, chinese, example, exampleChinese, lemma: spanish, partOfSpeech, frequencyRank })

// Production batch 016: 72 canonical targets covering everyday description,
// public services, culture, and social participation without inflection padding.
export const expansionBatch016: ExpansionDeck[] = [
  {
    id: 'expansion-a2-people-objects-016', level: 'A2', scene: '日常', title: '人物、物品与常见状态',
    description: '补充描述身边人物、物品和日常状态的高频词', frameworkReference: A1_A2_PCIC,
    words: [
      w('chico', '男孩；年轻人', 'El chico espera junto a la puerta.', '那个男孩在门边等候。', 'noun', 1235),
      w('copa', '杯；奖杯', 'Tomamos una copa de agua.', '我们喝了一杯水。', 'noun', 1238),
      w('triste', '难过的；悲伤的', 'Hoy se siente triste.', '他今天感到难过。', 'adjective', 1259),
      w('alguno', '某一个；有些', '¿Conoces alguno de estos lugares?', '这些地方里你认识哪一个吗？', 'pronoun', 1260),
      w('marco', '框架；边框', 'La foto tiene un marco blanco.', '这张照片有一个白色边框。', 'noun', 1297),
      w('escena', '场景；一幕', 'La última escena es muy breve.', '最后一幕很短。', 'noun', 1312),
      w('peligro', '危险', 'Hay peligro de caída.', '有跌落的危险。', 'noun', 1327),
      w('batalla', '战斗；较量', 'La batalla duró varias horas.', '战斗持续了几个小时。', 'noun', 1336),
      w('duro', '硬的；艰难的', 'El trabajo fue duro.', '这项工作很艰难。', 'adjective', 1341),
      w('evento', '活动；事件', 'El evento empieza a las seis.', '活动六点开始。', 'noun', 1344),
      w('intento', '尝试；企图', 'Este es mi segundo intento.', '这是我的第二次尝试。', 'noun', 1350),
      w('enorme', '巨大的', 'El edificio tiene una entrada enorme.', '这栋楼有一个巨大的入口。', 'adjective', 1375),
    ],
  },
  {
    id: 'expansion-a2-description-016', level: 'A2', scene: '基础', title: '位置、外观与日常表达',
    description: '表达位置、尺寸、外观和常见个人信息', frameworkReference: A1_A2_PCIC,
    words: [
      w('raro', '奇怪的；少见的', 'Oigo un ruido raro.', '我听到一个奇怪的声音。', 'adjective', 1393),
      w('quizá', '也许；可能', 'Quizá llegue más tarde.', '他也许会晚点到。', 'adverb', 1422),
      w('debajo', '在下面', 'La caja está debajo de la mesa.', '箱子在桌子下面。', 'adverb', 1442),
      w('antiguo', '古老的；以前的', 'Visitamos un barrio antiguo.', '我们参观了一个老街区。', 'adjective', 1467),
      w('carga', '负载；货物；充电量', 'La batería tiene poca carga.', '电池电量很少。', 'noun', 1469),
      w('objeto', '物品；对象', 'Encontré un objeto en el suelo.', '我在地上发现了一个物品。', 'noun', 1490),
      w('corto', '短的；简短的', 'El mensaje es corto y claro.', '这条消息简短清楚。', 'adjective', 1567),
      w('cuánto', '多少', '¿Cuánto cuesta el billete?', '这张票多少钱？', 'pronoun', 1568),
      w('papá', '爸爸', 'Mi papá cocina los domingos.', '我爸爸星期日做饭。', 'noun', 1615),
      w('mirada', '目光；眼神', 'Su mirada parece tranquila.', '他的目光看起来很平静。', 'noun', 1644),
      w('regreso', '返回；归来', 'El regreso será el lunes.', '返程是在星期一。', 'noun', 1700),
      w('bandera', '旗帜；国旗', 'La bandera está junto a la entrada.', '旗帜在入口旁边。', 'noun', 1758),
    ],
  },
  {
    id: 'expansion-b1-public-life-016', level: 'B1', scene: '社会', title: '公共生活与社会角色',
    description: '理解公共事件、社会角色和集体讨论中的常用词', frameworkReference: B1_B2_PCIC,
    words: [
      w('golpe', '打击；撞击', 'El sector recibió un golpe fuerte.', '这个行业受到沉重打击。', 'noun', 1316),
      w('directo', '直接的；直播的', 'Necesitamos un contacto directo.', '我们需要直接联系。', 'adjective', 1372),
      w('clave', '关键；密码；钥匙', 'La confianza es la clave del acuerdo.', '信任是协议的关键。', 'noun', 1401),
      w('demanda', '需求；诉讼', 'La demanda de vivienda ha aumentado.', '住房需求增加了。', 'noun', 1407),
      w('alcalde', '市长', 'El alcalde presentó el nuevo plan.', '市长介绍了新计划。', 'noun', 1434),
      w('candidato', '候选人', 'Cada candidato explicó su propuesta.', '每位候选人都解释了自己的提案。', 'noun', 1438),
      w('abogado', '律师', 'El abogado revisó el contrato.', '律师审查了合同。', 'noun', 1463),
      w('cárcel', '监狱', 'El juez ordenó su ingreso en la cárcel.', '法官下令将其收监。', 'noun', 1503),
      w('distrito', '区；行政区', 'El distrito ofrece nuevos servicios.', '这个区提供了新服务。', 'noun', 1507),
      w('familiar', '家庭的；熟悉的', 'El lugar resulta familiar.', '这个地方让人感到熟悉。', 'adjective', 1508),
      w('junta', '委员会；会议', 'La junta aprobó el presupuesto.', '委员会批准了预算。', 'noun', 1513),
      w('máximo', '最大值；最高的', 'El plazo máximo es de diez días.', '最长期限是十天。', 'adjective', 1517),
    ],
  },
  {
    id: 'expansion-b1-culture-structure-016', level: 'B1', scene: '学习', title: '结构、文化与表达',
    description: '说明目的、结构、文化内容和组织关系', frameworkReference: B1_B2_PCIC,
    words: [
      w('propósito', '目的；意图', 'El propósito del curso es practicar.', '课程的目的是练习。', 'noun', 1527),
      w('sede', '总部；举办地', 'La sede está en el centro.', '总部在市中心。', 'noun', 1532),
      w('cadena', '链条；连锁；频道', 'La empresa pertenece a una cadena hotelera.', '这家公司属于一家连锁酒店集团。', 'noun', 1539),
      w('búsqueda', '搜索；寻找', 'La búsqueda de empleo lleva tiempo.', '找工作需要时间。', 'noun', 1564),
      w('espíritu', '精神；心灵', 'El equipo mantiene un espíritu positivo.', '团队保持积极的精神。', 'noun', 1572),
      w('terreno', '地面；土地；领域', 'El terreno está mojado.', '地面是湿的。', 'noun', 1658),
      w('aspecto', '方面；外观', 'Debemos revisar cada aspecto del plan.', '我们必须检查计划的每个方面。', 'noun', 1667),
      w('comité', '委员会', 'El comité publicará su decisión.', '委员会将公布决定。', 'noun', 1670),
      w('novela', '小说', 'La novela cuenta una historia familiar.', '这部小说讲述了一个家庭故事。', 'noun', 1687),
      w('deporte', '运动；体育', 'El deporte mejora la salud.', '运动改善健康。', 'noun', 1767),
      w('disco', '唱片；圆盘；磁盘', 'Compró un disco de música española.', '他买了一张西班牙音乐唱片。', 'noun', 1768),
      w('escritor', '作家', 'El escritor presentó su nueva obra.', '作家介绍了自己的新作品。', 'noun', 1770),
    ],
  },
  {
    id: 'expansion-b2-institutions-016', level: 'B2', scene: '行政', title: '制度、法律与公共关系',
    description: '讨论法律事件、公共机构和社会责任', frameworkReference: B1_B2_PCIC,
    words: [
      w('asesinato', '谋杀；杀害', 'La policía investiga el asesinato.', '警方正在调查这起谋杀案。', 'noun', 1666),
      w('inmediatamente', '立即；马上', 'La norma entró en vigor inmediatamente.', '这项规定立即生效。', 'adverb', 1680),
      w('patria', '祖国；故土', 'Regresó a su patria después de muchos años.', '多年后他回到了祖国。', 'noun', 1739),
      w('aproximadamente', '大约', 'La reunión duró aproximadamente dos horas.', '会议持续了大约两个小时。', 'adverb', 1755),
      w('precisamente', '恰好；准确地说', 'Precisamente ese punto causó el conflicto.', '恰恰是那一点引发了冲突。', 'adverb', 1786),
      w('secreto', '秘密', 'El informe dejó de ser secreto.', '这份报告不再是秘密。', 'noun', 1793),
      w('comienzo', '开始；开端', 'El comienzo del debate fue tranquilo.', '辩论的开场很平静。', 'noun', 1805),
      w('crimen', '犯罪；罪行', 'El tribunal analizó las pruebas del crimen.', '法院分析了犯罪证据。', 'noun', 1807),
      w('sencillo', '简单的；朴素的', 'El procedimiento parece sencillo.', '这个流程看起来很简单。', 'adjective', 1916),
      w('comandante', '指挥官；司令', 'El comandante explicó la operación.', '指挥官解释了这次行动。', 'noun', 2014),
      w('mentira', '谎言；假话', 'La investigación reveló una mentira.', '调查揭露了一个谎言。', 'noun', 2037),
      w('década', '十年；年代', 'La ciudad cambió durante la última década.', '这座城市在过去十年中发生了变化。', 'noun', 2078),
    ],
  },
  {
    id: 'expansion-b2-society-culture-016', level: 'B2', scene: '社会', title: '社会、文化与复杂判断',
    description: '分析社会关系、文化现象和复杂情境', frameworkReference: B1_B2_PCIC,
    words: [
      w('enemigo', '敌人；对手', 'El miedo puede convertirse en enemigo del cambio.', '恐惧可能成为改变的敌人。', 'noun', 1848),
      w('foro', '论坛；讨论会', 'El foro reunió a expertos de varios países.', '论坛汇集了多个国家的专家。', 'noun', 1851),
      w('palacio', '宫殿；官邸', 'El palacio está abierto al público.', '宫殿向公众开放。', 'noun', 1872),
      w('estrella', '星星；明星', 'La actriz se convirtió en una estrella internacional.', '这位演员成为国际明星。', 'noun', 1896),
      w('guardia', '警卫；值班；警戒', 'La guardia controló el acceso al edificio.', '警卫控制了大楼入口。', 'noun', 1900),
      w('universo', '宇宙；整体世界', 'La novela crea un universo propio.', '这部小说创造了自己的世界。', 'noun', 1924),
      w('arma', '武器', 'La ley limita la posesión de un arma.', '法律限制持有武器。', 'noun', 1928),
      w('moda', '时尚；流行', 'La moda refleja cambios sociales.', '时尚反映社会变化。', 'noun', 1946),
      w('corriente', '潮流；水流；电流', 'La corriente de opinión cambió rápidamente.', '舆论潮流迅速改变。', 'noun', 1976),
      w('escala', '规模；比例；停靠', 'El problema existe a escala mundial.', '这个问题存在于全球范围。', 'noun', 1983),
      w('terrible', '可怕的；严重的', 'La región sufrió una crisis terrible.', '该地区经历了严重危机。', 'adjective', 1999),
      w('labor', '工作；任务；贡献', 'La labor del equipo recibió reconocimiento.', '团队的工作获得了认可。', 'noun', 2118),
    ],
  },
]
