import type { ExpansionDeck } from './lexiconExpansion'

const A1_A2_PCIC = 'https://cvc.cervantes.es/ensenanza/biblioteca_ele/plan_curricular/niveles/09_nociones_especificas_inventario_a1-a2.htm'
const B1_B2_PCIC = 'https://cvc.cervantes.es/ensenanza/biblioteca_ele/plan_curricular/niveles/09_nociones_especificas_inventario_b1-b2.htm'

// Production batch 006: 96 frequency-backed canonical targets covering
// concrete daily needs and the B1–B2 language needed to explain systems.
export const expansionBatch006: ExpansionDeck[] = [
  {
    id: 'expansion-a1-body-home-006', level: 'A1', scene: '健康', title: '身体与居住空间',
    description: '描述身体部位、家中位置和常见生活物品',
    frameworkReference: A1_A2_PCIC,
    words: [
      { spanish: 'luz', chinese: '光；灯', example: 'La luz del baño está encendida.', exampleChinese: '卫生间的灯亮着。', lemma: 'luz', partOfSpeech: 'noun', frequencyRank: 469 },
      { spanish: 'sangre', chinese: '血；血液', example: 'El análisis de sangre es mañana.', exampleChinese: '验血安排在明天。', lemma: 'sangre', partOfSpeech: 'noun', frequencyRank: 868 },
      { spanish: 'espalda', chinese: '背；背部', example: 'Me duele la espalda.', exampleChinese: '我背疼。', lemma: 'espalda', partOfSpeech: 'noun', frequencyRank: 1985 },
      { spanish: 'cuello', chinese: '脖子；衣领', example: 'Tengo frío en el cuello.', exampleChinese: '我脖子觉得冷。', lemma: 'cuello', partOfSpeech: 'noun', frequencyRank: 2075 },
      { spanish: 'pecho', chinese: '胸部；胸膛', example: 'Siento dolor en el pecho.', exampleChinese: '我胸部感到疼痛。', lemma: 'pecho', partOfSpeech: 'noun', frequencyRank: 2219 },
      { spanish: 'pared', chinese: '墙', example: 'El espejo está en la pared.', exampleChinese: '镜子在墙上。', lemma: 'pared', partOfSpeech: 'noun', frequencyRank: 2677 },
      { spanish: 'dedo', chinese: '手指；脚趾', example: 'Me he cortado un dedo.', exampleChinese: '我割伤了一根手指。', lemma: 'dedo', partOfSpeech: 'noun', frequencyRank: 2823 },
      { spanish: 'techo', chinese: '屋顶；天花板', example: 'El techo es muy alto.', exampleChinese: '天花板很高。', lemma: 'techo', partOfSpeech: 'noun', frequencyRank: 2848 },
      { spanish: 'espejo', chinese: '镜子', example: 'Hay un espejo junto a la puerta.', exampleChinese: '门旁边有一面镜子。', lemma: 'espejo', partOfSpeech: 'noun', frequencyRank: 3178 },
      { spanish: 'nariz', chinese: '鼻子', example: 'Tengo la nariz fría.', exampleChinese: '我的鼻子很凉。', lemma: 'nariz', partOfSpeech: 'noun', frequencyRank: 4024 },
      { spanish: 'vaso', chinese: '玻璃杯；一杯', example: 'Quiero un vaso de agua.', exampleChinese: '我想要一杯水。', lemma: 'vaso', partOfSpeech: 'noun', frequencyRank: 4129 },
      { spanish: 'apartamento', chinese: '公寓', example: 'El apartamento tiene dos habitaciones.', exampleChinese: '这套公寓有两个房间。', lemma: 'apartamento', partOfSpeech: 'noun', frequencyRank: 4216 },
    ],
  },
  {
    id: 'expansion-a1-food-nature-006', level: 'A1', scene: '日常', title: '食物与自然环境',
    description: '谈论基本食材、天气和周围自然景物',
    frameworkReference: A1_A2_PCIC,
    words: [
      { spanish: 'río', chinese: '河；河流', example: 'El río pasa cerca del pueblo.', exampleChinese: '河流经过小镇附近。', lemma: 'río', partOfSpeech: 'noun', frequencyRank: 698 },
      { spanish: 'fuego', chinese: '火；火灾', example: 'No hagas fuego en el bosque.', exampleChinese: '不要在森林里生火。', lemma: 'fuego', partOfSpeech: 'noun', frequencyRank: 851 },
      { spanish: 'naturaleza', chinese: '自然；大自然', example: 'Me gusta caminar por la naturaleza.', exampleChinese: '我喜欢在大自然中散步。', lemma: 'naturaleza', partOfSpeech: 'noun', frequencyRank: 1059 },
      { spanish: 'luna', chinese: '月亮', example: 'La luna está llena esta noche.', exampleChinese: '今晚是满月。', lemma: 'luna', partOfSpeech: 'noun', frequencyRank: 1416 },
      { spanish: 'piedra', chinese: '石头；石材', example: 'El camino tiene mucha piedra.', exampleChinese: '这条路上有很多石头。', lemma: 'piedra', partOfSpeech: 'noun', frequencyRank: 1524 },
      { spanish: 'planeta', chinese: '行星；星球', example: 'La Tierra es un planeta.', exampleChinese: '地球是一颗行星。', lemma: 'planeta', partOfSpeech: 'noun', frequencyRank: 1585 },
      { spanish: 'arena', chinese: '沙；沙滩', example: 'La arena está caliente.', exampleChinese: '沙子很热。', lemma: 'arena', partOfSpeech: 'noun', frequencyRank: 2377 },
      { spanish: 'temperatura', chinese: '温度；体温', example: 'La temperatura baja por la noche.', exampleChinese: '夜间温度下降。', lemma: 'temperatura', partOfSpeech: 'noun', frequencyRank: 2427 },
      { spanish: 'aceite', chinese: '油；食用油', example: 'La ensalada lleva aceite de oliva.', exampleChinese: '沙拉里有橄榄油。', lemma: 'aceite', partOfSpeech: 'noun', frequencyRank: 2856 },
      { spanish: 'queso', chinese: '奶酪', example: 'Este queso es suave.', exampleChinese: '这种奶酪味道温和。', lemma: 'queso', partOfSpeech: 'noun', frequencyRank: 2948 },
      { spanish: 'nieve', chinese: '雪', example: 'La montaña tiene nieve en invierno.', exampleChinese: '这座山冬天有雪。', lemma: 'nieve', partOfSpeech: 'noun', frequencyRank: 3344 },
      { spanish: 'naranja', chinese: '橙子；橙色', example: 'Tomo una naranja en el desayuno.', exampleChinese: '我早餐吃一个橙子。', lemma: 'naranja', partOfSpeech: 'noun', frequencyRank: 4180 },
    ],
  },
  {
    id: 'expansion-a2-digital-life-006', level: 'A2', scene: '科技', title: '数字设备与网络操作',
    description: '使用网页、应用、账号和常见电子设备',
    frameworkReference: A1_A2_PCIC,
    words: [
      { spanish: 'web', chinese: '网站；网络', example: 'La web funciona en el móvil.', exampleChinese: '这个网站可以在手机上使用。', lemma: 'web', partOfSpeech: 'noun', frequencyRank: 427 },
      { spanish: 'sitio', chinese: '地方；网站', example: 'Este sitio ofrece información útil.', exampleChinese: '这个网站提供有用信息。', lemma: 'sitio', partOfSpeech: 'noun', frequencyRank: 439 },
      { spanish: 'vídeo', chinese: '视频', example: 'El vídeo dura dos minutos.', exampleChinese: '视频时长两分钟。', lemma: 'vídeo', partOfSpeech: 'noun', frequencyRank: 1130 },
      { spanish: 'aplicación', chinese: '应用；申请', example: 'La aplicación guarda el progreso.', exampleChinese: '应用会保存进度。', lemma: 'aplicación', partOfSpeech: 'noun', frequencyRank: 1131 },
      { spanish: 'usuario', chinese: '用户', example: 'Cada usuario tiene un perfil.', exampleChinese: '每位用户都有一个个人资料。', lemma: 'usuario', partOfSpeech: 'noun', frequencyRank: 1230 },
      { spanish: 'perfil', chinese: '个人资料；轮廓', example: 'Puedes cambiar la foto del perfil.', exampleChinese: '你可以更换个人资料照片。', lemma: 'perfil', partOfSpeech: 'noun', frequencyRank: 1616 },
      { spanish: 'ubicación', chinese: '位置；定位', example: 'La aplicación pide tu ubicación.', exampleChinese: '应用请求你的位置信息。', lemma: 'ubicación', partOfSpeech: 'noun', frequencyRank: 2851 },
      { spanish: 'cable', chinese: '电线；数据线', example: 'Necesito un cable para cargar el teléfono.', exampleChinese: '我需要一根线给手机充电。', lemma: 'cable', partOfSpeech: 'noun', frequencyRank: 3034 },
      { spanish: 'batería', chinese: '电池；电量', example: 'La batería está casi vacía.', exampleChinese: '电池快没电了。', lemma: 'batería', partOfSpeech: 'noun', frequencyRank: 3101 },
      { spanish: 'computadora', chinese: '电脑', example: 'La computadora necesita una actualización.', exampleChinese: '电脑需要更新。', lemma: 'computadora', partOfSpeech: 'noun', frequencyRank: 3469 },
      { spanish: 'actualización', chinese: '更新；升级', example: 'La actualización tarda unos minutos.', exampleChinese: '更新需要几分钟。', lemma: 'actualización', partOfSpeech: 'noun', frequencyRank: 3752 },
      { spanish: 'descarga', chinese: '下载；卸货', example: 'La descarga comienza ahora.', exampleChinese: '下载现在开始。', lemma: 'descarga', partOfSpeech: 'noun', frequencyRank: 4001 },
    ],
  },
  {
    id: 'expansion-a2-study-services-006', level: 'A2', scene: '学习', title: '学习、办事与工作安排',
    description: '处理课程、证件、工资和日常时间安排',
    frameworkReference: A1_A2_PCIC,
    words: [
      { spanish: 'opción', chinese: '选项；选择', example: 'Esta opción es más barata.', exampleChinese: '这个选择更便宜。', lemma: 'opción', partOfSpeech: 'noun', frequencyRank: 1146 },
      { spanish: 'llegada', chinese: '到达；抵达', example: 'La hora de llegada es las seis.', exampleChinese: '抵达时间是六点。', lemma: 'llegada', partOfSpeech: 'noun', frequencyRank: 1864 },
      { spanish: 'examen', chinese: '考试；检查', example: 'El examen empieza a las diez.', exampleChinese: '考试十点开始。', lemma: 'examen', partOfSpeech: 'noun', frequencyRank: 2024 },
      { spanish: 'periódico', chinese: '报纸', example: 'Leo el periódico durante el desayuno.', exampleChinese: '我早餐时读报纸。', lemma: 'periódico', partOfSpeech: 'noun', frequencyRank: 2041 },
      { spanish: 'turismo', chinese: '旅游；旅游业', example: 'El turismo crea trabajo en la región.', exampleChinese: '旅游业为该地区创造就业。', lemma: 'turismo', partOfSpeech: 'noun', frequencyRank: 2054 },
      { spanish: 'licencia', chinese: '许可证；执照', example: 'La licencia termina este mes.', exampleChinese: '许可证本月到期。', lemma: 'licencia', partOfSpeech: 'noun', frequencyRank: 2216 },
      { spanish: 'renta', chinese: '租金；收入', example: 'La renta se paga cada mes.', exampleChinese: '租金每月支付。', lemma: 'renta', partOfSpeech: 'noun', frequencyRank: 2634 },
      { spanish: 'turno', chinese: '轮次；班次；预约号', example: 'Mi turno empieza por la tarde.', exampleChinese: '我的班次下午开始。', lemma: 'turno', partOfSpeech: 'noun', frequencyRank: 2752 },
      { spanish: 'salario', chinese: '工资；薪水', example: 'El salario llega a final de mes.', exampleChinese: '工资月底到账。', lemma: 'salario', partOfSpeech: 'noun', frequencyRank: 2804 },
      { spanish: 'audio', chinese: '音频；声音', example: 'El audio no se escucha bien.', exampleChinese: '音频听不清楚。', lemma: 'audio', partOfSpeech: 'noun', frequencyRank: 2862 },
      { spanish: 'paquete', chinese: '包裹；套餐', example: 'El paquete llega mañana.', exampleChinese: '包裹明天到。', lemma: 'paquete', partOfSpeech: 'noun', frequencyRank: 3201 },
      { spanish: 'agenda', chinese: '日程本；议程', example: 'Anoto la cita en la agenda.', exampleChinese: '我把预约记在日程本上。', lemma: 'agenda', partOfSpeech: 'noun', frequencyRank: 3223 },
    ],
  },
  {
    id: 'expansion-b1-health-care-006', level: 'B1', scene: '健康', title: '健康、医疗与恢复',
    description: '理解检查、治疗、生活习惯和公共医疗信息',
    frameworkReference: B1_B2_PCIC,
    words: [
      { spanish: 'descanso', chinese: '休息；休假', example: 'El cuerpo necesita descanso.', exampleChinese: '身体需要休息。', lemma: 'descanso', partOfSpeech: 'noun', frequencyRank: 2876 },
      { spanish: 'virus', chinese: '病毒', example: 'El virus se transmite con facilidad.', exampleChinese: '这种病毒容易传播。', lemma: 'virus', partOfSpeech: 'noun', frequencyRank: 2961 },
      { spanish: 'laboratorio', chinese: '实验室；化验室', example: 'La muestra llega al laboratorio.', exampleChinese: '样本送到实验室。', lemma: 'laboratorio', partOfSpeech: 'noun', frequencyRank: 3057 },
      { spanish: 'tensión', chinese: '紧张；血压；电压', example: 'La enfermera mide la tensión.', exampleChinese: '护士测量血压。', lemma: 'tensión', partOfSpeech: 'noun', frequencyRank: 3155 },
      { spanish: 'dieta', chinese: '饮食；食谱', example: 'Una dieta variada ayuda a la salud.', exampleChinese: '多样化饮食有益健康。', lemma: 'dieta', partOfSpeech: 'noun', frequencyRank: 3480 },
      { spanish: 'recuperación', chinese: '恢复；康复', example: 'La recuperación requiere paciencia.', exampleChinese: '康复需要耐心。', lemma: 'recuperación', partOfSpeech: 'noun', frequencyRank: 3515 },
      { spanish: 'órgano', chinese: '器官；机构', example: 'El corazón es un órgano vital.', exampleChinese: '心脏是重要器官。', lemma: 'órgano', partOfSpeech: 'noun', frequencyRank: 3664 },
      { spanish: 'alimentación', chinese: '饮食；营养供给', example: 'La alimentación influye en el bienestar.', exampleChinese: '饮食影响健康状态。', lemma: 'alimentación', partOfSpeech: 'noun', frequencyRank: 3825 },
      { spanish: 'cirugía', chinese: '外科手术；外科', example: 'La cirugía duró dos horas.', exampleChinese: '手术持续了两个小时。', lemma: 'cirugía', partOfSpeech: 'noun', frequencyRank: 3905 },
      { spanish: 'sanidad', chinese: '医疗卫生系统', example: 'La sanidad pública necesita recursos.', exampleChinese: '公共医疗系统需要资源。', lemma: 'sanidad', partOfSpeech: 'noun', frequencyRank: 3959 },
      { spanish: 'prevención', chinese: '预防', example: 'La prevención reduce muchos riesgos.', exampleChinese: '预防能降低许多风险。', lemma: 'prevención', partOfSpeech: 'noun', frequencyRank: 4104 },
      { spanish: 'clínica', chinese: '诊所；临床的', example: 'La clínica abre todos los días.', exampleChinese: '诊所每天营业。', lemma: 'clínica', partOfSpeech: 'noun', frequencyRank: 4142 },
    ],
  },
  {
    id: 'expansion-b1-learning-work-006', level: 'B1', scene: '工作', title: '学习流程与工作协作',
    description: '解释程序、能力、规则和团队协作方式',
    frameworkReference: B1_B2_PCIC,
    words: [
      { spanish: 'explicación', chinese: '解释；说明', example: 'La explicación incluye un ejemplo práctico.', exampleChinese: '说明中包含一个实际例子。', lemma: 'explicación', partOfSpeech: 'noun', frequencyRank: 2500 },
      { spanish: 'procedimiento', chinese: '程序；步骤', example: 'El procedimiento tiene tres pasos.', exampleChinese: '这个程序有三个步骤。', lemma: 'procedimiento', partOfSpeech: 'noun', frequencyRank: 2521 },
      { spanish: 'talento', chinese: '才华；人才', example: 'El equipo busca talento local.', exampleChinese: '团队正在寻找当地人才。', lemma: 'talento', partOfSpeech: 'noun', frequencyRank: 2581 },
      { spanish: 'entorno', chinese: '环境；周边', example: 'Necesitamos un entorno seguro para trabajar.', exampleChinese: '我们需要安全的工作环境。', lemma: 'entorno', partOfSpeech: 'noun', frequencyRank: 2605 },
      { spanish: 'regla', chinese: '规则；尺子', example: 'Cada actividad tiene una regla clara.', exampleChinese: '每项活动都有明确规则。', lemma: 'regla', partOfSpeech: 'noun', frequencyRank: 2632 },
      { spanish: 'taller', chinese: '工作坊；维修店', example: 'El taller ofrece formación práctica.', exampleChinese: '工作坊提供实践培训。', lemma: 'taller', partOfSpeech: 'noun', frequencyRank: 2638 },
      { spanish: 'ventaja', chinese: '优势；好处', example: 'La experiencia es una ventaja importante.', exampleChinese: '经验是一项重要优势。', lemma: 'ventaja', partOfSpeech: 'noun', frequencyRank: 2640 },
      { spanish: 'enseñanza', chinese: '教学；教育', example: 'La enseñanza combina teoría y práctica.', exampleChinese: '教学结合理论与实践。', lemma: 'enseñanza', partOfSpeech: 'noun', frequencyRank: 2654 },
      { spanish: 'entrenamiento', chinese: '训练；培训', example: 'El entrenamiento empieza esta semana.', exampleChinese: '培训本周开始。', lemma: 'entrenamiento', partOfSpeech: 'noun', frequencyRank: 2656 },
      { spanish: 'funcionamiento', chinese: '运行；运作方式', example: 'El manual explica el funcionamiento del sistema.', exampleChinese: '手册解释系统的运行方式。', lemma: 'funcionamiento', partOfSpeech: 'noun', frequencyRank: 2664 },
      { spanish: 'cooperación', chinese: '合作；协作', example: 'La cooperación entre equipos es esencial.', exampleChinese: '团队间协作至关重要。', lemma: 'cooperación', partOfSpeech: 'noun', frequencyRank: 2702 },
      { spanish: 'encuesta', chinese: '调查；问卷', example: 'La encuesta recoge opiniones de usuarios.', exampleChinese: '问卷收集用户意见。', lemma: 'encuesta', partOfSpeech: 'noun', frequencyRank: 2711 },
    ],
  },
  {
    id: 'expansion-b2-systems-006', level: 'B2', scene: '社会', title: '系统、标准与公共发展',
    description: '分析基础设施、规范、进展和社会系统变化',
    frameworkReference: B1_B2_PCIC,
    words: [
      { spanish: 'potencial', chinese: '潜力；潜在的', example: 'La región tiene potencial turístico.', exampleChinese: '该地区具有旅游潜力。', lemma: 'potencial', partOfSpeech: 'noun', frequencyRank: 2629 },
      { spanish: 'fenómeno', chinese: '现象', example: 'El informe estudia un fenómeno social.', exampleChinese: '报告研究一种社会现象。', lemma: 'fenómeno', partOfSpeech: 'noun', frequencyRank: 2662 },
      { spanish: 'infraestructura', chinese: '基础设施', example: 'La ciudad mejora su infraestructura pública.', exampleChinese: '城市正在改善公共基础设施。', lemma: 'infraestructura', partOfSpeech: 'noun', frequencyRank: 2724 },
      { spanish: 'ingeniería', chinese: '工程学；工程技术', example: 'La ingeniería aporta soluciones técnicas.', exampleChinese: '工程技术提供技术解决方案。', lemma: 'ingeniería', partOfSpeech: 'noun', frequencyRank: 2725 },
      { spanish: 'interpretación', chinese: '解释；口译；理解', example: 'La interpretación de los datos exige cuidado.', exampleChinese: '解读数据需要谨慎。', lemma: 'interpretación', partOfSpeech: 'noun', frequencyRank: 2726 },
      { spanish: 'lógica', chinese: '逻辑', example: 'No entiendo la lógica de esa decisión.', exampleChinese: '我不理解那项决定的逻辑。', lemma: 'lógica', partOfSpeech: 'noun', frequencyRank: 2732 },
      { spanish: 'progreso', chinese: '进步；进展', example: 'El gráfico muestra el progreso mensual.', exampleChinese: '图表显示每月进展。', lemma: 'progreso', partOfSpeech: 'noun', frequencyRank: 2744 },
      { spanish: 'norma', chinese: '规范；标准；规定', example: 'La nueva norma entra en vigor mañana.', exampleChinese: '新规定明天生效。', lemma: 'norma', partOfSpeech: 'noun', frequencyRank: 2789 },
      { spanish: 'porcentaje', chinese: '百分比', example: 'El porcentaje aumentó este año.', exampleChinese: '今年这一百分比上升了。', lemma: 'porcentaje', partOfSpeech: 'noun', frequencyRank: 2795 },
      { spanish: 'índice', chinese: '指数；索引', example: 'El índice refleja el cambio de precios.', exampleChinese: '该指数反映价格变化。', lemma: 'índice', partOfSpeech: 'noun', frequencyRank: 2915 },
      { spanish: 'mantenimiento', chinese: '维护；保养', example: 'El edificio necesita mantenimiento regular.', exampleChinese: '这栋楼需要定期维护。', lemma: 'mantenimiento', partOfSpeech: 'noun', frequencyRank: 2939 },
      { spanish: 'reducción', chinese: '减少；降低', example: 'La reducción del consumo ahorra energía.', exampleChinese: '降低消耗可以节省能源。', lemma: 'reducción', partOfSpeech: 'noun', frequencyRank: 3011 },
    ],
  },
  {
    id: 'expansion-b2-analysis-006', level: 'B2', scene: '学习', title: '研究、论证与评估',
    description: '组织分析、评估证据并表达复杂关系',
    frameworkReference: B1_B2_PCIC,
    words: [
      { spanish: 'concentración', chinese: '集中；浓度；专注', example: 'La tarea requiere mucha concentración.', exampleChinese: '这项任务需要高度专注。', lemma: 'concentración', partOfSpeech: 'noun', frequencyRank: 2815 },
      { spanish: 'difusión', chinese: '传播；推广', example: 'La difusión del informe fue limitada.', exampleChinese: '报告的传播范围有限。', lemma: 'difusión', partOfSpeech: 'noun', frequencyRank: 2925 },
      { spanish: 'evaluación', chinese: '评估；评价', example: 'La evaluación identifica los puntos débiles.', exampleChinese: '评估找出了薄弱点。', lemma: 'evaluación', partOfSpeech: 'noun', frequencyRank: 3320 },
      { spanish: 'enfoque', chinese: '方法；视角；重点', example: 'El estudio utiliza un enfoque diferente.', exampleChinese: '该研究采用不同方法。', lemma: 'enfoque', partOfSpeech: 'noun', frequencyRank: 3318 },
      { spanish: 'estabilidad', chinese: '稳定；稳定性', example: 'La medida busca estabilidad económica.', exampleChinese: '这项措施旨在实现经济稳定。', lemma: 'estabilidad', partOfSpeech: 'noun', frequencyRank: 3405 },
      { spanish: 'revisión', chinese: '复查；修订；检修', example: 'El texto necesita una revisión final.', exampleChinese: '文章需要最后复核。', lemma: 'revisión', partOfSpeech: 'noun', frequencyRank: 3360 },
      { spanish: 'fórmula', chinese: '公式；配方；办法', example: 'No existe una fórmula única para resolverlo.', exampleChinese: '解决它没有唯一公式。', lemma: 'fórmula', partOfSpeech: 'noun', frequencyRank: 3484 },
      { spanish: 'equilibrio', chinese: '平衡', example: 'Buscamos un equilibrio entre costo y calidad.', exampleChinese: '我们寻求成本与质量之间的平衡。', lemma: 'equilibrio', partOfSpeech: 'noun', frequencyRank: 3626 },
      { spanish: 'mecanismo', chinese: '机制；装置', example: 'El acuerdo incluye un mecanismo de control.', exampleChinese: '协议包含一个监督机制。', lemma: 'mecanismo', partOfSpeech: 'noun', frequencyRank: 3640 },
      { spanish: 'reflexión', chinese: '思考；反思', example: 'El resultado merece una reflexión profunda.', exampleChinese: '这个结果值得深入思考。', lemma: 'reflexión', partOfSpeech: 'noun', frequencyRank: 3656 },
      { spanish: 'tesis', chinese: '论文；论点', example: 'La autora defiende su tesis con datos.', exampleChinese: '作者用数据支持她的论点。', lemma: 'tesis', partOfSpeech: 'noun', frequencyRank: 3659 },
      { spanish: 'autonomía', chinese: '自主权；自主能力', example: 'El programa fomenta la autonomía del estudiante.', exampleChinese: '该项目培养学生的自主能力。', lemma: 'autonomía', partOfSpeech: 'noun', frequencyRank: 3673 },
    ],
  },
]
